### ISSUE TITLE
SNAPLib/AlignerContext.cpp:379:34: error: expected ')'

### ISSUE THREAD

**Issue by jankovanbeek** [jodyphelan/TBProfiler#1]
While installing TB profiler, I get the following error message:

SNAPLib/AlignerContext.cpp:379:34: error: expected ')'
                FormatUIntWithCommas((unsigned _int64)(1000 * stats->totalReads / max(alignTime, (_int64)1)), readsPerSecond, ...
                                               ^
SNAPLib/AlignerContext.cpp:379:24: note: to match this '('
                FormatUIntWithCommas((unsigned _int64)(1000 * stats->totalReads / max(alignTime, (_int64)1)), readsPerSecond, ...

It seems like a bracket is missing somewhere. Could you please have a look?

All the best, 

Janko

**Comment by jodyphelan** [comment]
Hi, can you let me know which version of g++ you are using? and are you running linux or osX?

**Comment by jankovanbeek** [comment]
Hi Jody,

I am using mac os x 10.11.6. I ran g++ -v and got this output:

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Hope that helps! Please let me know if you need any further information.

All the best, 

Janko

**Comment by jankovanbeek** [comment]
Hi Jody,

Did you had time to have a look to this issue? I would like to test the TB profiler on a large set of samples, including samples larger than 1 gb, so your help is much appreciated. 

All the best, 

Janko

**Comment by jodyphelan** [comment]
Hi Janko,

Apologies for the delay I think this might be an issue with the version of g++. Snap GitHub states that it should compile on a OS X with version 4.6. I don't have access to a mac at the moment so cannot test however I will try to asap to test. In the meantime try upgrading and see if that works.

Best,
Jody

**Comment by jodyphelan** [comment]
I have included a os X version in the installation script now

Use these commands to proceed:
```
git clone --recursive https://github.com/jodyphelan/TBProfiler.git
cd TBProfiler
bash osX_install_prerequisites.sh
echo "export PATH=\$PATH:$PWD" >> ~/.bashrc
```

This should install everything you need to run. 
Let me know if there are any other isssues

Best,
Jody

**Comment by jodyphelan** [comment]
Seems the compiled version of snap does not produce valid SAM/BAM files with some samples I tested - I have moved to BWA for os X. Sadly this increases the processing time - however it seem the only fix for now.

**Comment by jankovanbeek** [comment]
Hi Jody,
Thanks for your help. Installing G++ 4.6 using macports did solve my problem described above. The wget command in the osX_install_prerequisites.sh gave some problems on mac os x as well, but this could be solved by running the install prerequisites script line by line, and downloading both files which are downloaded by wget manually. I will try some other files these days and hope the BWA is not too slow.
All the best, Janko

**Comment by jodyphelan** [comment]
Ok let me know if you have any other problems!

Jody
