### ISSUE TITLE
TBProfiler Lineage

### ISSUE THREAD

**Issue by ksw9** [jodyphelan/TBProfiler#101]
Hi, 

Thanks for a great tool. I'm running into errors lineage typing in my samples. When I try tb-profiler on the test data, with the command 
```
tb-profiler profile -1 ERR1664619_1.fastq.gz -2 ERR1664619_2.fastq.gz -t 4 -p ERR1664619 --csv

```
I get the following (cut and pasted) results: 
```
TBProfiler report
--------------

Summary
-------
ID,ERR1664619
Date,Fri Mar 27 21:47:09 2020
Strain,root
Drug-resistance,XDR

Lineage report
--------------
Lineage,Estimated Fraction,Family,Spoligotype,Rd



Resistance report
-----------------
Drug,Genotypic Resistance,Mutations
"Rifampicin","R","rpoB p.Ser450Leu (1.00)"
```

I'm using TBProfiler version 2.8.5, downloaded from conda. Should there be a lineage reported in the test data?

Any suggestions would be great. Thank you!

**Comment by jodyphelan** [comment]
Hi @ksw9! 

It should indeed, thanks for letting me know. I'll look into this now.

Jody

**Comment by ksw9** [comment]
Thank you, I really appreciate it!

**Comment by jodyphelan** [comment]
The problem was that I have recently altered the format of the database recently. If you upgrade to v2.8.6 it should work. Let me know how it goes!

**Comment by ksw9** [comment]
Fantastic, it's working now as expected. Thanks for the quick response!
Best,

**Comment by ksw9** [comment]
One other question about lineage typing - I've noticed that some samples are assigned to lineage, while others are assigned to a more specific sub-lineage. What determines the level of lineage assignment, is there some cutoff for coverage or # of lineage-defining SNPs required to assign each additional sub-lineage? Thanks again and best,

**Comment by jodyphelan** [comment]
No probs!

Not all the lineages are classified to the same level (see [this table](https://static-content.springer.com/esm/art%3A10.1038%2Fncomms5812/MediaObjects/41467_2014_BFncomms5812_MOESM885_ESM.xlsx)). Depending on the phylogenetic clustering observed, different degrees of levels were assigned for different sublineages. This has all been pre-computed and is detailed [here](https://www.nature.com/articles/ncomms5812#Sec11). The TB-Profiler algorithm just looks for the SNPs which define each of the subclades.

Hope that explains it but I'm happy to go into more detail if you want!

Jody

**Comment by ksw9** [comment]
Great, thanks, this is really helpful. 

I had been trying to use estimated fraction to identify likely mixed infections, but how would you interpret the following lineage report? Should I consider this 5% Lineage4.6?
Thanks!

```
Date,Mon Mar 30 15:26:39 2020
Strain,lineage4.6;lineage4.3.3
Drug-resistance,Sensitive

Lineage report
--------------
Lineage,Estimated Fraction,Family,Spoligotype,Rd
"lineage4",1.000,"Euro-American","LAM;T;S;X;H","None"
"lineage4.6",0.053,"Euro-American","T;LAM","None"
"lineage4.3",1.000,"Euro-American (LAM)","mainly-LAM","None"
"lineage4.3.3",1.000,"Euro-American (LAM)","LAM;T","RD115"
```

**Comment by jodyphelan** [comment]
I would say this is most likely a pure lienage4.3.3 sample. All the fractions in the levels leading up to and including lineage4.3.3 are at 1.0 and the fraction for lineage4.6 is very low. There are 3 variants used to make the 4.6 call (54304,3170460 and 3466426) . It could be that one of them has a false positive mixed variant and is leading to the result that we see. It might be worthwhile looking at these sites to determine what is driving this. In general, tb-profiler requires all the variants associated with a lineage to have roughly the same fraction of ref/alt for it to be reported. I will have a look in my isolates to see if I can find the same result and that might tell us what is happening.

**Comment by jodyphelan** [comment]
Hi again, I've done some digging in the SRA and found a few samples with similar patterns. Let's take a look at **ERR1213931** for example. Here is the lineage report:

```
Lineage report
--------------
Lineage,Estimated Fraction,Family,Spoligotype,Rd
"lineage4",1.000,"Euro-American","LAM;T;S;X;H","None"
"lineage4.6",0.119,"Euro-American","T;LAM","None"
"lineage4.3",0.952,"Euro-American (LAM)","mainly-LAM","None"
"lineage4.3.3",0.914,"Euro-American (LAM)","LAM;T","RD115"
"lineage4.6.1.2",0.061,"Euro-American","T2","RD724"
```

The fraction of reads for lineage4.3 and 4.3.3 in the roughly the same and that for lineage4.6 and 4.6.1.2 is also roughly the same. My first guess is that this is a mix between a lineage4.3.3 and 4.6.1.2 which is what the pipeline outputs as the strain in the summary section. I've created a little extra functionality for the pipeline if you want to investigate further. If you run `tb-profiler lineage -a ERR1213931.bam -p ERR1213931 --snps` you will get a file called `ERR1213931.lineage.snps.txt` which will show the number of reads supporting each lineage snp in the barcode. From this we can see the following:

```
1098698 lineage4.6.1.2  0       29      0.0
1391868 lineage4.6.1.2  0       28      0.0
1501468 lineage4.6.1.2  5       33      0.13157894736842105
1832350 lineage4.6.1.2  8       50      0.13793103448275862
3332626 lineage4.6.1.2  0       40      0.0
3423426 lineage4.6.1.2  0       20      0.0
```

This shows us only two SNPs (at 1501468 and 1832350) have any reads supporting the lineage. Thes rest seems to indicate we do not have lineage4.6.1.2. Looking at the bam file in IGV or tablet I can see there are quite a few mixed calls. Based on this I would rule out a mixed infection. You might have to go through the difficult ones on a case by case basis as I haven't found a rule set which works for all. If you have any suggestions let me know and I would be more than happy to build it in. 

If you want to use the `--snps` flag in the `tb-profiler lineage` function you will have to use the latest commit from github but I'll try release a conda update soon too!

Hope that helps!

**Comment by ksw9** [comment]
Hi Jody,
I forgot to respond and say thank you so much for the clear explanation! This really helps.
Thanks and best!

**Comment by jodyphelan** [comment]
No probs!
