### ISSUE TITLE
Amino acid accuracy

### ISSUE THREAD

**Issue by mriglobal** [jodyphelan/TBProfiler#103]
I was exploring the results of running tb-profiler profile and pulling the nucleotide sequences from the H37Rv reference according to the output. I found multiple amino acid sequences that did not appear to match the codon at that position or a nearby position (to account for possible indexing differences).
For instance, at position 761155, I'm finding GGC, which translates to Glycine, not Serine or Proline.

Such examples were:

`7572    Rv0006  gyrA    p.Ser91Pro  1.000   ciprofloxacin,moxifloxacin,ofloxacin,levofloxacin,fluoroquinolones
761155  Rv0667  rpoB    p.Ser450Leu 1.000   rifampicin
1473246 rrs rrs r.1401a>g   1.000   kanamycin,aminoglycosides,capreomycin,amikacin
2155168 Rv1908c katG    p.Ser315Thr 1.000   isoniazid
4327347 Rv3854c ethA    p.Gly43Ser  1.000   ethionamide`

**Comment by jodyphelan** [comment]
Thanks for reporting this issue, can you confirm which reference genome you are using to find the codon sequences?

Thanks,
Jody

**Comment by mriglobal** [comment]
My apologies. I'm pulling from NC_000962.3 H37Rv

**Comment by jodyphelan** [comment]
No probs, this is the identical version as used in tb-profiler so that is fine. How are you extracting the codon?  
Just taking your example of the mutation at 761155. It is located in the second position of the codon so the genomic coordinates of the codon should be 761154 - 761156 (corresponding to TCG / Ser). I've highlighted this below using [artemis](https://www.sanger.ac.uk/science/tools/artemis).

![image](https://user-images.githubusercontent.com/8697224/81591017-a4b55e00-93b3-11ea-9acf-d190a948db46.png)

**Comment by jodyphelan** [comment]
I've uploaded a text file with the nucleotide positions mapped to the codon positions for drug resistance genes if you are interested. You can download it [here](https://send.firefox.com/download/d76a1359f029203f/#yrSsjKA59uprlt4agxF5fQ).

**Comment by mriglobal** [comment]
Can you help me read this? Looking at position 7572, it seems that we have a T as the wild-type base at that position, with A/C/G as alternatives, making the codons as listed in order that correspond to the amino acids, with TCG and Serine as the wild types, respectively.

Chromosome 7572 T A C G TCG 1 ACG CCG GCG S T P A Rv0006 gyrA . CDS 7302 9818 + 1 0 91 271 gyrB-gyrA

But, when I look at 2155168, it seems that C would be the wild type nucleotide? However, in the listed codons, the C is not the base that changes and in fact is expressed as one of the alternates.

Chromosome 2155168 C A T G AGC 2 ATC AAC ACC S I N T

I must be interpreting the table wrong. Do you have a header line for these or some other clarity?

Thank you!

**Comment by jodyphelan** [comment]
For the genes on the complement strand (ending in "c") you will need to take the reverse complement base so for this example C->G which matches with the second position of the codon "AGC" now.
