### ISSUE TITLE
Root as lineage

### ISSUE THREAD

**Issue by conmeehan** [jodyphelan/TBProfiler#104]
Hi,

For some of our samples we get in the summary file 'root' for the lineage and it is blank. I assume this means no SNPs associated with the lineage were found but from MTBseq many come out as L3. Any idea why this might happen?

Kind regards,
Conor

**Comment by jodyphelan** [comment]
Hi Conor,

I think this was an issue in some of the earlier releases of TB-Profiler can I confirm it is the latest version you are running?

Jody

**Comment by conmeehan** [comment]
Hey Jody,

Ok yes updating fixed it for most of them. The others, on closer inspection, have very little coverage at the lineage defining SNP position but good coverage in general, so I dont know whats goin on there. MTBseq called them as L3 but with little to no coverage of those SNPs. Its not a TB-profiler problem anyway that I can see, thanks!

Cheers,
Conor

**Comment by jodyphelan** [comment]
Ah cool! on the new version you can run `tb-profiler lineage`  with the `--snps` flag to get a detailed report of the numbers of reads aligning to each snp pos if you ever need it. It should be available in the next release (or now with the github version)

Jody
