### ISSUE TITLE
WT vs low coverage for DR

### ISSUE THREAD

**Issue by conmeehan** [jodyphelan/TBProfiler#107]
Hi Jody,

So I am having an issue with some WT calls. I have some samples where the specific positions are actually low coverage (depth <10 reads). TBprofiler calls this as WT when actually its more 'unknown due to low coverage of positions xx and yy'. Is there a way to have the output make that distinction? I want to be confident in my WT calls but right now I don't see how to do that.

Cheers,
Conor

**Comment by jodyphelan** [comment]
Hi Conor,

Oh yeah, that is a point, I'll try put in a feature for missing data. 
What would be the best way to report this? As an example, let's say the RRDR has low coverage for an isolate. Would is sufficient to report the gene/amino acid positions being affected?

Jody

**Comment by conmeehan** [comment]
Well the example we found it with is the gyrA Ala90 position. There is about 20 nucleotides there that are <10 coverage but the rest of the gene has great coverage, so when you look at the average per gene, like with bedtools, it looks fine, its only the per-position thats the issue.

So, I think reporting the gene and the specific amino acids is sufficient. Basically should be 'uncertain' or similar and then the SNPs that are giving that call, like you would for DR. WT should just be >10 reads on all AA that define that resistance, I guess.

Hope that makes sense!

**Comment by jodyphelan** [comment]
Yeah that makes sense! I've written a little update now that outputs the following section in the text output (and similar in the csv):

```
Missing positions report
---------------------
Gene_Id Position        Position_Type
Rv0667  -8      gene
Rv0667  -7      gene
Rv0667  -6      gene
Rv0667  -5      gene
Rv0667  -4      gene
Rv0667  -3      gene
Rv0667  -2      gene
Rv0667  -1      gene
Rv0667  1       codon
Rv0667  2       codon
```
It extracts based on a user-defined coverage threshold (default: 10) and then it reports the gene position if in a promoter/non-coding gene or the codon position if in a coding gene region. Would this be sufficient?

Jody

**Comment by conmeehan** [comment]
I think that starts to get at it. Does it list specifically those positions know to be involved in DR or all positions with low coverage? It is good to make this distinction so the user knows which is important, especially since it is tough to get exact genome positions for DR mutations from TBDB.

When will the update end up on conda? Then I can test it on our server and samples (it prefers conda to github cloning, its a headache).

**Comment by jodyphelan** [comment]
At the moment it only lists all of the positions, I can put in an extra column with whether or not it is in a DR position.

Strange on the jump in coverage, I had not noticed this myself. How were you assessing the coverage on 2.6? I have switched to `bedtools coverage` vs `samtools depth` so there might be some differences in the default filtering by the tools.

**Comment by conmeehan** [comment]
I think the extra column would be good so can easily scan and assess if WT can be 'trusted'.

I am using bedtools coverage for checking coverage in the bam files you produce. Was very odd but hopefully fixed ok now.

**Comment by jodyphelan** [comment]
Ok I've added the extra column and create a conda release. Should be available to test soon.

**Comment by conmeehan** [comment]
Ok, tested it and seems to work well. It is finding the positions that are not covered and putting them in the results. Thats great, thanks.
An additional feature that would be great is if this was then mentioined in the summary file of multiple samples. Something like a * or similar beside  the - for a drug to state that this WT prediction is unsure. That would be a massive help.

**Comment by jodyphelan** [comment]
Ok I've added in that function now. You should be able to activate it with `tb-profiler collate --mark_missing` in v2.8.9. A conda release should be available later today.

**Comment by conmeehan** [comment]
This seems to be working well now so thanks very muchf or those changes. Its a big help.

**Comment by jodyphelan** [comment]
No probs!

**Comment by malare** [comment]
Hi Jody,
I have questions related to the one above. How does TBprofiler handle duplicates and quality in general e.g. what Phred-score is used etc.?
Thank you and best wishes
