### ISSUE TITLE
Whole genome VCFs

### ISSUE THREAD

**Issue by jodyphelan** [jodyphelan/TBProfiler#109]
put the `--call_whole_genome` option back in

**Comment by malare** [comment]
Dear Jody,
In general, which genes are "targeted" genes i.e. which genes are included in the vcf files (using tbprofiler), only those with a mutation in the tbdb.csv file? E.g., the fbiD gene seems to be linked to potential delamanid resistance (https://www.biorxiv.org/content/10.1101/457754v1.full.pdf). I have a minor comment: Could you rename Rv2983 (Rv2983) with fbiD (Rv2983) in tbdb. According to: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6450877/ . I was wondering if mutations in the fbiD gene are included in vcf files (generated by tbprofiler)? Or do I have to use --call_whole_genome option to identify genes which have no mutation included in tbdb.csv yet?

Thank you!

**Comment by jodyphelan** [comment]
Hi @malare 

I have added in the changed the name of fbiD and added it to the [tbdb.watchlist.csv](https://github.com/jodyphelan/tbdb/blob/master/tbdb.watchlist.csv) (https://github.com/jodyphelan/tbdb/commit/eb6825e6f6c467b609043b407f78d51adbb2acba). This file is useful when you want to profile a gene but don't have a specific mutation. The variants will be present in the vcf and other output files.

I am also looking at an option to include a `--call_whole_genome` option where it would call variants on the whole genome and selectively extract the targets from this. It could be useful if you want to use the whole genome vcf for other downstream analysis. Would this be useful for you?

Jody

**Comment by malare** [comment]
Great, thank you, Jody! In summary, genes in the tbdb.csv and tbdb.watchlist.csv are "target" genes and for these variants are called and are thus included in the vcf. Other genes are not included in the vcf/output files?
I guess it is a good idea to have the option --call_whole_genome. It gives the option of selecting genes of interest. (This makes it a bit more flexible). However, if the tbdb.csv and tbdb.watchlist.csv are up to date, they include all relevant (drug resistance-conferring) genes, right? Further, WGS-vcf files could be useful for other tasks like phylogeny.

Best,

**Comment by jodyphelan** [comment]
Yes, exactly. Only those in the two files are extracted and analysed.

Cool I'll let you know when it is available!

**Comment by Ankita-1211** [comment]
Hey Jody

I need your help & suggestion in this.

I intend to make all known SNP database related to drug resistance in Mtb which can later be used in clinical diagnostic & screening of patient for drug resistance.

I am planning to collect all known SNP available in literature & various tool like yours & make  comprehensive database. am i doing correct. I do understand this is going to be very lengthy manual work. Need your help & suggestion.

TIA

P.s sorry using this thread wherein @malare has raised his issue. @malare need your inputs too. TIA

**Comment by jodyphelan** [comment]
Hi @Ankita-1211 

There are a couple of points/suggestions that you may find useful.

## Getting from curated lists

* There are many tools out there, all with their own lists. Some of the mutations may be present in multiple databases, others may be unique to one.
* It should be fairly easy to download the different lists of mutations, but the hard part will be to combine them as they all use different formats. For [tbdb](https://github.com/jodyphelan/tbdb) (the mutation list for TB-Profiler) I've used the standard [hgvs](https://varnomen.hgvs.org/) mutation format but others use custom formats. So it may require some data wrangling to get them all in the same format.
* Then you have to compare them. You will have to decide some rules on whether to include or exclude mutations from the combined list. This is easy for mutations such as _rpoB_ Ser450Leu (rifampicin) but get's more difficult when a variant is present in only one of the sources. Generally speaking, if a mutation is listed, it has been put in there for a reason and is likely to confer resistance, but some exceptions can occur (for example https://github.com/jodyphelan/tbdb/issues/1). 

## Getting from the literature
* This will be more lengthy and manual than sourcing from curated lists.
* Evidence for mutations can sometimes be lacking or contradictory, so setting out a defined criteria will help. Evidence can come from experimental and statistical data. Check out https://github.com/jodyphelan/tbdb/pull/20 for an example of how colleagues and I review mutations to merge into tbdb.
* I would say that most tools out there already have a pretty good list for the first-line drugs such as rifampicin and isoniazid, so a literature might be more fruitful for the less well-characterised drugs.


I would start by choosing a format that you would like to represent mutations with and then merging the lists of the different sources. You can then check the overlap between them and choose which ones to include/exclude. After that, you can try do a literature search to find potential new mutations. 

Let me know if you have any questions/thoughts.

Jody

**Comment by Ankita-1211** [comment]
Thank you Jody for your inputs .
Could you please help me with getting the genomic location for mutation in tbd.csv .

I was trying with tbprofiler_get_genome_pos.py script but was unsuccessful.

**Comment by jodyphelan** [comment]
No problem, I've transferred the issue [here](https://github.com/jodyphelan/tbdb/issues/27) as the script is part of this repo.

**Comment by Ankita-1211** [comment]
Sure, I will share the error in some time when I rerun.

I am in urgent need of getting the genomic location for antibiotics mutation reported in tbdb.csv.

If you have file at your end with genomic location , could you pls share.

TIA

**Comment by harrismia** [comment]
Hi Jody, 

   I would like to add a vote for the --call_whole_genome  option.  Having the whole genome VCF available would be very useful for our work.   

   Michael

**Comment by jodyphelan** [comment]
Hi Michael,

I have recently added a commit which adds in this option. By adding in the flag `--call_whole_genome` it will first produce a vcf file based on the whole genome. After that it will produce a separate vcf with only the calls overlapping resistance genes. If all the testing passes I will draft a new release on conda.

Jody

**Comment by harrismia** [comment]
Hi Jody, 

    That sounds perfect!   Thanks a lot, 

  Michael

**Comment by jodyphelan** [comment]
This is now implemented in release v3.0.4, which is also on conda. Let us know if there are any issues.
