### ISSUE TITLE
Why is TBProfilerFiles.tgz not in the repo?

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#11]
I am trying to package up TBProfiler but the external need to download `TBProfilerFiles.tgz` is problematic.

Is there a reason it isn't part of the github repo?
(and I don't mean tar.gz)

I notice it has `bwa` and `samtools` and `tabix` indices. These could be generated in your install script as bwa etc are dependencies anyway. Then you could just put the .fa and .gff in github?

```
ref/MTB-h37rv_asm19595v2-eg18.gff
ref/MTB-h37rv_asm19595v2-eg18.fa
ref/MTB-h37rv_asm19595v2-eg18.tab.ann.gz
ref/MTB-h37rv_asm19595v2-eg18.tab.ann.gz.tbi
ref/MTB-h37rv_asm19595v2-eg18.fa.pac
ref/MTB-h37rv_asm19595v2-eg18.fa.ann
ref/MTB-h37rv_asm19595v2-eg18.fa.amb
ref/MTB-h37rv_asm19595v2-eg18.fa.bwt
ref/MTB-h37rv_asm19595v2-eg18.fa.sa
ref/MTB-h37rv_asm19595v2-eg18.fa.fai
```

**Comment by jodyphelan** [comment]
Hi,

The reason is because the `MTB-h37rv_asm19595v2-eg18.tab.ann.gz` file is quite large and currently not possible to generate only from the .gff and .fa files. I will see if there is a way to either remove this dependency or create it from the .fa and .gff file.

Jody

**Comment by jodyphelan** [comment]
I have now updated much of the TBProfiler code and as part of that, the way the database is stored. 
The database is now shipped as part of the repo (making it ~4Mb in total).

**Comment by tseemann** [comment]
THis is good news @jodyphelan - thank you!
