### ISSUE TITLE
SNP INDEL Classes

### ISSUE THREAD

**Issue by vijay-naidu** [jodyphelan/TBProfiler#113]
Hello fellow researcher,

Great tool!!
I am not sure if this is the right place for my post. Apologies if not. I was wondering if there is way to distinguish SNPs from INDELs while calling for drug resistance? That is, adding classes for SNPs and INDELs, in addition to DR and lineage classes. May be filling the circles with different colors?

Cheers,
Vijay

**Comment by jodyphelan** [comment]
Hi Vijay,

Don't worry you're in the right place! Do you mean in the itol config? Filling in with a different colour depending on whether it was a SNP or indel conferring resistance?

**Comment by vijay-naidu** [comment]
Hi Jody,

Perfect!! Yes, that's exactly what I meant. How can we achieve this?

**Comment by jodyphelan** [comment]
I'll have a look at this in the next couple of days and let you know when it is ready to test.

**Comment by vijay-naidu** [comment]
Terrific. Thank you!!

**Comment by vijay-naidu** [comment]
Hi Jody,
How's it going? Any luck?
Cheers,
Vijay

**Comment by jodyphelan** [comment]
Hi Vijay,

I've had a look at it seems it is not possible using the current itol config system to make something which will represent the data in this way. The binary data type which I am currently using does not seem to allow different colours/shapes on the same line/drug (https://itol.embl.de/help.cgi#binary). I did find another type (pie chart) which does allow for different colours, however it is not possible to create one file for all the drugs and the labels can't be added to the plot (https://itol.embl.de/help.cgi#piechart). 

Just in case you want to take a look I created a script to have different colours for snp (red), small indels (green) and large deletions (blue). It creates one config per drug and you will have to add the labels after exporting in some image processing software. The script is available to download [here](https://raw.githubusercontent.com/jodyphelan/tbprofiler_scripts/master/tbprofiler_itol_drugs.py).

You can run it in the same way you run the collate function:
```
python tbprofiler_itol_drugs.py 
```
or if you have sample names in a file called samples.txt and you the json result files are stored in a location other than "results" you can do:
```
python ~/github/tbprofiler_scripts/tbprofiler_itol_drugs.py --samples samples.txt --dir /path/to/tbprofiler_results/
```

Let me know if this is useful, or if you have any other suggestions,
Jody

**Comment by vijay-naidu** [comment]
Hi Jody,

Many thanks for looking into this. Much appreciated.
I will certainly give this a try and let you know how it goes.

Cheers,
Vijay
