### ISSUE TITLE
BED file

### ISSUE THREAD

**Issue by pgcudahy** [jodyphelan/TBProfiler#115]
Hello, there are many things I don't completely get about genome coordinate systems, so this may be a mistake, but I was digging into some rpoB mutations in my samples and saw that your BED file defines rpoB/Rv0667 as `Chromosome	759310	763325	Rv0667	rpoB	rifampicin` while mycobrowser (https://mycobrowser.epfl.ch/genes/Rv0667) and tbdb (http://genome.tbdb.org/cgi-bin/GeneDetails.html?id=SRv0667) use 759807 - 763325. A google search for `759310 763325 tuberculosis` didn't come up with much, while `759807 763325 tuberculosis` had lots of hits.

**Comment by jodyphelan** [comment]
Hi @pgcudahy,

You're right the coding region of rpoB is  759807 - 763325. When the library is created, the script takes the intergenic region between Rv666 and Rv0667 to be able to look for promoter mutations. This is not so important for rifampicin but is useful for example with the inhA promoter mutation.

Jody

**Comment by pgcudahy** [comment]
Ah, thanks for the explanation
