### ISSUE TITLE
TB Dr profile iTOL

### ISSUE THREAD

**Issue by peflanag** [jodyphelan/TBProfiler#117]
Hi,

I was using the info from the collate option to put into iTOL but i get the error attached and the colours don't match.

Just wondering if it's a bug?

Cheers,

P

<img width="522" alt="Screenshot 2020-06-25 at 10 06 53" src="https://user-images.githubusercontent.com/32863969/85690837-dec09200-b6cb-11ea-838a-84066a2d282b.png">
<img width="156" alt="Screenshot 2020-06-25 at 10 07 04" src="https://user-images.githubusercontent.com/32863969/85690839-dff1bf00-b6cb-11ea-9412-1874ea5bfc53.png">
<img width="72" alt="Screenshot 2020-06-25 at 10 07 13" src="https://user-images.githubusercontent.com/32863969/85690841-dff1bf00-b6cb-11ea-950e-7442f3810bc7.png">
<img width="578" alt="Screenshot 2020-06-25 at 10 10 00" src="https://user-images.githubusercontent.com/32863969/85691098-1a5b5c00-b6cc-11ea-9439-0f39682993f7.png">

**Comment by peflanag** [comment]
Also, I ran a larger set of samples and get the following error. The names are correct so I dont know what the issue could be. Would it be that I removed all the results files into one folder in a new directory and ran collate on it without the bam and vcf folders in the same directory?

<img width="505" alt="Screenshot 2020-06-25 at 14 33 22" src="https://user-images.githubusercontent.com/32863969/85730354-80a6a580-b6f1-11ea-9ee4-abf524a17da5.png">

**Comment by jodyphelan** [comment]
Hi @peflanag 

Thanks for flagging that up, it does seem like a bug. I'll take a look and get back to you.

Jody

**Comment by peflanag** [comment]
Hey Jody,

No worries, I'm a complete novice so wasn't sure so I just opened the file and added a new colour code myself when I eventually realised how it works!

**Comment by jodyphelan** [comment]
Some rogue white space characters had replaced some of the code in the collate function. This should now be fixed! I'll release a conda update later today. Thanks again!

**Comment by peflanag** [comment]
No worries. Cheers for fixing!
