### ISSUE TITLE
Problem with webserver

### ISSUE THREAD

**Issue by matiassko** [jodyphelan/TBProfiler#119]
Hello Jody,

Can I have a question? Is there any problem with webserver TB Profiler? It is not possible to get the results (even after few days).

Thank you very much for your answer,

Best Regards,

Matus

**Comment by jodyphelan** [comment]
Hi Matus,

I'll take a look and get back to you.

Jody

**Comment by jodyphelan** [comment]
Seems there was a problem with the server, it should be fixed now but it is clearing a backlog of samples, so it might take a while to finish your sample. Try check back in a few hours and let me know if you samples still haven't finished yet.

**Comment by matiassko** [comment]
Thank you for your quick answer, Jody. Web Server is working very well!

Have a nice day, 

Matus

**Comment by jodyphelan** [comment]
Perfect, thanks for reporting!

**Comment by matiassko** [comment]
Hello Jody,

I think that the problem with webserver reappeared.
