### ISSUE TITLE
`stor_dir` is not used.

### ISSUE THREAD

**Issue by andersgs** [jodyphelan/TBProfiler#12]
Hello.

The `--dir` option doesn't seem to be plugged in. I see it in the class __init__ parameter as `stor_dir`, but that is not used to form path the storage directories of the various outputs. 

This seems to lead to a bug where the program searches for the `bam` files and other products in the wrong directory unless I use the default `.`.

Thank you.

Anders.

**Comment by jodyphelan** [comment]
Hi Anders,

I will take a look.

Jody

**Comment by jodyphelan** [comment]
Hi Anders,

I have updated TBProfiler now to use this option. Let me know if it works.

Jody
