### ISSUE TITLE
Error parsing

### ISSUE THREAD

**Issue by peflanag** [jodyphelan/TBProfiler#120]
Hi,

I ran TBprofiler and collate and now that I am trying to upload the iTOL files they wont upload. I have attached the errors I am getting. For any of the files it says to check the separator but I dont know what that is.

Any help would be great!

Cheers,

P

<img width="500" alt="Screenshot 2020-07-07 at 13 55 30" src="https://user-images.githubusercontent.com/32863969/86784809-d9fbc680-c059-11ea-8c61-efea590e58cf.png">

**Comment by jodyphelan** [comment]
Hi,

Is it just complaining about samples not being there or are there other errors too?
I'll test out on some trees I have and see  if I can replicate the error.

Jody

**Comment by peflanag** [comment]
As far as I can tell it's just the error above. I cant scroll to see if theres anything else.


P

**Comment by jodyphelan** [comment]
Seems to work ok with the trees I have, is there any discrepancy between the samples names that you can see in the text file and the tree?

**Comment by peflanag** [comment]
I’m away from the computer in question at the moment but will check when I get back. From memory though I think they where the same because I use the same nomenclature but will double check!

**Comment by peflanag** [comment]
So it turns out rather than the isolate names under the data column its give the prefix name?

**Comment by peflanag** [comment]
And I found out the reason! In my loop I didnt specify each isolate!

**Comment by jodyphelan** [comment]
Ah cool, is it working alright now?

**Comment by peflanag** [comment]
Its running again but I think it should work this time. I looped my script wrong thinking i was running a different program. I was wondering though, is there an easier way to loop it? Normally for other apps i use the "loop1" attached but i noticed for tbprofiler i have to use the "loop2" attached and specify each sample.

By the way, im not a bioinformatician im a molecular microbiologist so my knowledge of command is low and self thought!

P


[Loop1.zip](https://github.com/jodyphelan/TBProfiler/files/4891324/Loop1.zip)
[loop2.zip](https://github.com/jodyphelan/TBProfiler/files/4891327/loop2.zip)

**Comment by jodyphelan** [comment]
You can use the `--dir` flag to specify where you want the results to be stored. For example, if you had a file structure like this:
```
.
├── fastq
│   ├── ERR4161999_1.fastq.gz
│   ├── ERR4161999_2.fastq.gz
│   ├── ERR4162000_1.fastq.gz
│   ├── ERR4162000_2.fastq.gz
│   ├── ERR4162001_1.fastq.gz
│   ├── ERR4162001_2.fastq.gz
│   ├── ERR4162002_1.fastq.gz
│   ├── ERR4162002_2.fastq.gz
│   ├── ERR4162003_1.fastq.gz
│   └── ERR4162003_2.fastq.gz
├── script.sh
└── tbprofiler
```

A script like this would work:

```
#!/bin/sh

sampleLoc=fastq
sampleName=("ERR4161999"
"ERR4162000"
"ERR4162001"
"ERR4162002"
"ERR4162003")
outputLoc=tbprofiler

for sample in ${sampleName[*]}

do

tb-profiler profile -1 $sampleLoc/${sample}_1.fastq.gz -2 $sampleLoc/${sample}_2.fastq.gz  -p $sample --dir $outputLoc

done
```

**Comment by peflanag** [comment]
Amazing cheers!  will give this a go! It would help a lot for when I have a lot of samples cause I am currently writing each loaction!

**Comment by jodyphelan** [comment]
No probs! Let me know if there are any more issue with it.

**Comment by peflanag** [comment]
Cheers Jody!

P
