### ISSUE TITLE
Changing min_depth doesnt seem to work

### ISSUE THREAD

**Issue by conmeehan** [jodyphelan/TBProfiler#121]
Hi Jody,

I am trying to play around with changing the minimum depth thats needed to call an allele for tb-rpofiler profile. I use the following command:

tb-profiler profile --txt --csv --min_depth 1 --threads 8 --read1 sample1_R1.fastq.gz --read2 sample1_R2.fastq.gz 

However I get the same results if I set min_depth to 1, 10, 1000, or 10000.
I think this is meant to be done at the bcftools filter stage but I always see bcftools filter -e 'FMT/DP<10' -S . -Oz -o ./tbprofiler.{2}.vcf.gz for that command in the output given to the screen, suggesting that 10 is always being used and not changed if I am reading that right.

Can you tell me if I am doing something wrong?

Cheers,
Conor

**Comment by jodyphelan** [comment]
Hi Conor,

Ah this is most likely something wrong in the script. Probably the the min_depth value isn't being propagated through the functions. I'll take a look and get back to you.

Jody

**Comment by conmeehan** [comment]
Thanks so much, it would be massively helpful

C

**Comment by jodyphelan** [comment]
Ok, I've found the issue, tt is indeed not using the right value set by the user. In your case, would the values you use for the variant calling (--min_depth) and the missing threshold (--missing_cov_threshold) be different? Just checking to see if it would be useful to keep them separate or if this complicates things necessarily for users.

Jody

**Comment by conmeehan** [comment]
I think these would be separate but indeed perhaps this needs to be flagged to the user if missing_cov_threshold is now above the min_depth. Would that work?

**Comment by jodyphelan** [comment]
Yeah that should straightforward to put in. Will let you know when it is done.

**Comment by jodyphelan** [comment]
The new version (v2.8.12) should now be available on bioconda.

**Comment by conmeehan** [comment]
That seems to propogate properly now, thanks.

C
