### ISSUE TITLE
Version 2.8.12 Coverage Report showing 0 coverage for gene with resistance mutation with 1.0 fraction

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#123]
The coverage report is showing 0 coverage for positions that should have coverage.  For example the result file is below:

The resistance report shows rpoB p.Ser450Leu at a fraction of 1.0 but the coverage report shows rpoB with 0 fraction. 

Strain: lineage4.3.3
Drug-resistance: XDR

Lineage report
--------------
Lineage	Estimated Fraction	Family	Spoligotype	Rd
lineage4	1.000	Euro-American	LAM;T;S;X;H	None
lineage4.3	1.000	Euro-American (LAM)	mainly-LAM	None
lineage4.3.3	0.999	Euro-American (LAM)	LAM;T	RD115

Resistance report
-----------------
Drug	Genotypic Resistance	Mutations
Rifampicin	R	rpoB p.Ser450Leu (1.00)
Isoniazid	R	katG p.Ser315Thr (1.00)
Ethambutol	R	embB p.Met306Val (1.00)
Pyrazinamide	R	pncA p.Leu27Pro (1.00)
Streptomycin	R	rpsL p.Lys43Arg (1.00)
Fluoroquinolones	R	gyrA p.Asp94Ala (1.00)
Amikacin		
Capreomycin		
Kanamycin	R	eis c.-14C>T (1.00)
Cycloserine		
Ethionamide		
Clofazimine		
Para-aminosalicylic acid		
Delamanid		
Bedaquiline		
Linezolid		

Resistance variants report
-----------------
Genome Position	Locus Tag	Gene	Change	Estimated Fraction	Drug
7582	Rv0006	gyrA	p.Asp94Ala	1.000	ciprofloxacin,fluoroquinolones,levofloxacin,moxifloxacin,of
loxacin
761155	Rv0667	rpoB	p.Ser450Leu	1.000	rifampicin
781687	Rv0682	rpsL	p.Lys43Arg	1.000	streptomycin
2155168	Rv1908c	katG	p.Ser315Thr	1.000	isoniazid
2289162	Rv2043c	pncA	p.Leu27Pro	1.000	pyrazinamide
2715346	Rv2416c	eis	c.-14C>T	1.000	kanamycin
4247429	Rv3795	embB	p.Met306Val	1.000	ethambutol

Other variants report
---------------------
Genome Position	Locus Tag	Gene	Change	Estimated Fraction
7362	Rv0006	gyrA	p.Glu21Gln	1.000
7585	Rv0006	gyrA	p.Ser95Thr	1.000
8040	Rv0006	gyrA	p.Gly247Ser	1.000
9304	Rv0006	gyrA	p.Gly668Asp	1.000
761032	Rv0667	rpoB	p.Gln409Arg	1.000
764995	Rv0668	rpoC	c.1626C>G	1.000
781395	Rv0682	rpsL	c.-165T>C	1.000
1303095	Rv1173	fbiC	c.165G>A	1.000
1834836	Rv1630	rpsA	p.Met432Thr	0.996
1917972	Rv1694	tlyA	c.33A>G	0.996
2518919	Rv2245	kasA	p.Gly269Ser	1.000
2726142	Rv2428	ahpC	c.-51G>A	1.000
2746340	Rv2447c	folC	p.Ala420Val	1.000
2987502	Rv2671	ribD	p.Gly222Ser	1.000
3073868	Rv2764c	thyA	p.Thr202Ala	1.000
3086788	Rv2780	ald	c.-32T>C	1.000
3087252	Rv2780	ald	c.433 434insGC	0.951
4242643	Rv3793	embC	c.2781C>T	1.000
4326593	Rv3854c	ethA	p.Cys294Tyr	0.996
4408156	Rv3919c	gid	p.Leu16Arg	1.000

Coverage report
---------------------
Gene	Locus_Tag	Cutoff	Fraction
gyrB	Rv0005	0	0.000
gyrA	Rv0006	0	0.000
fgd1	Rv0407	0	0.000
mshA	Rv0486	0	0.000
rpoB	Rv0667	0	0.000
rpoC	Rv0668	0	0.000
mmpR5	Rv0678	0	0.000
rpsL	Rv0682	0	0.000
rplC	Rv0701	0	0.000
fbiC	Rv1173	0	0.000
embR	Rv1267c	0	0.000
atpE	Rv1305	0	0.000
rrs	rrs	0	0.000
rrl	rrl	0	0.000
fabG1	Rv1483	0	0.000
inhA	Rv1484	0	0.000
rpsA	Rv1630	0	0.000
tlyA	Rv1694	0	0.000
katG	Rv1908c	0	0.000
pncA	Rv2043c	0	0.000
kasA	Rv2245	0	0.000
eis	Rv2416c	0	0.000
ahpC	Rv2428	0	0.000
folC	Rv2447c	0	0.000
pepQ	Rv2535c	0	0.000
ribD	Rv2671	0	0.000
thyX	Rv2754c	0	0.000
thyA	Rv2764c	0	0.000
ald	Rv2780	0	0.000
fbiD	Rv2983	0	0.000
fbiA	Rv3261	0	0.000
fbiB	Rv3262	0	0.000
alr	Rv3423c	0	0.000
ddn	Rv3547	0	0.000
panD	Rv3601c	0	0.000
embC	Rv3793	0	0.000
embA	Rv3794	0	0.000
embB	Rv3795	0	0.000
ubiA	Rv3806c	0	0.000
ethA	Rv3854c	0	0.000
ethR	Rv3855	0	0.000
gid	Rv3919c	0	0.000

Missing positions report
---------------------
Gene	Locus_Tag	Position	Position_Type	Drug_Resistance_Position

Analysis pipeline specifications
--------------------------------
Pipeline version: 2.8.12
Database version: tbdb_eb6825e_Jody Phelan <jody.phelan@lshtm.ac.uk>_Tue Jul 7 12:03:47 2020 +0100
Analysis	Program
Mapping	bwa
Variant Calling	bcftools

**Comment by jodyphelan** [comment]
Hi @harrismia 

This actually denotes good coverage. The "fraction" columns represents the fraction of nucleotides that have less than the cut-off for a given gene. So this means all your genes are covered by at least 1 base at all positions.

Jody

**Comment by harrismia** [comment]
Thanks for adding this nice new feature!  That makes sense.  

You might want to add a description to the documentation.   

Best. 

Michael

**Comment by jodyphelan** [comment]
Good idea, I will add some into to the text and CSV reports.

Jody
