### ISSUE TITLE
Lineage calling from user supplied VCF files

### ISSUE THREAD

**Issue by vijay-naidu** [jodyphelan/TBProfiler#124]
Hi Jody,
Hope you're well!!
I was wondering if we can start the process of lineage calling directly by supplying our own filtered vcf files? So, skipping the mapping process and beginning the process of tb-profiling with lineage calling? And then collating the results?
Cheers,
Vijay

**Comment by jodyphelan** [comment]
Hi Vijay,

You can use the `vcf_profile` function to extract lineage information.

Jody

**Comment by vijay-naidu** [comment]
Great, thanks, Jody. Can I just do the following:
`tb-profiler vcf_profile *.vcf`
or do I have to merge all the vcf files into a single file? I have around 1100 samples, so, I have around 1100 vcf files.
Thanks,
Vijay

**Comment by jodyphelan** [comment]
At the moment it only takes in single VCF file. It will take multi-sample VCFs but if you only have single sample VCFs then you could do something like this:

```ls *.vcf.gz | parallel -j 1 --bar tb-profiler vcf_profile {}```

Just make sure they are bgzipped.

Jody

**Comment by vijay-naidu** [comment]
Terrific, thanks, Jody!!

**Comment by vijay-naidu** [comment]
Hi Jody,
When I try to run the code below, I get the following error:

`tb-profiler vcf_profile TB1.vcf
Running command:
set -u pipefail; bcftools index --threads 1 -f TB1.vcf
Command Failed! Please Check!`

I tried both v4.1 and v4.2 individually of the vcf files but I get same error as above.
Thanks,
Vijay

**Comment by vijay-naidu** [comment]
Hi Jody,
The process of lineage calling ran successfully without any error using the command that you suggested. However, I was wondering about the results. The only new files that I could see are in the format .vcf.gz.csi and three folders, namely, bam, results and vcf. The folders are all empty except for the results folder, which has a file titled "SAMPLE.results.json". I tried collating the results by running the following command:
`tb-profiler collate`
But all I get are files with nothing in it as if nothing was called.
Is there anything that I am missing, please?
Thanks,
Vijay

**Comment by jodyphelan** [comment]
Hi @vijay-naidu 

Hmm that is strange, there should be more result files. TB-Profiler names the files according to the sample in the VCF. My guess is they all have the same sample name in the VCF. Can you check a few by using the following command for a few of the vcf files?

```
bcftools query -l XXX.vcf.gz
```

If they all produce the same output then they either have to be renamed, or I can potentially build in a function to override the output file name.

Jody
