### ISSUE TITLE
skipping allelic depth filter

### ISSUE THREAD

**Issue by 0xaf1f** [jodyphelan/TBProfiler#126]
Hello -- thanks for this tool (and for your prompt response on the other issue I filed). I'm trying to run tb-profiler for lineage typing, but my VCF files don't have the `AD` attribute and it's causing problems when the tool tries to run `bcftools view -i 'sum(AD)>0' ` to filter. Could you make it so that `--reporting_af` set to 0 skips that step altogether?

**Comment by jodyphelan** [comment]
Hi @0xaf1f 

Thanks for raising this issue. I'll look into a solution and get back to you asap.

Jody

**Comment by jodyphelan** [comment]
Hi @0xaf1f ,

I've implemented the fix in the latest commit. I'll push the update on conda today.

Jody

**Comment by 0xaf1f** [comment]
Thanks! I can confirm that it fixes my problem. However, for the regular use case, if you don't pass a `reporting_af`, I thought the default is supposed to be 0.1, but it is still filtering only >0 instead of the actual value of `reporting_af`:

```
        if args.reporting_af>0:
            pp.run_cmd("bcftools view -s %(sample_name)s -c 1 %(vcf)s | bcftools view -i 'sum(AD)>0' | bcftools +fixploidy -Oz -o %(tmp_vcf)s " % vars(args))
        else:
```

**Comment by jodyphelan** [comment]
Hi @0xaf1f 

The `bcftools view -i 'sum(AD)>0'` just removes sites at which there are no alternate alleles (happens for some variant callers) as a first pass. The `--reporting_af` is actually used elsewhere in the code to (when writing text and pdf output) and filters out variants then.

Jody
