### ISSUE TITLE
Lineage/sub-lineage prediction for assembled genomes

### ISSUE THREAD

**Issue by ksw9** [jodyphelan/TBProfiler#127]
Dear Jody,

I hope you're doing well. I'm wondering if there is a way to use TBProfiler to assign sub-lineage for assembled genomes?

Thank you!

**Comment by jodyphelan** [comment]
Hi Katie,

I'm good thanks. Yes you should be able to use the `fasta_profile` function. The first argument is the fasta file and the second is a prefix for the output files. For example:
`tb-profiler fasta_profile contigs.fa sample1`

Let me know if you run into any problems with this command.

Jody

**Comment by ksw9** [comment]
Great, thank you Jody!
Best,

**Comment by jodyphelan** [comment]
No probs!
