### ISSUE TITLE
Lineage not showing in collate

### ISSUE THREAD

**Issue by conmeehan** [jodyphelan/TBProfiler#128]
Hi Jody,

I have a few samples where, if I look at the individual results.txt file I see lineage information with high estimated fractions, but when I look in the collated file there is no lineage info listed. Could this be because the depth at those SNPs is too low or something? I can email you sample reads if you wish.

Cheers,
Conor

**Comment by jodyphelan** [comment]
Hi @conmeehan 

Oh that is strange, can you email a few examples?

Jody

**Comment by conmeehan** [comment]
Actually some are on publicly available such as:

ERR751392
ERR751627
ERR775297

So should be able to see youself fvrom there. if not, I can send you the reads.

**Comment by jodyphelan** [comment]
Ah perfect, I'll take a look.

**Comment by jodyphelan** [comment]
Using v2.8.12 it seems to work for me. Are you using a specific version or changed any of the default parameters?
