### ISSUE TITLE
Rerunning when temporary files still exist

### ISSUE THREAD

**Issue by pgcudahy** [jodyphelan/TBProfiler#131]
Hello, thanks for the great tool. I've been running hundreds of samples with TBProfiler using a workflow manager (https://github.com/vatlab/SoS/). What I've noticed is that at a certain scale, a handful of `tb-profiler` runs will fail for random reasons like out-of-memory or weird disk issues. That's not a big deal, since the workflow manager can see that they've failed and just re-run them a second time where they'll usually do just fine. The only issue is that failed jobs leave behind their temporary files like `X.pair.bam.tmp.0000.bam` and the next run won't overwrite them, so they also fail. I've adjusted my scripts to always clear out the directory of temporary files before running tb-profiler, but it might be nice to have tb-profiler check for these, or allow them to be overwritten.

**Comment by jodyphelan** [comment]
Hi @pgcudahy 

Thanks for the info! Unfortunately memory issues and such will most likely cause the main python interpreter to crash, meaning it will not be able to execute any more code (e.g. checks for files) after the crash. The file checking logic will have to be run outside of TB-Profiler. Can you share an example error report to see if this is the case?

Thanks,
Jody

**Comment by jodyphelan** [comment]
Hi @pgcudahy, 

I've had a go at this and got it working. It should now clean up the files on exiting with an error. The feature is available in the new release (v3). Thanks for the idea!

Jody
