### ISSUE TITLE
Single end read analysis

### ISSUE THREAD

**Issue by peflanag** [jodyphelan/TBProfiler#132]
Hi,

I have been provided with single end reads. Can I run using just -1 and leave out the -2 in the command? I tried but it didn't work.

Cheers,

Peter

**Comment by jodyphelan** [comment]
Hey!

You should be able to... is it giving an error message?

Jody

**Comment by peflanag** [comment]
Hey Jody,

This is copied from my terminal window:


 tb-profiler profile -1 /Users/peterflanagan/IMRL_Sequencing/IMRL_2020_WGS_Data/Illumina/Run15/EQA/EQA_Extra/Fastq/11_synth_R1.fastq.gz -p 11_synth
Using gff file: /Users/peterflanagan/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.gff
Using ref file: /Users/peterflanagan/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta
Using ann file: /Users/peterflanagan/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.ann.txt
Using barcode file: /Users/peterflanagan/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed
Using bed file: /Users/peterflanagan/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed
Using json_db file: /Users/peterflanagan/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.dr.json
Using version file: /Users/peterflanagan/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.version.json

Running command:
set -u pipefail; trimmomatic SE -threads 1 -phred33 /Users/peterflanagan/IMRL_Sequencing/IMRL_2020_WGS_Data/Illumina/Run15/EQA/EQA_Extra/Fastq/11_synth_R1.fastq.gz ./11_synth_TU LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
Command Failed! Please Check!%

**Comment by jodyphelan** [comment]
Hmm it does seem to be picking up the single-ended version of trimming. Can you try run the command in the same directory and post the output?

```
trimmomatic SE -threads 1 -phred33 /Users/peterflanagan/IMRL_Sequencing/IMRL_2020_WGS_Data/Illumina/Run15/EQA/EQA_Extra/Fastq/11_synth_R1.fastq.gz ./11_synth_TU LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
```

**Comment by peflanag** [comment]
Hey, so I ran that and posted below:

trimmomatic SE -threads 1 -phred33 /Users/peterflanagan/IMRL_Sequencing/IMRL_2020_WGS_Data/Illumina/Run15/EQA/EQA_Extra/Fastq/11_synth_R1.fastq.gz ./11_synth_TU LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
TrimmomaticSE: Started with arguments:
 -threads 1 -phred33 /Users/peterflanagan/IMRL_Sequencing/IMRL_2020_WGS_Data/Illumina/Run15/EQA/EQA_Extra/Fastq/11_synth_R1.fastq.gz ./11_synth_TU LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at org.usadellab.trimmomatic.fastq.FastqParser.parseOne(FastqParser.java:65)
	at org.usadellab.trimmomatic.fastq.FastqParser.next(FastqParser.java:179)
	at org.usadellab.trimmomatic.TrimmomaticSE.processSingleThreaded(TrimmomaticSE.java:60)
	at org.usadellab.trimmomatic.TrimmomaticSE.process(TrimmomaticSE.java:226)
	at org.usadellab.trimmomatic.TrimmomaticSE.run(TrimmomaticSE.java:321)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:85)

**Comment by jodyphelan** [comment]
I ran the same command, substituting in a random fastq file I had, and it seemed to run fine. So I think it is either a problem with your fastq file or a problem with your trimmomatic.

If you think it might be your trimmomatic then you can run the following to check with a valid fastq:
```
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR166/009/ERR1664619/ERR1664619_1.fastq.gz
tb-profiler profile -1 ERR1664619_1.fastq.gz -p ERR1664619
```

If the above works then it is probably something to do with the fastq file you are trying to run through. Feel free to send it to me if you run out of options.

**Comment by peflanag** [comment]
Hey thanks Jody. I’ve a feeling it might be the single ended fastq cause other files worked for me the day before. These are samples we’ve been asked to part take in a quality test and the people providing it said they’re could be issues abs to let them know! 

I’ll try some paired end again and see. Maybe if you don’t mind I could send you one or two to see if it works for you?

**Comment by jodyphelan** [comment]
Sure you can send me a link at &#106;&#111;&#100;&#121;&#046;&#112;&#104;&#101;&#108;&#097;&#110;&#064;&#108;&#115;&#104;&#116;&#109;&#046;&#097;&#099;&#046;&#117;&#107;
