### ISSUE TITLE
Questions about coverage and missing positions report

### ISSUE THREAD

**Issue by pmenzel** [jodyphelan/TBProfiler#133]
Dear Jody,
Just to make sure that I understood the coverage and missing positions report:
I ran tb-profiler with default settings.

For example, I have this line in the coverage report with a non-zero column 4:
```
Coverage report
---------------------
...
rrl     rrl     0       0.057
...
```
I understood, that it means that 5.7% of all bases in the rrl gene have no read aligning to them, i.e. coverage is 0.

And in the missing positions report, I see all positions that have a coverage < 10 (and possibly 0) ?

thanks!

**Comment by jodyphelan** [comment]
Hi Peter,

Yes that is correct there are 5.7% of bases with 0 coverage in rrl.

The missing positions report contains info on which positions/codons are involved and if they associated with drug resistance. The default cutoff is 10 for this but can be changes with `--missing_cov_threshold`

Jody

**Comment by pmenzel** [comment]
Thanks. I just tried to set `--missing_cov_threshold` to zero, but then the missing positions report  was empty. Shouldn't it show the bases in rrl with no mapped reads in that case?

**Comment by jodyphelan** [comment]
Sorry forgot to explain that clearly. It will report every position < missing_cov_threshold. So in your case, you will need to set it to 1. Let me know if that works.

**Comment by pmenzel** [comment]
Ah thanks, of course! I set it to 1 and now I can see a list of positions in rrl.

And positions contained in tbdb would also have an entry in the Drug_Resistance_Position column?

**Comment by jodyphelan** [comment]
Yes it will have "DR" in that column. In the future, I will change that so it reports the drugs involved instead.

**Comment by pmenzel** [comment]
Alright, thanks for the insight!
