### ISSUE TITLE
Errors on running whole pipeline

### ISSUE THREAD

**Issue by hjafar** [jodyphelan/TBProfiler#136]
Dear Phelan,

I have got the following errors after I have run the example data. Note: I follow the documentation on my data and got the same as the issues. How can I solve it?

Thank you in advance
Hussain

Running command:
set -u pipefail; cat /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 4 --col-sep " " "bcftools mpileup -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -ABq8 -Q0 -a DP,AD -r {1} ./ERR1664619.bam | bcftools call -mv | bcftools norm -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -S . -Oz -o ./ERR1664619.{2}.vcf.gz"
Command Failed! Please Check!(tbprofiler)

**Comment by jodyphelan** [comment]
Hi Hussain,

Thanks for reporting the issue. Could you run the following command and post the output please?

```
cat /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1""$2""$3}' | parallel -j 4 --col-sep " " "bcftools mpileup -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -ABq8 -Q0 -a DP,AD -r {1} ./ERR1664619.bam | bcftools call -mv | bcftools norm -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -S . -Oz -o ./ERR1664619.{2}.vcf.gz"
```

Thanks,
Jody

**Comment by hjafar** [comment]
Thank you for your quick response.

I have run the above command line and got the following outputs.

(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ cat /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1""$2""$3}' | parallel -j 4 --col-sep " " "bcftools mpileup -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -ABq8 -Q0 -a DP,AD -r {1} ./ERR1664619.bam | bcftools call -mv | bcftools norm -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -S . -Oz -o ./ERR1664619.{2}.vcf.gz"
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence the citation notice: run 'parallel --citation'.

bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ 
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Thanks,
Thanks,: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Jody
Jody: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ @hjafar
@hjafar: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ New Video support! Upload MP4 and MOV file types. Attach files by dragging & dropping, selecting or pasting them.
[2] 39324

Command 'New' not found, did you mean:

  command 'new' from deb mmh (0.4-2)
  command 'new' from deb nmh (1.7.1-6)

Try: sudo apt install <deb name>

dropping,: command not found
[2]-  Exit 127                New Video support! Upload MP4 and MOV file types. Attach files by dragging
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Remember, contributions to this repository should follow our GitHub Community Guidelines.
Remember,: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Assignees
Assignees: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ No one assigned
No: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Labels
Labels: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ None yet
None: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Projects
Projects: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ None yet
None: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Milestone
Milestone: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ No milestone
No: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Linked pull requests
Linked: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ 
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Successfully merging a pull request may close this issue.
Successfully: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ None yet
None: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Notifications
Notifications: command not found
(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ Customize

Command 'Customize' not found, did you mean:

  command 'kustomize' from snap kustomize (3.8.8)

See 'snap info <snapname>' for additional versions.

(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ You’re receiving notifications because you authored

**Comment by jodyphelan** [comment]
No problem, there seems to be an issue with the bcftools installation. Can you install the latest version of bcftools using conda and then check if you can run it.

```
conda install bcftools=1.11
bcftools version
```

**Comment by hjafar** [comment]
I have done all the following. Can you please give me your suggestion/advice?


(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ conda install -c bioconda bcftools
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

I have updated to version bcftools=1.9

(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ bcftools version
bcftools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

I have run the following command line and got the same errors as before.

(tbprofiler) hussain@hussain:~/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run$ python /home/hussain/anaconda3/envs/tbprofiler/bin/tb-profiler profile -1 '/home/hussain/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run/ERR1664619_1.fastq.gz' -2 '/home/hussain/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run/ERR1664619_2.fastq.gz' -t 4 -p ERR1664619

Running command:
set -u pipefail; cat /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 4 --col-sep " " "bcftools mpileup -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -ABq8 -Q0 -a DP,AD -r {1} ./ERR1664619.bam | bcftools call -mv | bcftools norm -f /home/hussain/anaconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -S . -Oz -o ./ERR1664619.{2}.vcf.gz"

There are conflicts with version bcftools=1.11

Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.0.2l,<1.0.3a']
bcftools=1.10 -> htslib[version='>=1.10.1,<1.11.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1g,<1.1.2a']

**Comment by jodyphelan** [comment]
It looks like you might have python2.7 installed which might have some compatibility issues with bcftools/samtools. Can you try create a new environment with the following and see if that works?

`conda create -n tb-profiler tb-profiler=2.8.14`

**Comment by hjafar** [comment]
Thank you so much for your opinion and advice.

I have created a new environment (named as tb-profiler) with python version 3.6 and then installed tb-profiler=2.8.14 as shown in the following and got another issue.
1. conda create -n tb-profiler python=3.6
2. conda install -c bioconda tb-profiler=2.8.14
3. tb-profiler profile -1 '/home/hussain/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run/ERR1664619_1.fastq.gz' -2 '/home/hussain/Documents/KFHRC/NTM/S18/S18_1868_3646/changeID/test_run/ERR1664619_2.fastq.gz' -t 4 -p ERR166461

I have this issue
Running command:
set -u pipefail; delly call -t DEL -g /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta ./ERR1664619.bam -o ./ERR1664619.delly.bcf
Can't find ./ERR1664619.delly.bcf

I have checked to install package delly which is already installed in my environment.

conda install -c bioconda delly
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

delly call -t DEL -g /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta ./ERR1664619.bam -o ./ERR1664619.delly.bcf
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory

I look forward to hearing from you...

Hussain

**Comment by hjafar** [comment]
I have tried to update the delly.
$ conda update delly

Again, I have got the same issues.
Running command:
set -u pipefail; delly call -t DEL -g /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta ./ERR1664619.bam -o ./ERR1664619.delly.bcf
Can't find ./ERR1664619.delly.bcf

**Comment by hjafar** [comment]
Dear Phelan,

Kindly find below how I figure out the above issues. It was a problem with delly version installation. I remove and reinstall delly package version (v0.8.1).
1. $ conda remove -y delly
2. $ wget https://github.com/dellytools/delly/releases/download/v0.8.1/delly_v0.8.1_linux_x86_64bit
3. $ chmod 755 delly_v0.8.1_linux_x86_64bit
4. $ mv delly_v0.8.1_linux_x86_64bit `echo $PATH | tr ":" "\n" | head -1`/delly

I have got this message :)

Running command:
set -u pipefail; mv -f RR1664619/ERR1664619.delly.bcf* RR1664619/vcf/

Profiling finished successfully!

Best,
Hussain

**Comment by hjafar** [comment]
Dear Phelan,

I have run the following command line and did not produce/get the figure of phylogeny and drug resistance outputs which is output by ITOL website. 

$ tb-profiler collate 
Using gff file: /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.gff
Using ref file: /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta
Using ann file: /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.ann.txt
Using barcode file: /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.barcode.bed
Using bed file: /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.bed
Using json_db file: /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.dr.json
Using version file: /home/hussain/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.version.json

They have the list outputs files :
1. tbprofiler.dr.indiv.itol.txt
2. tbprofiler.dr.itol.txt
3. tbprofiler.json
4. tbprofiler.lineage.itol.txt
5. tbprofiler.txt
6. tbprofiler.variants.txt

Do I need to install some specific packages like R and its dependencies? Or what is your advice?

Thank you

**Comment by jodyphelan** [comment]
Hi Hussain,

Thanks for troubleshooting and finding a solution. I'll check the conda package and try to find out why it installed the wrong version of Delly. Glad you managed to figure it out. 

With your question on the tree: the config files are meant to be used on the the [itol website](https://itol.embl.de/). You will need to create a tree also, this function is not included with TB-Profiler so you will need to use other software for this.

Jody

**Comment by hjafar** [comment]
Hi Phelan,

Thank you for your understanding.

I know there are many ways to produce a file with extension **.tree** to be used on the itol website such as using iqtree and raxml packages ... etc.

Is your pipeline produce a summary combined both results of the phylogeny tree and drug resistance outputs as shown in the tutorial page. Because I have done all steps and got the results (all variants and annotation and phylogeny tree ... etc) and I am looking for tools to predict Drug resistance of my samples.

Which database and tools are using in your annotation steps and what is the difference between prokka and eggNOG annotation?

Regards,
Hussain

**Comment by jodyphelan** [comment]
Yes that is correct... it will produce a summary of the resistance in your samples. You don't necessarily need a tree for that actually. The predictions will be present in the *tbprofiler.txt* file which you can view using excel or similar software (make sure you use tab as the delimiter). The other files ending in ".itol.txt" are just in case you want to superimpose that information onto an itol tree.

The annotations are performed using bcftools csq and the reference [gff file](https://github.com/jodyphelan/tbdb/blob/master/genome.gff). This will annotate functional changes caused by SNPs and indels. These changes are then looked for in a list of drug resistance mutations which can be found [here](https://github.com/jodyphelan/tbdb/blob/master/tbdb.csv).

The pipeline doesnt use prokka or eggNOG because it doesn't perform de-novo assembly. In our case we just perform mapping to an established reference genome with annotations already existing.

Hope that help clear up some of your questions, let me know if you have any more.

Jody

**Comment by hjafar** [comment]
Dear Phelan,
I have uploaded the tbprofiler.tree and I am stuck with following to git final figure result as included in the example_data directory.
Kindly what is it "select the iTOL config files" and how can I get it?

Also, I would like to know that can tb-profile pipeline use/obtain results about DST and MIC? 
What is next after I get report drug resistance?
What is your advice to git sensitivity and specificity calculation for NTM (newly sequenced genome)?
Best,
Hussain

**Comment by jodyphelan** [comment]
Hi @hjafar,

> Kindly what is it "select the iTOL config files" and how can I get it?

You can get this by running `tb-profiler collate` inside the directory where you ran `tb-profiler profile`. This should generate a few files ending in .itol.txt which you can upload to https://itol.embl.de/

> Also, I would like to know that can tb-profile pipeline use/obtain results about DST and MIC?

TB-Profiler can currently not give you an MIC result as it just gives you a Sensitive/Resistant prediction on the different drugs. This binary result can be thought of as similar to a DST result.

>  What is your advice to git sensitivity and specificity calculation for NTM (newly sequenced genome)?

The best current way is to run [kraken2](https://ccb.jhu.edu/software/kraken2/). I am currently working on a fast method of estimating this within tb-profiler, however it is not yet ready for release.
