### ISSUE TITLE
about TlyA 751T>TTG

### ISSUE THREAD

**Issue by feihongloveworld** [jodyphelan/TBProfiler#137]
hi sir:
       a frameshift insertion (751T>TTG) in the tlyA gene associated with capreomycin resistance in tbprofiler paper,
      but the tlyA c.751_752insTG is indeterminate, so why ?
      Another question，what‘s the stardand to classificate mutation to different level （high，indeterminate）？

thanks

**Comment by jodyphelan** [comment]
Hi 

These confidence categories are based on the criteria described in https://erj.ersjournals.com/content/50/6/1701354 (see 
[inline-supplementary-material-1.pdf](https://github.com/jodyphelan/TBProfiler/files/5795641/inline-supplementary-material-1.pdf): supplementary 5 for detail). These criteria try to give a statistical confidence level according to data available. But this sometimes there is not enough data to calculate these. This is why it has been labelled "indeterminate". 

The mutations in the database have been collated based upon different sources of evidence, mainly:
* Statistical methods - e.g. GWAS
* Experimental methods - e.g. allelic exchange experiments

The mutation in question was put into the database as it was found to explain capreomycin resistance in an isolate in [this study ](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-016-0385-x) and evidence that frameshifts it tlyA confer resistance to capreomycin ([see here](https://aac.asm.org/content/49/2/571#T2)). So for this mutation the evidence was came more from the experimental methods.

Hope that answers your question.

Jody
