### ISSUE TITLE
PDF output does not end up in results folder 

### ISSUE THREAD

**Issue by pmenzel** [jodyphelan/TBProfiler#138]
Dear Jody,

I just noticed, that when using PDF output, the tex file is created in the results folder here:
https://github.com/jodyphelan/TBProfiler/blob/515ee35e136e046b9cbbdd9e2ed68b64b6c903eb/tb-profiler#L128

Then, at least on my system, the PDF file will be created in the folder where tb-profiler is run and not in the results/ folder. I am not sure if it was always like that. Is it the same for you?

Then maybe the pdf file  could be moved to the results folder, around here: https://github.com/jodyphelan/TBProfiler/blob/515ee35e136e046b9cbbdd9e2ed68b64b6c903eb/tb-profiler#L137

best,
Peter

**Comment by jodyphelan** [comment]
Hi @pmenzel 

Oh yes, looking at the code it seems that it is not moved to the right location. 
I was actually wondering about the PDF output for the next big update, whether I should keep developing support.  Is the preferred output format for your use?

Jody

**Comment by pmenzel** [comment]
I set tb-profiler to produce all formats. While I usually just look at the txt output, PDF might still be handy when sending the report to Windows users, medical doctors for example :)

**Comment by jodyphelan** [comment]
Oh yeah I will fix improve that in the next version I upload. I was actually thinking to redevelop the PDF report a bit as it is tricky to install the latex distribution on conda. Together with that I will try update the format a bit too.

**Comment by jodyphelan** [comment]
The directory should be properly set now in the new release (v3), thanks for letting me know about the issue.
