### ISSUE TITLE
results folder empty

### ISSUE THREAD

**Issue by paolaflorez** [jodyphelan/TBProfiler#14]
Hi Jody,

We have managed to partially run the TBprofiler.  Philip on my team, can successfully generate *.bam and *.depth files but the vcf/results folder seem to be empty (not even a header).  Have you every run into this before?  Any suggestions on how to populate these files?

Best,
Paola and Philip

**Comment by jodyphelan** [comment]
Hi Paola and Philip,

Are there any error mesages?
You can tun with -v2 to increase the verbosity.

Jody
