### ISSUE TITLE
Can't find XXXX.delly.bcf

### ISSUE THREAD

**Issue by ChiehYin** [jodyphelan/TBProfiler#140]
Hi, 

I ran the code fine, but It showed "Can't find XXXX.delly.bcf" between the lines. Is this okay? 

#######
Running command:
set -u pipefail; bwa mem -t 1 -c 100 -R '@RG\tID:K190823_S1119\tSM:K190823_S1119\tPL:illumina' -M -T 50 /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta ./K190823_S1119_1P ./K190823_S1119_2P | samtools sort -@ 1 -o ./K190823_S1119.pair.bam -
Running command:
set -u pipefail; bedtools coverage -a /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.barcode.bed -b ./K190770_S1161.bam -d -sorted

Running command:
set -u pipefail; delly call -t DEL -g /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta ./K190770_S1161.bam -o ./K190770_S1161.delly.bcf
**Can't find ./K190770_S1161.delly.bcf**
Using gff file: /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.gff
Using ref file: /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta
Using ann file: /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.ann.txt
Using barcode file: /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.barcode.bed
Using bed file: /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.bed
Using json_db file: /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.dr.json
Using version file: /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.version.json

Running command:
set -u pipefail; trimmomatic PE -threads 1 -phred33 K190817_S1164_R1.fastq.gz K190817_S1164_R2.fastq.gz -baseout ./K190817_S1164 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
####################

Thank you.

**Comment by jodyphelan** [comment]
Hi @ChiehYin 

I think this might be an issue with running delly. Can you run the following code and paste the output here?

```
delly call -t DEL -g /home/opt/appl/anaconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta ./K190770_S1161.bam -o ./K190770_S1161.delly.bcf
```

**Comment by ChiehYin** [comment]
Hi Jody, 

Thank you. Here is the output after running delly.

_delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory_


And I ran the code you mentioned in other issue. 
`conda update delly`  
The package tqdm-4.56.0 was then downloaded .
But I reran the delly code it showed the above error again.

Also, I ran 
 'conda install delly=0.8.7 '  

_PackagesNotFoundError: The following packages are not available from current channels:
  - delly=0.8.7_


If I specified the channel bioconda (which not sure if it's correct), it turned out to some package conflicts.

_Package openssl conflicts for:
delly=0.8.7 -> htslib[version='>=1.10.2,<1.11.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1g,<1.1.2a']
python=3.6 -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.0.2l,<1.0.3a']_

Thank you!

**Comment by jodyphelan** [comment]
Thanks for the feedback. It seems delly is the problem and you were right to try install it again. Are you running Linux? you could try replicate a working environment I have.
I also have attached an explicit list which you can use to build and identical environment to mine: [spec-file.txt](https://github.com/jodyphelan/TBProfiler/files/5952762/spec-file.txt). You should be able to create and env with `conda create --name myenv --file spec-file.txt`

**Comment by ChiehYin** [comment]
Yes I am using Linux. It worked after I replicated your working environment. 

Thank you!

**Comment by jodyphelan** [comment]
Perfect!
