### ISSUE TITLE
About insert position

### ISSUE THREAD

**Issue by wangzhichao1990** [jodyphelan/TBProfiler#142]
Hi, 
There is a tb-profiler result.

| Genome Position | Locus Tag | Gene | Change         | Estimated Fraction | Drug                                                         |
| --------------- | --------- | ---- | -------------- | ------------------ | ------------------------------------------------------------ |
| 7582            | Rv0006    | gyrA | p.Asp94Ala     | 1                  | ciprofloxacin,fluoroquinolones,levofloxacin,moxifloxacin,ofloxacin,fluoroquinolones,levofloxacin,moxifloxacin,ofloxacin |
| 761140          | Rv0667    | rpoB | p.His445Arg    | 1                  | rifampicin                                                   |
| 2155167         | Rv1908c   | katG | p.Ser315Arg    | 1                  | isoniazid                                                    |
| 2288853         | Rv2043c   | pncA | c.391 392insGG | 0.964              | pyrazinamide                                                 |
| 4247429         | Rv3795    | embB | p.Met306Val    | 1                  | ethambutol                                                   |
| 4326703         | Rv3854c   | ethA | c.770 771insC  | 1                  | ethionamide                                                  |

However, I can't find  pncA  c.391 392insGG and  ethA c.770 771insC in the database.
I just find pncA  c.392_393insGG and  ethA c.771_ 772insC .
The version of tb-profiler is 3.0.0.
Did I do something wrong? Thanks.

**Comment by wangzhichao1990** [comment]
I think that the code should be change a little in here  (https://github.com/jodyphelan/tbdb/blob/b2af4440038499b9fdf98a5cc24574dade66e3d7/parse_db.py#L110) .  Is it right?

**Comment by jodyphelan** [comment]
Hi @wangzhichao1990 ,

Thanks for posting this issue. Some frameshifts will not be explicitly specified in the database but they are used in the prediction if the "frameshift" keyword is present in the database (e.g.https://github.com/jodyphelan/tbdb/blob/master/tbdb.csv#L1073).  This is why you may see them in the result files but not in the database.

Regarding whether the coordinates are correct, I had a look at some of my samples with the same mutation (pncA c.391_392insGG) and I am getting a different value for "genome position". Would it be possible for you to post the json result file for this sample so I can check?

**Comment by wangzhichao1990** [comment]
Hi @jodyphelan ,
Thanks for your reply. Here is the json file for my sample.
[results.zip](https://github.com/jodyphelan/TBProfiler/files/6076506/results.zip)

**Comment by wangzhichao1990** [comment]
Here is the lines(66-81) of https://github.com/jodyphelan/TBProfiler/blob/master/pathogenprofiler/utils.py

```{python}
        # Insertion
        # 1918692G>GTT
        re_obj = re.search("([0-9]+)([A-Z])>([A-Z][A-Z]+)",x)
        if re_obj:
            chr_pos = int(re_obj.group(1))
            ref = re_obj.group(2)
            alt = re_obj.group(3)
            strand = "-" if gene[-1]=="c" else "+"
            if strand == "+":
                gene_start = gene_info[chr_pos]
                gene_end = gene_start + 1
                return "c.%s_%sins%s" % (gene_start,gene_end,alt[1:])
            else:
                gene_start = gene_info[chr_pos] - 1
                gene_end = gene_info[chr_pos]
                return "c.%s_%sins%s" % (gene_start,gene_end,revcom(alt[1:]))
```

For this mutation site(1918692G>GTT) , the chrom position of "G" is 1918692。
However, in here((https://github.com/jodyphelan/tbdb/blob/b2af4440038499b9fdf98a5cc24574dade66e3d7/parse_db.py#L110) ), the 1918692 chrom posintion  means "T".
Do they conflict with each other? Thanks.

**Comment by jodyphelan** [comment]
Thanks for sharing your result file. I see it has the c.770_771insC frameshift in ethA. I found another isolate with the same mutation to demonstrate with. Here is a visualisation of the reads and reference:

![image](https://user-images.githubusercontent.com/8697224/109898849-ca865900-7c8c-11eb-9ba9-521aa1bef016.png)

The variant caller sees this mutation and calls it as 4326703 T>TG. VCF format always stores variant in the context of the positive strand, however this gene is in the reverse direction. So when representing the mutation in the context of coding sequence we must also "reverse complement" the variant. This mutation in the context of the reverse strand starts at 4326703 (which is gene position: 770) and the inserted base would be a C instead of a G. So the variant is c.770_771insC.

**Comment by wangzhichao1990** [comment]
Yes,  you are right.
But, in the tbdb.dr.json file, the "4326703T>TG" is c.771_772insC.  I think it is an error.
```
"4326703T>TG": {"annotations": [{"type": "drug", "drug": "ethionamide", "confidence": "indeterminate"}], "hgvs_mutation": "c.771_772insC"}
```
Forgive me for my broken English.

**Comment by jodyphelan** [comment]
Ah yes, sorry I was looking at something different. Yes you are right indeed, the mutation is wrong in the tbdb.dr.json file. Thanks for getting this to my attention. I'll fix that and release a patch asap.

Jody

**Comment by jodyphelan** [comment]
Hi @wangzhichao1990 

I've written a fix (https://github.com/jodyphelan/TBProfiler/commit/9ebce0e84b18ce4433bb1d8ef303b5988fd28006). 
The variant c.770_771insC will now be represented in the json datbase as
```
"4326703T>TG": {
      "annotations": [
        {
          "type": "drug",
          "drug": "ethionamide",
          "confidence": "indeterminate"
        }
      ],
      "hgvs_mutation": "c.770_771insC"
    }
}
```

Let me know if you find any other issues!

Jody
