### ISSUE TITLE
errors removing files when using -d directive

### ISSUE THREAD

**Issue by jeffreybm** [jodyphelan/TBProfiler#143]
Hi Jody,

Running tb-profiler version 3.0 using a -d directive is causing the pipeline to fail.  A file is being attempted to be removed but is not found.  Pipeline runs fine when not using -d directive, however a couple temp files do remain. The call "rm 3e6999f0-249d-4a82-adf7-61fce602800f.* "   does remove most of these files except for those that have an underscore at end of temp file name eg. 3e6999f0-249d-4a82-adf7-61fce602800f_1P

command line call leading to failure:
tb-profiler profile -1 ERR1664619_1.fastq.gz -2 ERR1664619_2.fastq.gz -t 4 -p ERR1664619 -d ./profiler_results

error message:
Running command:
set -u pipefail; rm bfdc2b9a-9402-4d62-a553-63cddac2a4fd.*
Traceback (most recent call last):
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-3.0.0-python3/bin/tb-profiler", line 569, in <module>
    args.func(args)
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-3.0.0-python3/bin/tb-profiler", line 209, in main_profile
    pp.run_cmd("rm %(tmp_prefix)s.*" % vars(args))
  File "/sysapps/cluster/software/Anaconda3/5.3.0/envs/tbprofiler-3.0.0-python3/lib/python3.6/site-packages/pathogenprofiler/utils.py", line 325, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; rm bfdc2b9a-9402-4d62-a553-63cddac2a4fd.*
stderr:
rm: cannot remove ‘bfdc2b9a-9402-4d62-a553-63cddac2a4fd.*’: No such file or directory

Cleaning up after failed run

################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the
contents of the error log (ERR1664619.errlog)

###############################################################################

Cheers!

Brendan

**Comment by jodyphelan** [comment]
Hi Brendan,

Thanks for letting me know about this issue. I'll have a look.

Jody

**Comment by jodyphelan** [comment]
It should be fixed now, are you using conda or a manual install?

**Comment by jeffreybm** [comment]
our sys admin has been using conda install -c bioconda tb-profiler

latest version we're on is 3.0
(base) [jeffreybm@ai-hpcn047 .../scratch/jeffreybm] $ tb-profiler version

TBProfiler version 3.0.0

**Comment by jodyphelan** [comment]
Ok I'm in the process of updating the conda package. Will let you know when it is ready.

Jody

**Comment by jodyphelan** [comment]
New version is available on conda (v3.0.2). Let me know if it fixes your errors.
