### ISSUE TITLE
Files not working via command line

### ISSUE THREAD

**Issue by bajwamoneeb** [jodyphelan/TBProfiler#145]
# tb-profiler error report

* OS: linux
* Program version: 3.0.3
* Database version: a2a234b
* Program call:
```
{'read1': '18RF7106-MI-TBWGS-NextSeq-2018-60_S89 (paired)_R1.fastq.gz', 'read2': '18RF7106-MI-TBWGS-NextSeq-2018-60_S89 (paired)_R2.fastq.gz', 'bam': None, 'platform': 'illumina', 'db': 'tbdb', 'external_db': None, 'prefix': 'tbprofiler', 'dir': '.', 'csv': False, 'txt': False, 'pdf': False, 'add_columns': None, 'add_mutation_metadata': False, 'mapper': 'bwa', 'caller': 'bcftools', 'calling_params': None, 'min_depth': 10, 'af': 0.1, 'reporting_af': 0.1, 'coverage_fraction_threshold': 0, 'missing_cov_threshold': None, 'no_trim': False, 'no_flagstat': False, 'no_delly': False, 'threads': 1, 'verbose': 0, 'no_cleanup': False, 'delly_bcf': None, 'func': <function main_profile at 0x7f0220365598>, 'tmp_prefix': '78744061-d0ca-4227-88e6-f8bd3721ea97'}
```
## Traceback:
```
  File "/home/mbajwa/.conda/envs/TBprofiler/bin/tb-profiler", line 569, in <module>
    args.func(args)
  File "/home/mbajwa/.conda/envs/TBprofiler/bin/tb-profiler", line 141, in main_profile
    fastq_obj = untrimmed_fastq_obj.trim(files_prefix,threads=args.threads)
  File "/home/mbajwa/.conda/envs/TBprofiler/lib/python3.6/site-packages/pathogenprofiler/fastq.py", line 33, in trim
    run_cmd("trimmomatic PE -threads %(threads)s -phred33 %(r1)s %(r2)s -baseout %(prefix)s LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36" % vars(self))
  File "/home/mbajwa/.conda/envs/TBprofiler/lib/python3.6/site-packages/pathogenprofiler/utils.py", line 325, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
```
## Value:
```
Command Failed:
set -u pipefail; trimmomatic PE -threads 1 -phred33 18RF7106-MI-TBWGS-NextSeq-2018-60_S89 (paired)_R1.fastq.gz 18RF7106-MI-TBWGS-NextSeq-2018-60_S89 (paired)_R2.fastq.gz -baseout ./78744061-d0ca-4227-88e6-f8bd3721ea97 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
stderr:
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `set -u pipefail; trimmomatic PE -threads 1 -phred33 18RF7106-MI-TBWGS-NextSeq-2018-60_S89 (paired)_R1.fastq.gz 18RF7106-MI-TBWGS-NextSeq-2018-60_S89 (paired)_R2.fastq.gz -baseout ./78744061-d0ca-4227-88e6-f8bd3721ea97 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36'
```

**Comment by bajwamoneeb** [comment]
Please assist

**Comment by jodyphelan** [comment]
Hi @bajwamoneeb,

It looks like you have spaces and backet symbols in the read file names. This can cause problems with running the pipeline. If this is the case, I would recommend changing these symbols. For example you could change the file names to:
 `18RF7106-MI-TBWGS-NextSeq-2018-60_S89_paired_R1.fastq.gz`
and
 `18RF7106-MI-TBWGS-NextSeq-2018-60_S89_paired_R2.fastq.gz`

Let me know if this fixes the issue

**Comment by bajwamoneeb** [comment]
Hi Jody,

Thanks for the reply! Also if I had Nextseq paired TB samples that were from multiple lanes, what would be the best way to go about analyzing them via your program?

________________________________

**Comment by jodyphelan** [comment]
No problem!

If you have have multiple pairs from different lanes the easiest thing to do is to combine all the forward together and all the reverse together. For example if you have the files:
```
sample1_S1_L001_R1_001.fastq.gz
sample1_S1_L001_R2_001.fastq.gz
sample1_S1_L002_R1_001.fastq.gz
sample1_S1_L002_R2_001.fastq.gz
```
You can do the following:
```
cat sample1_S1_L001_R1_001.fastq.gz sample1_S1_L001_R1_001.fastq.gz > sample1_all_lanes_R1.fastq.gz
cat sample1_S1_L001_R2_001.fastq.gz sample1_S1_L001_R2_001.fastq.gz > sample1_all_lanes_R2.fastq.gz
```
Then you can use the combined files for analysis:
```
tb-profiler -1 sample1_all_lanes_R1.fastq.gz -2 sample1_all_lanes_R2.fastq.gz -p sample1 
```

**Comment by bajwamoneeb** [comment]
Hi Jody,

Thanks! Also, I am not sure how to collate for specific samples. I tried using the following syntax:

tb-profiler collate --samples 18RF7106

My fastq file was named as such: 18RF7106-MI-TBWGS-NextSeq-2018-60_S89_paired_R1.fastq.gz.

My results file was named 18RF7106.results.json. But it doesn't work when I try the above collating syntax as it says it can't find such a file.

Please assist.
________________________________

**Comment by jodyphelan** [comment]
Hi @bajwamoneeb ,

The `--samples` argument expects a file with each line being a sample name. Alternatively you can run `tb-profiler collate` without the `--samples` argument and it will automatically detect the result files.

**Comment by bajwamoneeb** [comment]
So what was wrong with my syntax?
________________________________

**Comment by jodyphelan** [comment]
You are using the sample ID directly, however you should have a file with the IDs in it. E.g.

If you have a file named `ids.txt` wit the contents:
```
18RF7106
```
Then you can use `tb-profiler collate --samples ids.txt`

**Comment by jodyphelan** [comment]
It means that the drug resistance doesn't fall into any of the other categories (e.g. Sus/MDR/XDR).
For example, an isolate with only pyrazinamide resistance would be classified as "other".

**Comment by bajwamoneeb** [comment]
Why aren't such samples that have resistance to one drug classified simply as DR? Also what are all the classification categories in TB-Profiler?
________________________________

**Comment by bajwamoneeb** [comment]
Also what would be the difference between "other" and "pre-MDR" in terms of strength of drug resistance?
________________________________

**Comment by jodyphelan** [comment]
> Why aren't such samples that have resistance to one drug classified simply as DR? Also what are all the classification categories in TB-Profiler?

Classifying drug resistant (DR) could potentially lead to confusion as in MDR or XDR could be seen as drug resistant strains. The different classifications are the following :
| Type | Drugs resistance |
|-|-|
|Sensitive | No drug resistance|
|Pre-MDR | Rifampicin or isonisazid |
|MDR | Rifampicin and isoniazid| 
|Pre-XDR | MDR and (any fluoriquinolone or any second-line injectables)|
|XDR | MDR and (any fluoriquinolone and any second-line injectables) |
|Other | Resistance to any drug but none of the above categories|

> Also what would be the difference between "other" and "pre-MDR" in terms of strength of drug resistance?

No inference on the strength of drug resistance can be drawn from these categories. I guess this will depend a bit on the definition of strength. 

In any case, these categories are constructed from the individual drug predictions which also are present in the file. If a different categorisation is required it can be constructed from these. I have created a little tutorial on how to do so if you are interested: https://jodyphelan.gitbook.io/tb-profiler/development/writing-a-custom-collate-script

**Comment by jodyphelan** [comment]
A potential improvement would be to add an extra category "mono-resistant" which the WHO defines as resistance to any of the first line drugs. I'll look into adding this classification in with the next release.

**Comment by bajwamoneeb** [comment]
That sounds good. Also a quality score would be very important as well; similar to how Nextclade gives a quality score for COVID when classifying clades.
________________________________

**Comment by jodyphelan** [comment]
Added _RR-TB_ and _HR-TB_ as mono-resistant categories in latest release. As for a quality score, do you mean on the resistance or sublineage prediction?

**Comment by bajwamoneeb** [comment]
Ideally QC scores on DR classification; any other QC metrics would be a bonus, such as percent reference coverage.
________________________________

**Comment by jodyphelan** [comment]
Ok sounds good. I'm planning to include confidence on the individual mutation/drug associations based on the values reported in the [new WHO list](https://www.who.int/publications-detail-redirect/9789240028173) (after they sort out some formatting issues). As the current prediction models is simply presence/absence of mutation, this confidence value could serve as a QC score on the DR classification. 

There are a few other QC measures currently already reported such as number of reads, % reads mapping and average coverage across the genome (at the moment this is just in the json report file. See this snippet:

```
{
  "qc" : {
    "pct_reads_mapped": 0.13, 
    "num_reads_mapped": 1322420, 
    "median_coverage": 64
  }
}
```
 For each gene there is also a coverage report which tells you the fraction of low-coverage positions (with a user-defined threshold, default=0). See this snipped from the text report:

```
Coverage report
---------------------
Gene    Locus_Tag       Cutoff  Fraction
gyrB    Rv0005  0       0.000
gyrA    Rv0006  0       0.000
fgd1    Rv0407  0       0.000
```
