### ISSUE TITLE
TypeError: profiler() got an unexpected keyword argument 'af'

### ISSUE THREAD

**Issue by Nagasundaram620** [jodyphelan/TBProfiler#147]
Hi 
    Thanks for the wonderful tool to profile the TB mutations and Drug resistance. 

     I have successfully installed both the anaconda and TB profiler on Ubuntu 20.10. Further fetched the example data successfully but while executing  the command - tb-profiler profile -1 ERR1664619_1.fastq.gz -2 ERR1664619_2.fastq.gz -t 4 -p ERR1664619 it showing the following error.

Traceback (most recent call last):
  File "/home/nagasundaram/anaconda3/bin/tb-profiler", line 333, in <module>
    args.func(args)
  File "/home/nagasundaram/anaconda3/bin/tb-profiler", line 82, in main_profile
    results = pp.profiler(conf_file=conf_file,prefix=args.dir+"/"+args.prefix,r1=args.read1,r2=args.read2,bam_file=args.bam,call_method=args.call_method,min_depth=args.min_depth,threads=args.threads,platform=args.platform,mapper=args.mapper,run_delly=True,af=args.af)
TypeError: profiler() got an unexpected keyword argument 'af'

 Kindly help me to solve this!

**Comment by jodyphelan** [comment]
Hi @Nagasundaram620,

I think this could be a problem with an old version of tb-profiler. Can you run `tb-profiler version`, and paste the output here?

**Comment by Nagasundaram620** [comment]
Dear Jody Phelan 

                          Thanks for the reply. i have used the command line  conda install -c bioconda tb-profiler  to install in Ubuntu. Kindly provide with the command line to install the newer version of tb-profiler. This will really helpful for me to install the newer version quickly. 

 


Thanks & Regards Dr. N. Nagasundaram Research Associate [ICMR]Vellore Institute of Technology (VIT)Vellore, TamilnaduIndia 
 

    On Friday, 9 April, 2021, 9:33:01 pm IST, Jody Phelan ***@***.***> wrote:  
 
 


Hi @Nagasundaram620,

I think this could be a problem with an old version of tb-profiler. Can you run tb-profiler version, and paste the output here?

**Comment by jodyphelan** [comment]
You shold be able to install the newest version with:
```
conda install -c bioconda tb-profiler=3.0.3
```

If this fails due to compatibility with other packages in your base environment you can try:
```
conda create -n tb-profiler -c bioconda tb-profiler=3.0.3
```

This creates a new environment for tb-profiler which you will have to activate first using:
```
conda acrivate tb-profiler
```

**Comment by Nagasundaram620** [comment]
Dear Jody Phelan
            I tried both the comments, but its not working, I have attached the screen shot of the terminal  for your kind perusal.  Kindly help me to rectify the error.  

Thanks & Regards Dr. N. Nagasundaram Research Associate [ICMR]Vellore Institute of Technology (VIT)Vellore, TamilnaduIndia 
 

    On Monday, 12 April, 2021, 4:05:22 pm IST, Jody Phelan ***@***.***> wrote:  
 
 


You shold be able to install the newest version with:
conda install -c bioconda tb-profiler=3.0.3

If this fails due to compatibility with other packages in your base environment you can try:
conda create -n tb-profiler -c bioconda tb-profiler=3.0.3

This creates a new environment for tb-profiler which you will have to activate first using:
conda acrivate tb-profiler

**Comment by jodyphelan** [comment]
I cant see any attachment, can you try again (maybe directly though github rather than email)

**Comment by Nagasundaram620** [comment]
![tb-profiler Error](https://user-images.githubusercontent.com/80810234/114423696-0d651600-9bd5-11eb-803a-816364e9ec80.png)

**Comment by jodyphelan** [comment]
Ah I think it is having trouble finding some of the dependancy packagees. Please add the following all required channels suing the following commands before installing.

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

**Comment by Nagasundaram620** [comment]
![Sample Json results](https://user-images.githubusercontent.com/80810234/114814227-61d4e500-9dd1-11eb-8b5b-0ec437d5a419.png)
Dear Jodyphelan
                         Thanks for your support! Now i able to get the results by installing all the channels properly. Herewith i have attached the .json format results. But it is not in readable format. How can i get the result in text format or how can i read this file!

**Comment by jodyphelan** [comment]
Great!

You can use the `reformat` function to convert into txt or csv format:
```
tb-profiler reformat results/tbprofiler.results.json --txt --csv 
```

In the you can also include `--txt`, `--csv` and `--pdf` while running `tb-profiler profile` to create these files straight away.

**Comment by Nagasundaram620** [comment]
Hi 
      Thanks for the command line, now I can get the results in both .txt and .pdf format.

**Comment by jodyphelan** [comment]
Great! Let me know if you run into any more issues.
