### ISSUE TITLE
collate for SNPs ?

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#15]
Thanks for making this great tool available!  

Would it be possible to add a collate option for SNPs similar to what you have for drugs? I would like a report indicating which samples have specific mutations.  The rows would be samples and the columns would be SNP names.    Column headers could  be gene names concatenated with SNP name.  For example:  gyrA_Asp94Gly   the value in the cells could be the freq value.  For example  0.91 .     Thanks!

**Comment by jodyphelan** [comment]
Hi Michael,

That is a great idea. I will add this feature and let you know when it is ready.

Jody

**Comment by harrismia** [comment]
Great! Glad you think it is a good idea. Looking forward to using it.   

  Michael

**Comment by jodyphelan** [comment]
Hi Michael,

A file named <prefix>.variants.txt will now be created according to your recommended specifications. By default this will only use variants present in the dataset. If you would like a table with all SNPs in the database then you can use the `--all_variants` flag. This could be usefull for combining variant files from different sources

**Comment by harrismia** [comment]
Hi Jody, 

      Fantastic!  I will give it a try and  let you know  how it goes.    Best wishes, 

      Michael
