### ISSUE TITLE
Conda release for version 3.0.4

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#150]
Hi Jody, 

    Would it be possible to make a conda release for version 3.0.4 ?    

   Best, 

    Michael

**Comment by jodyphelan** [comment]
Sure! This is now availabe: 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/8697224/116708177-597ecb80-a9c7-11eb-98ee-e0a7a883a4b2.png">
