### ISSUE TITLE
Tree file generate after tb-profiler collate command

### ISSUE THREAD

**Issue by AfzalBioinfo** [jodyphelan/TBProfiler#151]
How to create .tree file 
after below command
tb-profiler collate

when we run its give us only 

tbprofiler.dr.indiv.itol.txt
tbprofiler.dr.itol.txt
tbprofiler.json
tbprofiler.lineage.itol.txt
tbprofiler.txt
tbprofiler.variants.txt

after that how can we generate .tree file for phylogeny view in iTOL online ( https://itol.embl.de/ )

**Comment by jodyphelan** [comment]
Hi @AfzalBioinfo 

At the moment TB-Profiler does not provide any functionality to actually create the tree. The config files are generated, however the tree must be created with other software. It is planned for future releases, however it might take some time to be fully developed. I would suggest alternative software for the phylogenetic reconstruciton step (such as [snippy](https://github.com/tseemann/snippy) + [iqtree](http://www.iqtree.org/))
