### ISSUE TITLE
bcftools error running tb_profiler

### ISSUE THREAD

**Issue by BettyAC** [jodyphelan/TBProfiler#161]
Running command:
set -u pipefail; cat ./tbprofiler_1U ./tbprofiler_2U > ./tbprofiler_TU

Running command:
set -u pipefail; rm ./tbprofiler_1U ./tbprofiler_2U

Running command:
set -u pipefail; bwa mem -t 16 -c 100 -R '@RG\tID:tbprofiler\tSM:tbprofiler\tPL:illumina' -M -T 50 /m/anaconda3b/envs/py3/share/tbprofiler/tbdb.fasta ./tbprofiler_1P ./tbprofiler_2P | samtools sort -@ 16 -o ./tbprofiler.pair.bam -

Running command:
set -u pipefail; bwa mem -t 16 -c 100 -R '@RG\tID:tbprofiler\tSM:tbprofiler\tPL:illumina' -M -T 50 /m/anaconda3b/envs/py3/share/tbprofiler/tbdb.fasta ./tbprofiler_TU | samtools sort -@ 16 -o ./tbprofiler.single.bam -

Running command:
set -u pipefail; samtools merge -@ 16 -f ./tbprofiler.unsort.bam ./tbprofiler.pair.bam ./tbprofiler.single.bam

Running command:
set -u pipefail; samtools sort -@ 16 -o ./tbprofiler.bam ./tbprofiler.unsort.bam

Running command:
set -u pipefail; rm ./tbprofiler.single.bam ./tbprofiler.pair.bam ./tbprofiler.unsort.bam

Running command:
set -u pipefail; samtools index -@ 16 ./tbprofiler.bam

Using ./tbprofiler.bam

Please ensure that this BAM was made using the same reference as in the database.
If you are not sure what reference was used it is best to remap the reads.

Running command:
set -u pipefail; cat /m/anaconda3b/envs/py3/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 16 --col-sep " " "freebayes -f /m/anaconda3b/envs/py3/share/tbprofiler/tbdb.fasta -r {1} ./tbprofiler.bam --haplotype-length 1  | bcftools view -c 1 | bcftools norm -f /m/anaconda3b/envs/py3/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -S . -Oz -o ./tbprofiler.{2}.vcf.gz"
Command Failed! Please Check!

**Comment by jodyphelan** [comment]
Hi @BettyAC 

Would it be possible to post the output of ther error log file? This will contain some more information which might help. If this is the latest version it should be called `tbprofiler.errlog`

**Comment by BettyAC** [comment]
Hi, here it is.
# tb-profiler error report

* OS: linux
* Program version: 3.0.4
* Database version: a2a234b
* Program call:
```
{'read1': None, 'read2': None, 'bam': 'aln15mtb-sorted.bam', 'platform': 'illumina', 'db': 'tbdb', 'external_db': None, 'prefix': 'tbprofiler', 'dir': '.', 'csv': False, 'txt': False, 'pdf$
```
## Traceback:
```
  File "/m/anaconda3b/bin/tb-profiler", line 571, in <module>
    args.func(args)
  File "/m/anaconda3b/bin/tb-profiler", line 170, in main_profile
    min_depth=args.min_depth,delly_bcf_file=args.delly_bcf,call_wg=args.call_whole_genome
  File "/m/anaconda3b/lib/python3.7/site-packages/pathogenprofiler/profiler.py", line 28, in bam_profiler
    vcf_obj = bam_obj.call_variants(conf["ref"], caller=caller, bed_file=conf["bed"], threads=threads, calling_params=calling_params, samclip = samclip, min_dp=min_depth)
  File "/m/anaconda3b/lib/python3.7/site-packages/pathogenprofiler/bam.py", line 58, in call_variants
    run_cmd("bcftools concat -aD `%(windows_cmd)s | awk '{print \"%(prefix)s.\"$2\".vcf.gz\"}'` | bcftools view -c1 -a -Oz -o %(vcf_file)s" % vars(self))
  File "/m/anaconda3b/lib/python3.7/site-packages/pathogenprofiler/utils.py", line 242, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
```
## Value:
```
Command Failed:
set -u pipefail; bcftools concat -aD `cat /m/anaconda3b/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | awk '{print "./4620e1a0-e727-48cf-8740-6921ace869f6."$2".vcf$
stderr:
Checking the headers and starting positions of 42 files
Different sample names in ./4620e1a0-e727-48cf-8740-6921ace869f6.Chromosome_7268_9818.vcf.gz. Perhaps "bcftools merge" is what you are looking for?
Failed to read from standard input: unknown file type

**Comment by BettyAC** [comment]
Thank you. I did the run with raw fastq files. I ll try with the second option you mentioned.

**Comment by jodyphelan** [comment]
ok, it might be a different error if you have run it on the fastq files. but let me know how it goes with the second option
