### ISSUE TITLE
how to interpret missing positions report

### ISSUE THREAD

**Issue by xiaoli-dong** [jodyphelan/TBProfiler#164]
Where I can find the document on how to interpret "Missing position report". different between gene and codon in the report, and what does the negative position mean?

Missing positions report
---------------------
Gene,Locus_Tag,Position,Position_Type,Drug_Resistance_Position
"gyrB","Rv0005","-242","gene",""
"gyrB","Rv0005","-241","gene",""
.
.
"gyrB","Rv0005","1","codon",""
"gyrB","Rv0005","2","codon",""
"gyrB","Rv0005","3","codon",""
"gyrB","Rv0005","4","codon",""

**Comment by jodyphelan** [comment]
Hi @xiaoli-dong

This section reports regions which do not have sufficient coverage.
If a coding part of a gene is low it will show the codon positions (covering three nucleotide positions) which are low.
If a promoter region or rRNA gene is low it will show the gene (nucleotide) positions which are low. If the position is negative it means it it in a promoter position.

Let me know if you need further clarification.

**Comment by xiaoli-dong** [comment]
thanks

**Comment by alantsangmb** [comment]
Hi, for the missing position part, am I right that the tool would report the regions that lack sufficient coverage for the mutations listed in the tbdb mutation list, including those with uncertain and "not associated w R" confidence?

Thank you.
