### ISSUE TITLE
how lineage was predicted in TBProfiler

### ISSUE THREAD

**Issue by xiaoli-dong** [jodyphelan/TBProfiler#165]
Hi, Can you explain a little on how lineage in the TBProfiler were predicted? I was looking for the information and could not find it. Also, in the example file, there is png visualization of the tree and drug resistant information. It looks great. I tried to build the tree with the example data using filtered SNPs over the whole genome. The topology of the tree I generated is quite different from yours. I am wondering how your tree was generated? You were using the SNPs in the marker genes (*.targets.csq.vcf.gz) or the SNPs over the whole genome?

Thanks,

**Comment by jodyphelan** [comment]
Hi @xiaoli-dong,

1. lineage is predicted by looking for lineage-specific SNPs that have been previously defined (see [here](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-020-00817-3) for publication and [here](https://github.com/jodyphelan/tbdb/blob/master/barcode.bed) for the SNPs dataset). 

2. This example tree has been created using SNPs generated across the whole genome with and iqtree for the tree building. If you have used the SNPs from the _.targets.csv.vcf.gz_ files, this might provide enough resolution. I would recommend processing your data using a pipeline like [snippy](https://github.com/tseemann/snippy) followed by phylogenetic reconstruction with iqtree.
