### ISSUE TITLE
Other variants from watchlist

### ISSUE THREAD

**Issue by LennertVerboven** [jodyphelan/TBProfiler#166]
When specifying genes and drugs in the watchlist when creating your own mutation database, the drugs associated with the gene in which a mutation was found that does not appear in the database itself are not listed in the other variants section of the json. This makes it quite difficult to identify to for which drugs a mutation might be relevant.

**Comment by jodyphelan** [comment]
It is possible to use the bed file to look up the gene/drug combinations but this might not be ideal for all situations. 
A possible solution would be to have a "gene-associated-drug" field for each variant, would this make it easier?

**Comment by LennertVerboven** [comment]
Hi Jody


Thank you for your reply, I agree that you can indeed look up what drug this gene is associated with, but the advantage of a summaryfile (as generated by TBProfiler) is that all information is condensed in one location. In my opinion it would be best if the format for the 'other_variants' resembles the format of 'dr_variants' as close as possible, so I would opt for a drugs list same as with the dr_variants, although just naming it 'drugs' might be confusing as they are not really associated. I think 'gene_associated_drug' should do just fine.


Kind regards

Lennert


Lennert Verboven



[logo_uantwerp] <https://www.uantwerp.be>    [logo_torch]  <https://torch-consortium.com/>

        TORCH - Tuberculosis Omics ResearCH consortium
Global Health Institute
Gouverneur Kinsbergencentrum - Room 1.16
Doornstraat 331 - 2610 Wilrijk - Belgium
***@***.*** ***@***.***>

________________________________

**Comment by jodyphelan** [comment]
Ok I'll have a go at adding that and let you know when it is done

**Comment by jodyphelan** [comment]
This has now been added in release v3.0.6
