### ISSUE TITLE
interpret the report

### ISSUE THREAD

**Issue by xiaoli-dong** [jodyphelan/TBProfiler#167]
Hi Jody,
Another question. In the following report, I guess the resistance report were generated based on the "missing positions" and "dr_variants". Can you explain a little about it? "R" means resistant ?, what the empty string means?
Thanks,

Resistance report
-----------------
Drug,Genotypic Resistance,Mutations
"Rifampicin","R","rpoB p.Ser450Leu (1.00)"
"Isoniazid","R","fabG1 c.-8T>C (1.00), katG p.Ser315Thr (1.00)"
"Ethambutol","R","embB p.Met306Ile (1.00)"
"Pyrazinamide","R","pncA p.Trp68Gly (1.00)"
"Streptomycin","R","rpsL p.Lys43Arg (1.00)"
"Fluoroquinolones","R","gyrA p.Asp94Ala (1.00)"
"Amikacin","",""
"Capreomycin","",""
"Kanamycin","",""
"Cycloserine","",""
"Ethionamide","R","fabG1 c.-8T>C (1.00)"
"Clofazimine","",""
"Para-aminosalicylic acid","",""
"Delamanid","",""
"Bedaquiline","",""
"Linezolid","",""

Resistance variants report
-----------------
Genome Position,Locus Tag,Gene,Change,Estimated Fraction,Drugs.Drug
"7582","Rv0006","gyrA","p.Asp94Ala",1.000,"ciprofloxacin,fluoroquinolones,levofloxacin,moxifloxacin,ofloxacin"
"761155","Rv0667","rpoB","p.Ser450Leu",1.000,"rifampicin"
"781687","Rv0682","rpsL","p.Lys43Arg",1.000,"streptomycin"
"1673432","Rv1483","fabG1","c.-8T>C",1.000,"ethionamide,isoniazid"
"2155168","Rv1908c","katG","p.Ser315Thr",1.000,"isoniazid"
"2289040","Rv2043c","pncA","p.Trp68Gly",1.000,"pyrazinamide"
"4247431","Rv3795","embB","p.Met306Ile",1.000,"ethambutol"

**Comment by jodyphelan** [comment]
Hi @xiaoli-dong 

The resistance report is genered based on the dr_variants only. It presents one drug per line and aggregates all drug resistance variants into one. You can see in your example that you have two mutations (_fabG1_ c.-8T>C and _katG_ p.Ser315Thr) which appear on separate lines in the _Resistance variants report_ but on one line in the _Resistance report_. This also ensures a constant number of drugs is output even for those which we do not find resistance variants.

**Comment by xiaoli-dong** [comment]
Thank you so much @jodyphelan

**Comment by jodyphelan** [comment]
No problem, I will collate all these descriptions and put them onto the documentation page so this is super useful.
