### ISSUE TITLE
Insertions in promotor regions when using create_db

### ISSUE THREAD

**Issue by LennertVerboven** [jodyphelan/TBProfiler#169]
When using tb-profiler create_db with a custom database that has insertions in promotor regions of genes (e.g. c.-587_-586insT), tb-profiler throws an error  "c.-587_-586insT is not a valid formatted mutation... Exiting!" I believe that you are missing the minus sign in the regex on the line below
https://github.com/jodyphelan/TBProfiler/blob/8a892bd845e1ab439b9a90a5d4c4a463c4b5fb6c/tbprofiler/db.py#L96

When looking at deletions in promotor regions you do have the minus sign in the regex .
https://github.com/jodyphelan/TBProfiler/blob/8a892bd845e1ab439b9a90a5d4c4a463c4b5fb6c/tbprofiler/db.py#L82

**Comment by jodyphelan** [comment]
Ah yeah looks like you spotted the bug and the solution for it! I'll get that fixed asap and create a new release

**Comment by jodyphelan** [comment]
Fixed in latest release and on bioconda
