### ISSUE TITLE
Typo in db

### ISSUE THREAD

**Issue by thobalose** [jodyphelan/TBProfiler#17]
Kindly look into changing `PARA-AMINOSALISYLIC_ACID` to [ `PARA-AMINOSALICYLIC_ACID`](https://www.drugbank.ca/drugs/DB00233) on all relevant files under [db/](https://github.com/jodyphelan/TBProfiler/tree/master/db).

**Comment by jodyphelan** [comment]
Hi,

Thanks for highlighting the typo. Fixed now.

Jody
