### ISSUE TITLE
Possible undercount of number of DR variants in collate report

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#170]
The number of DR variants reported in the collate report is sometimes less that what I was expecting.   For example in the attached spreadsheet, the DR variants fabG1_c.-15C>T, katG_p.Ser315Thr and fabG1_c.-15C>T are reported but the num_DR_variants=2

fabG1_c.-15C>T, katG_p.Ser315Thr are both reported in the Isoniazid column so maybe they are being counted together. 

Best, 

      Michael 

[PossibleDRcountError.xlsx](https://github.com/jodyphelan/TBProfiler/files/6957718/PossibleDRcountError.xlsx)

**Comment by jodyphelan** [comment]
Hi Michael,

The fabG1_c.-15C>T variant confers resistance to both isoniazid and ethionamide and so is present twice in the report, however at it is only counted once to get the total number of DR variants (i.e there are only two unique variants: fabG1_c.-15C>T and katG_p.Ser315Thr). If you need it to be counted twice maybe we can build that in.

Jody

**Comment by harrismia** [comment]
Hi Jody, 

    That makes sense.  I missed that there are only 2 unique variants.   

                Thanks!

           Michael
