### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by Hpinoto** [jodyphelan/TBProfiler#173]
Hi Jody,

I received a 502 bad gateway message:

Bad Gateway
The proxy server received an invalid response from an upstream server.
Apache/2.4.29 (Ubuntu) Server at tbdr.lshtm.ac.uk Port 443

I have tried refreshing/restarting the page, is there anything I can do?

Thanks.

**Comment by jodyphelan** [comment]
Hi @Hpinoto,

Could you send me the link address you are trying to visit?

Jody

**Comment by Hpinoto** [comment]
https://tbdr.lshtm.ac.uk/upload

I was trying to upload these specific sequences but kept on receiving this message.

Thanks

**Comment by jodyphelan** [comment]
Ah right, it seems to load ok for me. Can you try with a different browser or from another device?

**Comment by Hpinoto** [comment]
I just tried it from a different browser and another device, but it showed me the same message. It's just these two particular sequences though, the other sequences seemed to work fine.

**Comment by jodyphelan** [comment]
Ah right, that is interesting... did it get assigned an ID or does it fail before that?

**Comment by Hpinoto** [comment]
It crashed straight after I uploaded the sequences, so it didn't get assigned an ID :(

**Comment by jodyphelan** [comment]
Ok if you want you can send the sequences to me and I can take a look?

**Comment by Hpinoto** [comment]
Sure, I just got permission, should I email you?

**Comment by jodyphelan** [comment]
Sure: &#106;&#111;&#100;&#121;&#046;&#112;&#104;&#101;&#108;&#097;&#110;&#064;&#108;&#115;&#104;&#116;&#109;&#046;&#097;&#099;&#046;&#117;&#107;
