### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by arturotorreso** [jodyphelan/TBProfiler#176]
Hi @jodyphelan, 

I have been using TBprofiler for a while, but it suddenly stopped working. I think it's probably something from my end, but I can't figure out exactly what. I run the test files with the exact commands as in the README file, and they still fail. I attach the error log file (just changed the extension to .txt so github won't complaoin) to see if you can take me on the right direction! 

[ERR1664619.errlog.txt](https://github.com/jodyphelan/TBProfiler/files/7206956/ERR1664619.errlog.txt)

**Comment by jodyphelan** [comment]
Hi @arturotorreso,

Interesting, I'll try replicate on my system and get back to you. Are you using macOS or Linux?

Jody

**Comment by arturotorreso** [comment]
Thank you! I'm using Linux. The last error message I have it's the following: 

```
Running command:
set -u pipefail; samtools view -Mb -L /miniconda3/share/tbprofiler/tbdb.barcode.bed ./3c2b00e1-3644-4ef8-bca1-d25eda468385.bam | bedtools coverage -a /miniconda3/share/tbprofiler/tbdb.barcode.bed -b - -d -sorted
Command Failed! Please Check!Exception ignored in: <generator object cmd_out at 0x7eff59c41550>
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/pathogenprofiler/utils.py", line 146, in cmd_out
    raise Exception
Exception: 
Traceback (most recent call last):
  File "/miniconda3/bin/tb-profiler", line 584, in <module>
    args.func(args)
  File "/miniconda3/bin/tb-profiler", line 177, in main_profile
    no_barcoding=args.no_lineage,variant_annotations=args.add_variant_annotations
  File "/miniconda3/lib/python3.7/site-packages/pathogenprofiler/profiler.py", line 62, in bam_profiler
    mutations = bam_obj.get_bed_gt(conf["barcode"],conf["ref"], caller=caller)
  File "/miniconda3/lib/python3.7/site-packages/pathogenprofiler/bam.py", line 130, in get_bed_gt
    results[chrom][pos] = {ref_nt[(chrom,pos)]:cov}
KeyError: ('Chromosome', 1131)
Cleaning up after failed run

```


I re-run the command `samtools view -Mb -L /miniconda3/share/tbprofiler/tbdb.barcode.bed ./3c2b00e1-3644-4ef8-bca1-d25eda468385.bam | bedtools coverage -a /miniconda3/share/tbprofiler/tbdb.barcode.bed -b - -d -sorted` and it worked with the correct output.

**Comment by jodyphelan** [comment]
Thanks for sending the error.
I am having trouble replicating the issue on my side. 

Seems like it is not finding the key in `ref_nt` [here](https://github.com/jodyphelan/TBProfiler/blob/master/pathogenprofiler/bam.py#L130).
The dictionary is populated by [this piece of code](https://github.com/jodyphelan/TBProfiler/blob/master/pathogenprofiler/bam.py#L115-L122) so potentially this is where it is going wrong. This means it is most likely an issue with bedtools or the reference fasta file.

Have you tried reinstalling `tb-profiler`? This could potentially fix these issues.

**Comment by arturotorreso** [comment]
You are right! I was using bedtools v2.25.0, so I updated it to v2.30.0 and now it works. 

Thanks for pointing to the right direction!
