### ISSUE TITLE
add coverage and mean depth to output

### ISSUE THREAD

**Issue by pmenzel** [jodyphelan/TBProfiler#177]
It would be great to have some stats of the mapping in the summary section of the output, in particular the number of mapped reads, the coverage of the chromosome and the mean depth across all bases.

These numbers can easily obtained by the `samtools coverage` command:
```
>samtools coverage -d 0 mysample.bam                                                                                                                                                                                         
#rname  startpos        endpos  numreads        covbases        coverage        meandepth       meanbaseq       meanmapq
Chromosome      1       4411532 175602  4395413 99.6346 38.8476 22.2    58.3
```

which could show up in the report like this:
```
TBProfiler report
=================

The following report has been generated by TBProfiler.

Summary
-------
ID: mysample
Date: Fri Sep 17 12:57:36 2021
Number of mapped reads: 175602
Genome Coverage:  99.6 %
Mean depth: 38.8 x
Strain: lineage4.4.1.1
Drug-resistance: Sensitive

[...]
```

**Comment by pmenzel** [comment]
Just noticed that option `-d` for `samtools coverage` needs a recent version of samtools. Therefore the bioconda recipe for tb-profiler would need an update:
https://github.com/bioconda/bioconda-recipes/blob/f6b4bb8910ceee02f863eb59db7d2a0b4a5f4779/recipes/tb-profiler/meta.yaml#L22

**Comment by jodyphelan** [comment]
Hi @pmenzel ,

This is a great idea, the number of mapped reads and % reads mapping are already present in the json report, so I just need to add them into the text report. Mean reads depth is currently not extracted but could certainly be added into it. I'll have a go at adding it to the next release.

Jody

**Comment by jodyphelan** [comment]
Added in latest version
