### ISSUE TITLE
Number of reads and Percentage reads mapped

### ISSUE THREAD

**Issue by Manigandan-Venkatesan** [jodyphelan/TBProfiler#178]
Hello, anyone please help me to find out about 

1) Number of reads and 2) Percentage reads mapped

for my samples sequence data after running TBprofiler3.0.8 on my linux system.

Thanks in advance!

**Comment by jodyphelan** [comment]
You can get this information from the json results file:

```
{
  "qc": {
    "pct_reads_mapped": 99.18,
    "num_reads_mapped": 867520,
    },
    ...
}
```
