### ISSUE TITLE
Duplicate Variants

### ISSUE THREAD

**Issue by thobalose** [jodyphelan/TBProfiler#18]
Hi @jodyphelan 

I have noted that [drdb](https://github.com/jodyphelan/TBProfiler/blob/master/db/drdb.txt) has duplicate variants (e.g. [AMIKACIN:1472359:rrs](https://github.com/jodyphelan/TBProfiler/blob/master/db/drdb.txt#L1) and [AMINOGLYCOSIDES:1472359:rrs](https://github.com/jodyphelan/TBProfiler/blob/master/db/drdb.txt#L11)).

I understand that [AMINOGLYCOSIDES](https://www.drugbank.ca/categories/DBCAT000853) is a class in which AMIKACIN belongs to. 

Have you thought about having the more specific variant,  [AMIKACIN:1472359:rrs](https://github.com/jodyphelan/TBProfiler/blob/master/db/drdb.txt#L1), as the main entry and removing the broad class entry?

**Comment by jodyphelan** [comment]
Hi,

Thanks for the feedback. We are currently developing a new library, I will let you know when it's ready!

Jody

**Comment by thobalose** [comment]
@jodyphelan 

Thanks. One more thing, how possible is it to add sources of the variants to the files?

**Comment by jodyphelan** [comment]
Hi, What do you mean by "sources"?

**Comment by thobalose** [comment]
I mean the variant publication or publications that make mention of it.

**Comment by jodyphelan** [comment]
Ah right, unfortunately we have not tracked the sources of variants so far however I plan to have a separate github repo for the new library whereby it will be easier to add this info and track the changes.

**Comment by jodyphelan** [comment]
Hi again,

I have now create a separate [repo](https://github.com/jodyphelan/tbdb) for the mutation library. The mutations are stored in [tbdb.csv](https://github.com/jodyphelan/tbdb/blob/master/tbdb.csv)  and it is now possible to add any extra information for the individual mutations. I have added a "literature" column to the csv file but in theory additional columns will be integrated into the results. Have a look and let me know what you think.

Jody

**Comment by thobalose** [comment]
Awesome! Thanks @jodyphelan
