### ISSUE TITLE
No ONT Data for Testing

### ISSUE THREAD

**Issue by frankambrosio3** [jodyphelan/TBProfiler#180]
Working on implementing this tool as a wdl workflow using the quay hosted docker image latest version. 
Is there testing/validation data available for the --platform nanopore version of the tool? We are seeing an error, but I am unsure if it is because the nanopore fastq file that I am using as the input is too big. 
Note: I am only seeing this issue with the --platform nanopore option and the --call_whole_genome flag active. Removal of the --call_whole_genome flag results in a successful run.
Thanks.

**Comment by jodyphelan** [comment]
Hi @frankambrosio3 

Insteresting, can you post the output of the error? I will try replicate the issue with nanopre data that I have and let you know what I find out.

**Comment by jodyphelan** [comment]
Issue was caused by timeout with test due to long time it takes bcftools to call variants across whole genome with nanopore data. Lastest release uses freebayes as default which is faster.
