### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#189]
It looks like the most recent version of the code is showing version 4.0.1 .   Should this be 4.0.2?

Thanks!

**Comment by jodyphelan** [comment]
Ah yes you are right, I'll get that fixed in the next release. Thanks for letting us know!

**Comment by jodyphelan** [comment]
This should be fixed in release [v4.0.3](https://github.com/jodyphelan/TBProfiler/releases/tag/v4.0.3) and is available on [bioconda](https://bioconda.github.io/recipes/tb-profiler/README.html).
