### ISSUE TITLE
Is there any way to run TBProfiler against a different reference genome?

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#19]
Is it possible to run TBProfiler against a different reference genome?   Specifically, we wanted to try running it against:   https://www.ncbi.nlm.nih.gov/nuccore/NC_018143.2

Thanks!

       Michael

**Comment by jodyphelan** [comment]
Hi Michael,

There is no functionality for that at the moment but we are currently developing a more generalist tool which could be used for this purpose. I'll update you when it's ready to test.

Jody

**Comment by harrismia** [comment]
Hi Jody, 

       Thanks! Looking forward to seeing the new tool.   Best, 

 Michael

**Comment by jodyphelan** [comment]
Hi Michael,

I have created a database for NC_018143.2. The files and commands used to generate it can be found here https://github.com/jodyphelan/tbdb_NC_018143.2. I have done minimal testing so please check the outputs look ok.

Jody

**Comment by harrismia** [comment]
Thanks very much Jody.   We will give it a try and let you know if we run into any issues.

Michael

On May 6, 2019, at 12:46 PM, Jody Phelan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Michael,

I have created a database for NC_018143.2. The files and commands used to generate it can be found here https://github.com/jodyphelan/tbdb_NC_018143.2. I have done minimal testing so please check the outputs look ok.

Jody
