### ISSUE TITLE
Support for Windows system

### ISSUE THREAD

**Issue by qingbo11** [jodyphelan/TBProfiler#190]
**Is your feature request related to a problem? Please describe.**
Hello, I am trying to use TB profiler for predicting the drug resistance of a batch of 65 Mtb genomes. Unfortunately we only have windows system available in our workstation. I tried to use the webserver first, but the limitation of 1 GB data was soon reached and cannot accept new submission. Could you please guide me on how to use the webserver basedon windows system in details?

**Describe the solution you'd like**
It could be useful if the installation of TB profiler can be easily conducted on windows system.
The current instruction for how to install it on windows system is difficult to me and I am unable to succeed in it.

Thanks,

**Additional context**

**Comment by jodyphelan** [comment]
This is due to a bug which has now been fixed. I will be putting out a new release today. Will let you know when live

**Comment by qingbo11** [comment]
Hi Dr. Jody Phelan,

That will be great! Thank you so much.

Best,

Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by jodyphelan** [comment]
This should be fixed in release [v4.0.3](https://github.com/jodyphelan/TBProfiler/releases/tag/v4.0.3) and is available on [bioconda](https://bioconda.github.io/recipes/tb-profiler/README.html).

**Comment by qingbo11** [comment]
Hi Jody,

Thank you again for your support. I updated the version of TB Profiler to 4.0.3, and now I got the results as shown in attachment. My apologize that I don't know how to generate a tbprofiler.tree file from the result json files. Could you please tell me how to generate it? I will use iTOL for the tree visualization and will be more than happy to include it in our manuscript.

Best regards,

Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by jodyphelan** [comment]
No problem, happy to help.
At the moment TB-Profiler does not provide any functionality to actually create the tree. The config files are generated, however the tree must be created with other software. It is planned for future releases, however it might take some time to be fully developed. I would suggest alternative software for the phylogenetic reconstruciton step (such as [snippy](https://github.com/tseemann/snippy) + [iqtree](http://www.iqtree.org/)). This could also be done in a similar way using docker.

**Comment by qingbo11** [comment]
Hi Dr. Jody Phelan,

A question about the "missing position" label in the result.json file. What does it mean? Where can we find the data structure for the json file?

[cid:30f3f634-c141-4441-8f01-2d214fc56815]

Best regards,

Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________
