### ISSUE TITLE
Unable to install TBprofiler on python 3.6 or newer versions on ubuntu 20.04

### ISSUE THREAD

**Issue by Javaria-Ashraf** [jodyphelan/TBProfiler#192]
Dear Jody,

I'm unable to install TBProfiler on any of my ubuntu operating system. Can you please help me with this error:

```
`Running command:
set -u pipefail; snpEff -Djava.net.useSystemProxies=true ann Mycobacterium_tuberculosis_h37rv 55c4fd71-a7dd-4bea-b202-8fc6608bd2f3
Traceback (most recent call last):
  File "/home/isd/miniconda3/envs/py36/bin/tb-profiler", line 582, in <module>
    args.func(args)
  File "/home/isd/miniconda3/envs/py36/bin/tb-profiler", line 237, in main_create_db
    tbp.create_db(args)
  File "/home/isd/miniconda3/envs/py36/lib/python3.6/site-packages/tbprofiler/db.py", line 407, in create_db
    mut = mutation_lookup[(row["Gene"],row["Mutation"])]
KeyError: ('ddn', 'c.51_101delTATCAAGTGGATGTCACGGATTAATACCTGGATGTACCGCCGCAACGACGG')


################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the
contents of the error log (tbdb.errlog)

###############################################################################


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/isd/miniconda3/envs/py36/bin/tb-profiler", line 30, in cleanup
    with open(outfile, "w") as O:
UnboundLocalError: local variable 'outfile' referenced before assignment
`
```
Thanks

J

**Comment by jodyphelan** [comment]
Hi @Javaria-Ashraf 

Did you install through conda?
Can you check if `snpEff` is working for you? It looks like this might be the issue

**Comment by Javaria-Ashraf** [comment]
I installed it manually as well as through conda but getting the same error. and no snpEFF is not in the path or system. Why is that so

**Comment by jodyphelan** [comment]
Ah, so I think that is probably where the error is coming from. I have recently introduced snpEff as a dependancy but forgot to update the README.md file, so if you have installed manually then this is why it is missing, apologies for that. Although, if you install from conda it should be included as a dependancy and should have been installed. Can you try run the folling and paste the output?
```
conda create -n tb-profiler tb-profiler
```

**Comment by Javaria-Ashraf** [comment]
Conda take ages to run ! it keeps on giving errors on solving environment and after rerunning it multiple times it run the command. So waiting once it is ran i ll update.

Thanks
J

**Comment by jodyphelan** [comment]
Ok, it might also be a good idea to use `mamba`. It's basically a faster version of conda built using c++ (https://github.com/mamba-org/mamba). You can install it with `conda install mamba` and then just use `mamba` instead of `conda` in all your commands

**Comment by Javaria-Ashraf** [comment]
Thank You so much it actually now running :) 


Thanks

J
