### ISSUE TITLE
Adding Pilon as an option for calling

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#194]
Would you consider adding [Pilon](https://github.com/broadinstitute/pilon) as a caller option?   Pilon has been shown to work very well with haploid genomes. 

Also see: [Pilon Wiki](https://github.com/broadinstitute/pilon/wiki)

**Comment by jodyphelan** [comment]
Sure, I can look into this.

**Comment by jodyphelan** [comment]
Starting this now, if you are already running it, do you have an example command? If not don't worry!

**Comment by harrismia** [comment]
So sorry I missed your message.  Thanks so much for working on this! I will look for the command and post it here.

**Comment by jodyphelan** [comment]
No problem, there is an outstanding small issue with the VCF header output from pilon (https://github.com/broadinstitute/pilon/issues/141) but I've git a PR in to fix that. In the meantime I've created a crude patch for it within tb-profiler. It will be included in the next release!

**Comment by jeffreybm** [comment]
Hi Jody, the pilon command we've been using to generate VCFs in @harrismia TB group:

java -Xmx16G -jar pilon-1.22.jar --threads {threads} --genome {params.reference} --frags {input} --output {params.vcf_out} --vcf

**Comment by harrismia** [comment]
Great news that pilot will be in the next release!

**Comment by jodyphelan** [comment]
This has now been added and will be included in the next conda release. Thanks for the suggestion!

**Comment by harrismia** [comment]
Great news! Thanks!
