### ISSUE TITLE
Can't find ./XTBDNA-17-077.delly.bcf

### ISSUE THREAD

**Issue by AaronHY** [jodyphelan/TBProfiler#196]
Hello, I have run the command for testing below:

tb-profiler profile -1 XTBDNA-17-077_1.fastq.gz -2 XTBDNA-17-077_2.fastq.gz -p XTBDNA-17-077

And it comes:

...

Running command:
set -u pipefail; bedtools coverage -a /home/miniconda3/envs/tb-profiler/share/tbprofiler/tbdb.barcode.bed -b ./XTBDNA-17-077.bam -d -sorted

Running command:
set -u pipefail; delly call -t DEL -g /home/miniconda3/envs/tb-profiler/share/tbprofiler/tbdb.fasta ./XTBDNA-17-077.bam -o ./XTBDNA-17-077.delly.bcf
Can't find ./XTBDNA-17-077.delly.bcf

Shall I need to reinstall Delly or update it? Please assist and thanks in advance.

Yi

**Comment by jodyphelan** [comment]
Hi @AaronHY 

Can you check to see if delly is installed? just by running `delly`. Did the pipeline produce a file called `XTBDNA-17-077.errlog`?

**Comment by jodyphelan** [comment]
Closing this for now. Feel free to open if there is still is an issue.

**Comment by arupgsh** [comment]
Hi,

I'm having the same issue while running the file with bam files.

command:
 tb-profiler profile -a aligned_bwa.bam -p test

error:

Can't find ./37713b50-547f-42d9-9c06-e40d1d0ee461.delly.bcf

Delly is installed in the env and no error log is generated.

**Comment by jodyphelan** [comment]
Hi @arupgsh ,

Can you post the full output?

**Comment by arupgsh** [comment]
(tbprofiler) [arup@headnode tbprofiler_result]$ tb-profiler profile -a ../dedup_all/SRR5341435.bam -p test
Using gff file: /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.gff
Using ref file: /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta
Using barcode file: /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed
Using bed file: /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed
Using json_db file: /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.dr.json
Using version file: /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.version.json
Using variables file: /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.variables.json
Using ../dedup_all/SRR5341435.bam

Please ensure that this BAM was made using the same reference as in the database.
If you are not sure what reference was used it is best to remap the reads.

Running command:
set -u pipefail; cat /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 1 --col-sep " " "samtools view -T /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -h ../dedup_all/SRR5341435.bam {1} | samclip --ref /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta | samtools view -b > ./bebdc991-6dce-410e-9c7a-b90cac325136.{2}.tmp.bam && samtools index ./bebdc991-6dce-410e-9c7a-b90cac325136.{2}.tmp.bam && freebayes -f /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -r {1} --haplotype-length -1  ./bebdc991-6dce-410e-9c7a-b90cac325136.{2}.tmp.bam | bcftools view -c 1 | bcftools norm -f /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta | bcftools filter -t {1} -e 'FMT/DP<10' -S . -Oz -o ./bebdc991-6dce-410e-9c7a-b90cac325136.{2}.vcf.gz"

Running command:
set -u pipefail; cat /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 1 --col-sep " " "bcftools index  ./bebdc991-6dce-410e-9c7a-b90cac325136.{2}.vcf.gz"

Running command:
set -u pipefail; bcftools concat -aD `cat /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | awk '{print "./bebdc991-6dce-410e-9c7a-b90cac325136."$2".vcf.gz"}'` | bcftools view -c1 -a -Oz -o ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.vcf.gz

Running command:
set -u pipefail; rm `cat /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | awk '{print "./bebdc991-6dce-410e-9c7a-b90cac325136."$2".vcf.gz*"}'`

Running command:
set -u pipefail; rm `cat /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | awk '{print "./bebdc991-6dce-410e-9c7a-b90cac325136."$2".tmp.bam*"}'`

Running command:
set -u pipefail; bcftools index --threads 1 -ft ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.vcf.gz

Running command:
set -u pipefail; bcftools query -l ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.vcf.gz

Running command:
set -u pipefail; bcftools view -v snps ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.vcf.gz | combine_vcf_variants.py --ref /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta --gff /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.gff | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff ann -noLog -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 08569408-e288-46e1-9365-e784e1eafa54.vcf

Running command:
set -u pipefail; bcftools view -v indels ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.vcf.gz | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff ann -noLog -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 84a44513-3bfa-4366-99bb-17e86b72a61d.vcf

Running command:
set -u pipefail; bcftools concat 08569408-e288-46e1-9365-e784e1eafa54.vcf 84a44513-3bfa-4366-99bb-17e86b72a61d.vcf | bcftools sort -Oz -o ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.csq.vcf.gz
Removing 08569408-e288-46e1-9365-e784e1eafa54.vcf
Removing 84a44513-3bfa-4366-99bb-17e86b72a61d.vcf

Running command:
set -u pipefail; bcftools index --threads 1 -ft ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.csq.vcf.gz

Running command:
set -u pipefail; bcftools query -l ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.csq.vcf.gz

Running command:
set -u pipefail; bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT\t%ANN\t[%AD]\n' ./bebdc991-6dce-410e-9c7a-b90cac325136.targets.csq.vcf.gz

Running command:
set -u pipefail; samtools flagstat -O json ../dedup_all/SRR5341435.bam > 236c02a8-51aa-49b2-8a25-c634e2fa3986

Running command:
set -u pipefail; bedtools genomecov -ibam ../dedup_all/SRR5341435.bam

Running command:
set -u pipefail; samtools view -Mb -L /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed ../dedup_all/SRR5341435.bam | bedtools coverage -a /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed -b - -d -sorted

Running command:
set -u pipefail; samtools view -Mb -L /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed ../dedup_all/SRR5341435.bam > ./bebdc991-6dce-410e-9c7a-b90cac325136.tmp.bam

Running command:
set -u pipefail; samtools index ./bebdc991-6dce-410e-9c7a-b90cac325136.tmp.bam

Running command:
set -u pipefail; freebayes -f /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -t /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed ./bebdc991-6dce-410e-9c7a-b90cac325136.tmp.bam --haplotype-length -1 | bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%GT\t%AD]\n'

Running command:
set -u pipefail; bedtools getfasta -fi /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta -bed /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed

Running command:
set -u pipefail; samtools view -Mb -L /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed ../dedup_all/SRR5341435.bam | bedtools coverage -a /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed -b - -d -sorted

Running command:
set -u pipefail; delly call -t DEL -g /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta ../dedup_all/SRR5341435.bam -o ./bebdc991-6dce-410e-9c7a-b90cac325136.delly.bcf
Can't find ./bebdc991-6dce-410e-9c7a-b90cac325136.delly.bcf

**Comment by jodyphelan** [comment]
Thanks, ok could you just run the delly command and provide the output?
```
delly call -t DEL -g /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta ../dedup_all/SRR5341435.bam -o ./bebdc991-6dce-410e-9c7a-b90cac325136.delly.bcf
```

**Comment by arupgsh** [comment]
The chromosome names are not matching.

BAM file chromosome NC_000962.3 is NOT present in your reference file /userdata/arup/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta

Is there any way I can specify or update the default reference genome used by TB-profiler ?

**Comment by jodyphelan** [comment]
Oh yeah what you should do it to update the database and feed in your reference genome so that it matches the chromosome names correctly. Try this:
```
tb-profiler update_tbdb --match_ref /path/to/ref.fa
```

**Comment by klaasdewaele** [comment]
A reinstall using Mamba resolved this

**Comment by jodyphelan** [comment]
Thanks @klaasdewaele, do you know if it installed a different version of delly?

**Comment by klaasdewaele** [comment]
Hi @jodyphelan

Delly version: v0.8.7
 using Boost: v1.74.0
 using HTSlib: v1.12

**Comment by jodyphelan** [comment]
Thanks I'll try pin those versions in the recipe
