### ISSUE TITLE
Error running tb-profiler using data downloaded from the SRA

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#2]
Hello, 

Thanks for making this code available!    I was able to build the code on my mac OSX using the provided instructions.   It seems to work fine on the example files: ERR1664619_1.fastq.gz, ERR1664619_2.fastq.gz

When  I try to run it on SRR files that I downloaded from the SRA it throws an   error.  To get the SRA data I did:

`~/Tools/sratoolkit.2.8.2-1-mac64/bin/fastq-dump -I --gzip --split-files SRR5486866`
      
which produces two files:   SRR5486866_1.fastq.gz, SRR5486866_2.fastq.gz    I then executed:
(not sure what the -t 4 does as  -t is not listed in the -help output).

`tb-profiler full -1 ./SRR5486866_1.fastq.gz -2 SRR5486866_2.fastq.gz -t 4 -p SRR5486866_tbprof`

Which produces the error: 
_set([])
Traceback (most recent call last):
  File "tb-profiler", line 538, in <module>
    args.func(args)
  File "tb-profiler", line 500, in main_run_pipeline
    lin = assign_lin(args.prefix)
  File "/tb-profiler", line 91, in assign_lin
    dict_sample_lin[sample_lin[0].split(".")[0]] = sorted([x for x in sample_lin if "." in x and sample_lin[0].split(".")[0] in x])[-1]_

**Comment by harrismia** [comment]
I redownloaded the SRA files but omitted the -I in the command.  tb-profiler seems to work fine on the newly created  .gz files.

**Comment by jodyphelan** [comment]
Hi @harrismia, good to hear you fixed the problem. I will add some more usefull error messages with the next release.
