### ISSUE TITLE
AttributeError in collate

### ISSUE THREAD

**Issue by Edohan** [jodyphelan/TBProfiler#20]
Hi,

I keep getting an AttributeError when running the collate part of your pipeline. It worked previously on other sample sets but I can't seem to figure out what the problem is now.

Traceback (most recent call last):
  File "./bin/tb-profiler", line 79, in <module>
    args.func(args)
  File "./bin/tb-profiler", line 19, in main_collate
    obj.results2tab()
  File "/home/edohan/software/tbprofiler/bin/tbprofiler/collate.py", line 56, in results2tab
    results[s][d].add("%s_%s" % (x["gene"],x["change"]) if self.full_results else "R")
AttributeError: 'str' object has no attribute 'add'

Best,
Edohan

**Comment by jodyphelan** [comment]
Hi Edohan,

This issue might arise if you have duplicates in the samples file. Can you try to see if there are any?
Let me know if this doesn't fix the issue.

Jody

**Comment by Edohan** [comment]
Hi,

It is solved after amended as you suggested.

Thank you,
Edohan
