### ISSUE TITLE
RR-TB and HR-TB definations

### ISSUE THREAD

**Issue by KevinLYW366** [jodyphelan/TBProfiler#200]
Hi Jody,

It's great to have WHO updated definations of XDR and pre-XDR in the latest version of TB-Profiler. Thanks!

It seems the old classification type pre-MDR is now replaced by RR-TB and HR-TB. I checked the code and found:
```
elif (rif and not inh) and (not flq and not gpa):
        drtype = "RR-TB"
elif (inh and not rif) and (not flq and not gpa):
        drtype = "HR-MDR"
```
Based on WHO definations of RR-TB and HR-TB, however, resistance to other drugs except for rifampicin and isoniazid are not mentioned. I'm wondering if this part "(not flq and not gpa)" shoud be in the condition?

Best,
Kevin

**Comment by jodyphelan** [comment]
Sorry I missed this in the run up to the holidays!

Yes this is something that potentially needs to be updated. Here is the definition of pre-XDR-TB from the WHO for reference:
> The new definition of pre-XDR-TB is: TB caused by Mycobacterium tuberculosis (M. tuberculosis) strains that fulfil the definition of multidrug resistant and rifampicin-resistant TB (MDR/RR-TB) and which are also resistant to any fluoroquinolone. The definition of MDR-TB* remains unchanged.

I'll use an example of a sample has resistance to **rif and flq**. This sample would need to be classified as pre-XDR according to the above definition. In the code, after checking if a sample is pan-susceptible, I first check for for RR-TB. A simple way would be to just do:
```
elif (rif and not inh):
```
However our sample from above would then be classified as RR-TB as opposed to pre-XDR as this checked first.
For this reason I have forced the absence of fluroquinolone (flq) in the if statement. I also force the absence of group A drugs (gpa) although I just realised this is not part of the pre-XDR definition. I am still not 100% sure if this is the best way to do it and if it fully adheres to the WHO definitions, so any feedback would be more than welcome.

**Comment by KevinLYW366** [comment]
I think you are right. I missed the part "MDR/RR-TB" in pre-XDR and XDR definition, which was a little bit confusing. Now I understand from your answer that RR-TB could also be a prerequisite for pre-XDR and XDR instead of MDR.

Following is my suggestion, which I hope might be helpful:

1. RR-TB: `(rif and not inh) and not flq`
2. HR-MDR: I cannot find the definition for HR-MDR. Does it stand for cases which are resistant to inh but are not MDR, pre-XDR or XDR? If so, `not rif and inh`
3. MDR: `(rif and inh) and not flq`
4. pre-XDR: `(MDR or RR-TB) and (flq and not gpa)`, `MDR or RR-TB` could be merged. After merging, `rif and flq`
5. XDR: `(MDR or RR-TB) and (flq and gpa)`, `MDR or RR-TB` could be merged. After merging, `rif and (flq and gpa)`

By the way, the codes to generate iTOL annotation file are not updated to support new drug resistance classification categories. Thanks, Jody!

**Comment by jodyphelan** [comment]
Thanks Kevin, those all look like good suggestions! I'll implement them and the update itol configs in the next release

**Comment by KevinLYW366** [comment]
@jodyphelan Great! Thanks

**Comment by KevinLYW366** [comment]
Hi, Jody @jodyphelan, I noticed two typos in your fix:

1. collate.py: should be `RR-TB` in `dr_cols` to match up with reformat.py
2. reformat.py: it would be better to remove the part `not flq` from the condition for `HR-MDR`. Considering about this, a case resistant to inh and flq would still be defined as HR-MDR based on WHO definition, which is different from RR-TB.

**Comment by jodyphelan** [comment]
Thanks for letting me know. I was thinking to keep the names more consistent with the WHO naming to append "-TB" after all RR, HR, MDR, Pre-XDR and XDR. Do you this would work?

Sensitive
RR-TB
HR-TB
MDR-TB
Pre-XDR-TB
XDR-TB
Other

**Comment by KevinLYW366** [comment]
These terms are good! I found a meeting report from WHO for reference (https://apps.who.int/iris/rest/bitstreams/1327986/retrieve). Actually they are using the same names just like you did.

**Comment by KevinLYW366** [comment]
Hi Jody,

I've tested TB-Profiler v4.1.0. It worked well except for an error message caused by the part to generate dr.itol.txt. As you can see, different drug resistance type names are used in the source code. Besides, RR-TB and HR-TB are sharing the same color code.

Line 117-118 in collate.py:
```  
OUT = open(prefix+".dr.itol.txt","w")
dr_cols = {"Sensitive":"#28a745","RR-MDR":"#007bff","HR-MDR":"#007bff","MDR":"#ffc107","Pre-XDR":"#dc3545","XDR":"#343a40","Other":"#f8f9fa"}
```

**Comment by jodyphelan** [comment]
Oh right! Don't know why that didn't get flaaged up in the tests. I'll get that fixed today!
Yeah I wasn't too sure on the colours, since RR-TB and HR-TB are kind of on the same Pre-MDR level. Would you rather different colours?

**Comment by KevinLYW366** [comment]
@jodyphelan I prefer two different colors for RR-TB and HR-TB since RR-TB is a prerequisite for pre-XDR but not HR-TB. I think two similar colors woud work (light and dark).

**Comment by jodyphelan** [comment]
Ok great!

**Comment by KevinLYW366** [comment]
Tested. Issues are fixed in this updated version. Thank you!
