### ISSUE TITLE
tb-profiler collate --full --all_variants   ?

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#21]
Hi Jody, 

            Can you describe what  

                    tb-profiler collate --full --all_variants     
                       vs  
                    tb-profiler collate --full      
                       vs 
                    tb-profiler collage  --all_variants 

               should produce?

              I was expecting one of these options to include data from the "other small variants in candidate genes" from the results but I don't see that.  When I try the  --full or --all_variants or both options I don't seem to be getting more data included in the spreadsheet. There are definitely more columns many of which are all 0s  but I am not clear on what those extra columns represent.   Are they also documented drug resistance variants?    

       Thanks!

                Michael

**Comment by jodyphelan** [comment]
Hi Michael,

The --full option will give you a results file with the mutations causing resistance for each sample (vs just an "R" for the samples)
The --all_variants will create a new file with all the drug-resistance mutations as columns and the samples as rows. If the mutation is present in a sample it will give the proportion of the reads which support the mutation.

Hope that answers your question,
Jody

**Comment by harrismia** [comment]
Thanks Jody, this is helpful!       

         Michael
