### ISSUE TITLE
Run has failed

### ISSUE THREAD

**Issue by ryobon-dev** [jodyphelan/TBProfiler#211]
During the run, I got the following error message.

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the
contents of the error log (out.errlog)

I have attached the errlog.

Could you please let me know how to solve this error.

Thanks,

[log.txt](https://github.com/jodyphelan/TBProfiler/files/8339639/log.txt)

**Comment by jodyphelan** [comment]
There seems to be an issue with your bcftools. Could you run the following commands and send back the output?

```
bcftools --version
conda env export | grep bcftools
```

**Comment by jodyphelan** [comment]
It may be that one of the conda dependancies is on the wrong version.
Try to install this conda env with [env.yml.txt](https://github.com/jodyphelan/TBProfiler/files/8348393/env.yml.txt):
`conda env create -f env.yml`

**Comment by jodyphelan** [comment]
I'm going to close this for now but feel free to reopen it if there are more related issues.

**Comment by jloubser** [comment]
Dear Jody, 

Sorry to comment on this again.
I'm running into this issue as well. Does the content of this yml file remain the same and one just change the tb-profiler version. Or does this file get extensively updated with every version?

**Comment by jodyphelan** [comment]
It shouldn't change too much, although tb-profiler depends on pathogen-profiler and they often increment up together. Other than that, it should stay fairly stable. 
You can use this updated environment file: [tb-profiler_v4.3.0.env.yml.txt](https://github.com/jodyphelan/TBProfiler/files/9459987/tb-profiler_v4.3.0.env.yml.txt)
Or if that doesn't work you could try using this explicit list: [tb-profiler_v4.3.0.env.spec-file.txt](https://github.com/jodyphelan/TBProfiler/files/9459997/tb-profiler_v4.3.0.env.spec-file.txt)
