### ISSUE TITLE
tb-profiler reports an error

### ISSUE THREAD

**Issue by zzzr999** [jodyphelan/TBProfiler#212]
seek help for everyone
tb-profiler profile -1 /F2393_R1.fastq.gz -2 F2393_R2.fastq.gz -p F2393
Traceback (most recent call last):
  File "/home/zhangrui/miniconda3/bin/tb-profiler", line 333, in <module>
    args.func(args)
  File "/home/zhangrui/miniconda3/bin/tb-profiler", line 82, in main_profile
    results = pp.profiler(conf_file=conf_file,prefix=args.dir+"/"+args.prefix,r1=args.read1,r2=args.read2,bam_file=args.bam,call_method=args.call_method,min_depth=args.min_depth,threads=args.threads,platform=args.platform,mapper=args.mapper,run_delly=True,af=args.af)
TypeError: profiler() got an unexpected keyword argument 'af'

**Comment by jodyphelan** [comment]
Hi @zzzr999 

Which version are you using? 
You can check this with `tb-profiler version`

**Comment by jodyphelan** [comment]
I'm going to close this for now but feel free to reopen it if there are more related issues.
