### ISSUE TITLE
tb-profiler works for root user but not me, a user with more limited permissions/access to the server

### ISSUE THREAD

**Issue by yumnamoosa** [jodyphelan/TBProfiler#216]
Hi Jody

I'm having trouble running the tb-profiler collate command on my institution's remote server. Our original solution was that a colleague who had root user access ran it - and it worked - but then we re-installed it with the intention that I could run it myself and now it isn't working. See below. 

Any clever ideas that could help?

Thanks in advance,

Yumna

(base) [yumna@krisp2 tbp_output]$ tb-profiler collate --full
Using ref file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.fasta
Using gff file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.gff
Using bed file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.bed
Using version file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.version.json
Using json_db file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.dr.json
Using variables file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.variables.json
Using spoligotype_spacers file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.spoligotype_spacers.txt
Using barcode file: /data/users/home/yumna/miniconda3/share/tbprofiler//tbdb.barcode.bed
  2%|█▋                                                                                | 2/95 [00:00<00:00, 2594.68it/s]
Traceback (most recent call last):
  File "/data/users/home/yumna/miniconda3/bin/tb-profiler", line 566, in <module>
    args.func(args)
  File "/data/users/home/yumna/miniconda3/bin/tb-profiler", line 254, in main_collate
    tbp.collate_results(args.prefix,args.conf,sample_file=args.samples,result_dir=args.dir,reporting_af=args.reporting_af,mark_missing=args.mark_missing)
  File "/data/users/home/yumna/miniconda3/lib/python3.9/site-packages/tbprofiler/collate.py", line 58, in collate_results
    for d in x["drugs"]:
KeyError: 'drugs'
Cleaning up after failed run
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/data/users/home/yumna/miniconda3/bin/tb-profiler", line 32, in cleanup
    with open(outfile, "w") as O:
PermissionError: [Errno 13] Permission denied: 'tbprofiler.errlog'

**Comment by jodyphelan** [comment]
Hi @yumnamoosa 

From the output you posted it looks like there might be two different issues:
1. The first one is that you get a KeyError being thrown which could indicate a difference between the tb-profiler version and the database version. 
2. The second is the PermissionError which as you said is not working due to some permissions error.

Let's start with the permissions error first. Did you install it through conda via the root user? Which version do you have installed? Can you let me know if if you can actually write to the directory that you are running `tb-profiler` in? (you can do this by running `touch test.txt`)

**Comment by yumnamoosa** [comment]
Okay, so, I can't write to the directory unless I sudo touch test.txt and
type in my password, in which case it works.

But if I sudo tb-profiler collate --full then it gives me this error
message:

sudo: tb-profiler: command not found

My colleague (who is now cc'ed) installed it initially, and it was an older
version. He re-installed the latest version last week. He says he did as
follows:

To install,
> I logged into the server and run; *sudo su yumna* to switch user to you
> so I could install as you. Install the latest version...4.x.x.


He is going to try to install without the sudo privilege and check whether
that works. If not, I'll be back in your inbox.

Thank you for your help,

Yumna

**Comment by jodyphelan** [comment]
I'm gonna close this for now, but feel free to reopen this if there are any issues!
