### ISSUE TITLE
Spoligotype argument

### ISSUE THREAD

**Issue by ksw9** [jodyphelan/TBProfiler#219]
Dear Jody,

Thank you for a fantastic tool! 

I'm wondering which version the experimental --spoligotype command can be used? I tried in version 2.8.12 and receive the error: 
unrecognized arguments: --spoligotype. 

I'm also wondering if this will be reported as an SIT, so the spoligotype could be compared to those in the international database? 

Thank you in advance and best,
Katie

**Comment by jodyphelan** [comment]
Hi @ksw9 

This was introduced with the latest version (v4.2.0). At the moment it just reports the octal/binary code but the plan is to have it link up to the SIT numbers. I can prioritize that for the next version.

**Comment by ksw9** [comment]
Dear Jody, Thank you and apologies, I didn’t see that I wasn’t using the latest version. Thank you for the quick reply!
Best,
Katie

From: Jody Phelan ***@***.***>
Date: Thursday, June 2, 2022 at 4:15 PM
To: jodyphelan/TBProfiler ***@***.***>
Cc: Katharine Walter ***@***.***>, Mention ***@***.***>
Subject: Re: [jodyphelan/TBProfiler] Spoligotype argument (Issue #219)

Hi @ksw9<https://github.com/ksw9>

This was introduced with the latest version (v4.2.0). At the moment it just reports the octal/binary code but the plan is to have it link up to the SIT numbers. I can prioritize that for the next version.

**Comment by jodyphelan** [comment]
Just following up on this... release v4.3.0 now includes Family and SIT in the report:

```
Spoligotype report
------------------
Binary: 1111111111111111111100001111111100001000000
Octal: 777777607760400
Family: LAM4
SIT: 1106
```

**Comment by ksw9** [comment]
Fantastic—thank you for the update and work on this Jody!

From: Jody Phelan ***@***.***>
Date: Sunday, August 21, 2022 at 5:43 AM
To: jodyphelan/TBProfiler ***@***.***>
Cc: Katharine Walter ***@***.***>, Mention ***@***.***>
Subject: Re: [jodyphelan/TBProfiler] Spoligotype argument (Issue #219)

Just following up on this... release v4.3.0 now includes Family and SIT in the report:

Spoligotype report

------------------

Binary: 1111111111111111111100001111111100001000000

Octal: 777777607760400

Family: LAM4

SIT: 1106
