### ISSUE TITLE
ITOL outputs

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#22]
Hi Jody, 

          Would it be possible for you to add some documentation and examples about how this tb-profiler output can be used?   I am not familiar with ITOL.    Thanks!

      Michael

**Comment by jodyphelan** [comment]
Hi Michael,

I've now added some example files and documentation to the readme.

Jody

**Comment by harrismia** [comment]
Thanks Jody! It looks great.  Best, 

  Michael
