### ISSUE TITLE
spoligotype calling question

### ISSUE THREAD

**Issue by jeffreybm** [jodyphelan/TBProfiler#220]
Hi Jody,

This question is related to issue https://github.com/jodyphelan/TBProfiler/issues/219

Our group has been using Lorikeet for predicting spoligotype lineage, however we are in process of switching to using TBprofilers spoligo lineage output that is reported by default.  Will the new --spoligotype experimental option add more spoligo information like the octal value?  We're just curious how the new --spoligotype option will differ from what is already reported.

Cheers,

Brendan

**Comment by jodyphelan** [comment]
Hi @jeffreybm,

The default spoligotype reported is based on associations associations of spoligotype with lineage (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4166679/bin/ncomms5812-s2.xlsx). So it just reports the spoligotype(s) that have been found in the predicted lineage. 

The new `--spoligotype` option actually performs the spoligotyping by looking for the spacers in the reads. This produces the binary reporesenation and the octal code. In the next release it is planned also to report the ST number as seen in [SITVIT2](http://www.pasteur-guadeloupe.fr:8081/SITVIT2/).

**Comment by jodyphelan** [comment]
Just following up on this... release v4.3.0  now includes Family and SIT in the report:

```
Spoligotype report
------------------
Binary: 1111111111111111111100001111111100001000000
Octal: 777777607760400
Family: LAM4
SIT: 1106
```
