### ISSUE TITLE
question re fluoroquinolones

### ISSUE THREAD

**Issue by pmenzel** [jodyphelan/TBProfiler#223]
Hi Jody,
I have another question about the reporting of fluoroquinolones.

For example, when finding variants in gyrA or gyrB, the `results.txt` shows them like
```
Resistance report
-----------------
Drug	Genotypic Resistance	Mutations
Fluoroquinolones	R	gyrB p.Ala504Thr (1.00), gyrA p.Asp94Ala (1.00)

Resistance variants report
-----------------
Genome Position	Locus Tag	Gene	Variant Type	Change	Estimated Fraction	Drug
6749	Rv0005	gyrB	missense_variant	p.Ala504Thr	1.000	ofloxacin,moxifloxacin,levofloxacin,fluoroquinolones,ciprofloxacin
7582	Rv0006	gyrA	missense_variant	p.Asp94Ala	1.000	ofloxacin,moxifloxacin,levofloxacin,fluoroquinolones,ciprofloxacin
``` 

In the variants report, the drugs `ofloxacin,moxifloxacin,levofloxacin,ciprofloxacin` are listed additionally to their group fluoroquinolones, but in the resistance report, only fluoroquinolones is printed.

Is there a special meaning here? Would it be possible to only have some of these 4 drugs being affected by a variant?

I am currently parsing the `results.json` file to generate a report and was thinking if these 4 can always be summarized as fluoroquinolones, like it is done in `results.txt`.

**Comment by jodyphelan** [comment]
There are some instances of mutations that seem to selectively give resistance to only one drug in the fluoroquinolone class, althogh this seems to be pretty rare: https://github.com/jodyphelan/tbdb/issues/30

At the moment the "fluoroquinolones" field is shown as resistant if a variant is present that gives resistant to all fluoroquinolones
