### ISSUE TITLE
tbdb.spoligotype_spacers.txt missing 

### ISSUE THREAD

**Issue by ksw9** [jodyphelan/TBProfiler#224]
Dear Jody,

Thank you again for a fantastic resource! I've been using TBProfiler 4.2.0, installed with Conda. I am running into an error that the tbdb.spoligotype_spacers.txt is missing. When I download directly from your Github, the pipeline proceeds with no errors. I'm not sure if I'm doing something wrong or perhaps this wasn't included in the Conda release?

Thank you for your help!
All the best,

**Comment by jodyphelan** [comment]
Hi @ksw9 ,

The conda release was missing one file that is important for spoligotyping (https://github.com/jodyphelan/TBProfiler/blob/master/db/tbdb.spoligotype_spacers.txt)

If you want to run it from a conda install it should work if you run `tb-profiler update_tbdb` before profiling. This will download the latest DB from github which includes the missing file.
