### ISSUE TITLE
fasta_profile

### ISSUE THREAD

**Issue by qingbo11** [jodyphelan/TBProfiler#227]
Hello Jody, 

I would like to know if it is possible to analyze the public genome sequences of Mtb downloaded from PATRIC database (https://patricbrc.org/search/?and(keyword(MYCOBACTERIUM),keyword(TUBERCULOSIS))). They are mainly contigs assemble in fasta format. I noticed that #208 mentioned the possible way of using fasta genome as input. I wonder if the contigs assemble genome can also be used as input. What is the right way to analyze this type of data.

Thank you!

**Comment by jodyphelan** [comment]
Hi @qingbo11 

Yes, you can analyse contigs from an assembly! All you need to do is to use the fasta file as input using `-f file.fasta`. For example:

```
tb-profiler profile -f mycontigs.fasta
```

**Comment by qingbo11** [comment]
Thank you. I tried the command you suggested. It stopped in the middle. Can you help me on it?

sh-5.0# tb-profiler fasta_profile --fasta 1733.1000.fna --prefix 1733.1000
Using gff file: /usr/local/share/tbprofiler/tbdb.gff
Using ref file: /usr/local/share/tbprofiler/tbdb.fasta
Using barcode file: /usr/local/share/tbprofiler/tbdb.barcode.bed
Using bed file: /usr/local/share/tbprofiler/tbdb.bed
Using json_db file: /usr/local/share/tbprofiler/tbdb.dr.json
Using version file: /usr/local/share/tbprofiler/tbdb.version.json
Using variables file: /usr/local/share/tbprofiler/tbdb.variables.json

Running command:
set -u pipefail; minimap2 /usr/local/share/tbprofiler/tbdb.fasta 1733.1000.fna --cs | sort -k6,6 -k8,8n | paftools.js call -l 100 -L 100 -f /usr/local/share/tbprofiler/tbdb.fasta -s 1733.1000 - | add_dummy_AD.py | bcftools view -Oz -o 1733.1000.vcf.gz

Running command:
set -u pipefail; bcftools index --threads 1 -ft 1733.1000.vcf.gz

Running command:
set -u pipefail; bcftools query -l 1733.1000.vcf.gz

Running command:
set -u pipefail; bcftools view -c 1 1733.1000.vcf.gz -Oz -o 1733.1000.targets.vcf.gz -T /usr/local/share/tbprofiler/tbdb.bed

Running command:
set -u pipefail; bcftools view -v snps 1733.1000.vcf.gz | combine_vcf_variants.py --ref /usr/local/share/tbprofiler/tbdb.fasta --gff /usr/local/share/tbprofiler/tbdb.gff | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff -Djava.net.useSystemProxies=true ann -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 2b55550e-1cd8-4ce9-aefe-aa7ea0ce9bbd.vcf

Running command:
set -u pipefail; bcftools view -v indels 1733.1000.vcf.gz | rename_vcf_chrom.py --source Chromosome --target Chromosome | snpEff -Djava.net.useSystemProxies=true ann -noStats Mycobacterium_tuberculosis_h37rv - | rename_vcf_chrom.py --source Chromosome --target Chromosome > 7a6d9132-b2b7-4c73-890b-01c2c213bdda.vcf

Running command:
set -u pipefail; bcftools concat 2b55550e-1cd8-4ce9-aefe-aa7ea0ce9bbd.vcf 7a6d9132-b2b7-4c73-890b-01c2c213bdda.vcf | bcftools sort -Oz -o 1733.1000.csq.vcf.gz
Removing 2b55550e-1cd8-4ce9-aefe-aa7ea0ce9bbd.vcf
Removing 7a6d9132-b2b7-4c73-890b-01c2c213bdda.vcf

Running command:
set -u pipefail; bcftools index --threads 1 -ft 1733.1000.csq.vcf.gz

Running command:
set -u pipefail; bcftools query -l 1733.1000.csq.vcf.gz

Running command:
set -u pipefail; bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT\t%ANN\t[%AD]\n' 1733.1000.csq.vcf.gz

Running command:
set -u pipefail; bcftools convert --gvcf2vcf -f /usr/local/share/tbprofiler/tbdb.fasta 1733.1000.csq.vcf.gz  | bcftools view -T /usr/local/share/tbprofiler/tbdb.barcode.bed  | bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT[\t%GT\t%AD]\n'

Running command:
set -u pipefail; rm 1733.1000.vcf.gz

Running command:
set -u pipefail; mv -f ./1733.1000*.vcf.gz* ./vcf/
sh-5.0#

**Comment by jodyphelan** [comment]
Which version are you using?

`tb-profiler version`

**Comment by qingbo11** [comment]
It is version 4.0.3

**Comment by qingbo11** [comment]
I used windows docker for the analysis. How to pull the newest version in the dock?

**Comment by jodyphelan** [comment]
I haven't used docker on windows before but you can try running this in the terminal:

```
docker pull quay.io/biocontainers/tb-profiler:4.2.0--pypyh5e36f6f_0
```

**Comment by qingbo11** [comment]
Thank you. Yes, it works now.

**Comment by jodyphelan** [comment]
Great!
