### ISSUE TITLE
Spoligotype error

### ISSUE THREAD

**Issue by ryobon-dev** [jodyphelan/TBProfiler#231]
TBprofiler worked well when I did not include --spoligotype in the command. However, when I included it, I encountered the error, "FileNotFoundError: [Errno 2] No such file or directory: '/home/kansensho/miniconda3/envs/tbprofiler/share/tbprofiler//tbdb.spoligotype_spacers.txt'
Cleaning up after failed run".
It seems like that there isn't tbdb.spoligotype_spacers.txt in the required directory. 

Could you tell me how to install it ?

**Comment by jodyphelan** [comment]
Hi @ryobon-dev ,

Could you try run `tb-profiler updat_tbdb`?

**Comment by ryobon-dev** [comment]
It worked !

Thanks a lot.

By the way, it would be helpful to inform your future developing plan for TBProfiler including Drug resistant list (may be compatible with WHO list) and update phylogenetic SNP barcode (https://pubmed.ncbi.nlm.nih.gov/34787541/).

**Comment by ryobon-dev** [comment]
I am currently using TBprofiler version 4.2.0.
I would like to update the version to the latest one, version 4.3.0.
Is there any command to update the version such as tb-profiler update_tbdb ?

Thanks,

**Comment by jodyphelan** [comment]
Currently it is only poassible with conda/mamba

You can do `mamba install tb-profiler=4.3.0` from your environment

**Comment by ryobon-dev** [comment]
Thanks,
