### ISSUE TITLE
Frameshift in specific region

### ISSUE THREAD

**Issue by mbhall88** [jodyphelan/TBProfiler#235]
When creating a custom database, you can label a gene with the mutation `frameshift` to signify any frameshift causes resistance. Is it possible to add the ability to specify a range? i.e. for the RRDR region I want to say any frameshift between codon 426 and 452?

**Comment by mbhall88** [comment]
Also, if I am reading the code correctly, [you used to allow a `premature_stop` mutation](https://github.com/jodyphelan/tbdb/blob/55bf015f98e74638140d2829b04b878f8f152bbd/parse_db.py#L139-L143), but the latest version of `tb-profiler create_db` no longer supports this?

**Comment by jodyphelan** [comment]
>When creating a custom database, you can label a gene with the mutation frameshift to signify any frameshift causes resistance. Is it possible to add the ability to specify a range? i.e. for the RRDR region I want to say any frameshift between codon 426 and 452?

The ranges is not possible at the moment but I can look into adding this feature.

>Also, if I am reading the code correctly, [you used to allow a premature_stop mutation](https://github.com/jodyphelan/tbdb/blob/55bf015f98e74638140d2829b04b878f8f152bbd/parse_db.py#L139-L143), but the latest version of tb-profiler create_db no longer supports this?

Not sure why the premature_stop was dropped in later versions, looks indeed like it isn't supported anymore. Related to this issue, I'm iworking on [a branch](https://github.com/jodyphelan/pathogen-profiler/pull/17) that standardises the non-hgvs mutations terms using sequence-ontology terms.  This way any SO term used by snpEff could be used https://pcingola.github.io/SnpEff/se_inputoutput/#effect-prediction-details.
