### ISSUE TITLE
adding variant quality

### ISSUE THREAD

**Issue by adimascf** [jodyphelan/TBProfiler#239]
Hello,

Thank you for creating and developing TBProfiler!
Is there a way to add variant quality to the report files? or can we filter out low-quality variants that are also reported in the result files?

Thank you

**Comment by jodyphelan** [comment]
Hi @adimascf 

At the moment the variant quality is not extracted however I can look at adding this into the pipeline.
Currently the only filter that can be applied are the following:
```
  --min_depth MIN_DEPTH
                        Minimum depth required to call variant. Bases with depth below this cutoff will be marked as missing (default: 10)
  --af AF               Minimum allele frequency to call variants (default: 0.1)
  --reporting_af REPORTING_AF
                        Minimum allele frequency to use variants for prediction (default: 0.1)
```

**Comment by adimascf** [comment]
Thank you for taking a look at this.

Yeah, it would be nice if we have variant quality in our result files for assessing the variants.  Otherwise, I think those flags can be helpful as well.
Thank you again @jodyphelan

**Comment by alantsangmb** [comment]
Hello @jodyphelan 
I would like to ask a question regarding the "QC failed variants report" section in the report generated using TBProfiler version 5.0.0. It appears that this section does not exist in version 4.4.0.
What are the criteria for assigning variants to this QC failed section? 
Thank you.

**Comment by jodyphelan** [comment]
Hi @alantsangmb ,

There are a few filtering parameters that are used.

```
Variant Filtering Options:
  --depth DEPTH         Minimum depth hard and soft cutoff specified as comma separated values (default: 0,10)
  --af AF               Minimum allele frequency hard and soft cutoff specified as comma separated values (default: 0,0.1)
  --strand STRAND       Minimum read number per strand hard and soft cutoff specified as comma separated values (default: 0,3)
  --sv_depth SV_DEPTH   Structural variant minimum depth hard and soft cutoff specified as comma separated values (default: 0,10)
  --sv_af SV_AF         Structural variant minimum allele frequency hard cutoff specified as comma separated values (default: 0.5,0.9)
  --sv_len SV_LEN       Structural variant maximum size hard and soft cutoff specified as comma separated values (default: 100000,50000)
```

The first three are for short variants and the last three are for large deletions. For each of these parameters there are two values. For a variant if the value is less than (or greater than for --sv_len) the first cutoff value it is removed from the analysis. If the value is in between the first and second cutoff values it is maked as "soft fail" and removed from the final predictions but kept in the report in the "qc_fail_variants" section. 

For example, the --af flag specifies the minimum allele frequency hard and soft cutoffs. If the default values are set to 0.1 and 0.4 (`--af 0.1,0.4`). This means that, tb-profiler will filter out mutations with a frequency less than 0.4. Any variant with less than 0.1 in frequency will not be analysed. Anything between 0.1 and 0.4 will be kept in the report but will be flagged as a failing the soft cutoff. This allows the user to decide if they want to keep these variants or not. By default, none of these "soft fail" variant make it into the final collated reports and this is why we do not see any mutations with a frequency less than 0.4 in the dataset.

**Comment by alantsangmb** [comment]
Thank you very much for the detailed explanation.

**Comment by alantsangmb** [comment]
Hello @jodyphelan
I have a question about minor variants calling. If I want to report a minor variant with a frequency greater than 10%, does it mean that with the default setting, the total sequencing depth needs to be above 100x, with at least 90x for the major/reference base and at least 10x for the minor/alternative base?

**Comment by jodyphelan** [comment]
The `--af` cutoffs set the frequency of the alternate as a proportion of the depth set in `--depth`. So an alternate allele depth of even 1x will be found if these are considered. However, there is also the `--strand` parameter which will affect the minimum. By default this is set to 3 (per strand) so this means minimum depth cutoff will be 6 as a minimum with all default settings. Some more examples with default values:

| Ref-Forward | Ref-Reverse | Alt-Forward | Alt-Reverse | Depth-QC  | AF-QC     | Strand-QC | Variant QC status |
|-------------|-------------|-------------|-------------|-----------|-----------|-----------|-------------------|
| 10          | 10          | 10          | 3           | Pass      | Pass      | Pass      | Pass              |
| 50          | 50          | 3           | 2           | Pass      | Pass      | Fail      | Soft-Fail         |
| 100         | 100         | 0           | 1           | Pass      | Soft-Fail | Soft-Fail | Soft-Fail         |
| 1           | 0           | 3           | 3           | Soft-Fail | Pass      | Pass      | Soft-Fail         |

**Comment by alantsangmb** [comment]
Thank you so much for the the detailed explanations.
