### ISSUE TITLE
Lineage / sublineage not matching

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#24]
Hello, 

        For sample :  [SRR6356970](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR6356970) the main lineage is reported as:  2.2  and the sublineage at 4.2.1  

         I was expecting the main lineage to be a single number with no decimal and the sublineage to be a further refinement of the main lineage.    Does this look correct to  you?  Thanks!

     Michael

**Comment by harrismia** [comment]
Thanks for looking into this!  Best, 

  Michael

**Comment by jodyphelan** [comment]
Hi Michael,

This issue was related to the sequence data being generated from a mixed population of Mtb strains. It should now be fixed. Please pull the latest commit and let me know if it works for you.

Jody

**Comment by harrismia** [comment]
Thanks Jody! I will test it and let you know. 

 Michael

**Comment by harrismia** [comment]
Hi Jody,   
 Sorry for the delay in getting back to you.   The TBprofiler lineage results for SRR6356970 are:

#### Lineage ####
lineage2.2	0.0593406593407	East-Asian (Beijing)	Beijing-RD207	RD105;RD207
lineage2.2.1	0.0727272727273	East-Asian (Beijing)	Beijing-RD181	RD105;RD207;RD181
lineage4	0.937716262976	Euro-American	LAM;T;S;X;H	None
lineage4.1	0.45652173913	Euro-American	T;X;H	None
lineage4.1.2	0.494623655914	Euro-American (X-type)	T;H	None
lineage4.1.2.1	0.483720930233	Euro-American (X-type)	T1;H1	RD182
lineage4.2	0.513189448441	Euro-American	H;T;LAM	None
lineage4.2.1	0.364864864865	Euro-American (TUR)	H3;H4	None

I am not an expert in lineage classification so I'm not sure if the content is correct  but the results are definitely more detailed and structured.  Just curious what do the numbers next to lineage mean?   For example:  lineage2.2.1	0.0727272727273 .   What does the 0.07272.. mean ?   Thanks! 

Michael

**Comment by harrismia** [comment]
Hi Jody, 

       This makes sense.  It is very useful to have the information about relative abundance. Thanks very much for the explanation!    Best, 

 Michael
