### ISSUE TITLE
are --af and --reporting_af not working?

### ISSUE THREAD

**Issue by adimascf** [jodyphelan/TBProfiler#240]
Hi @jodyphelan 

I am trying to set --af 0.9 and --reporting_af 0.9 to filter out low-quality variants. However, the report file and .vcf file still include variants with an estimated fraction < 0.9. I think those two flags are not working here or am I missing something?

Thank you

### This is my command
`tb-profiler profile -1 trimmed-fastqs/trimmed-sample64_R1.fastq.gz -2 trimmed-fastqs/trimmed-sample64_R2.fastq.gz --no_trim --af 0.9 --reporting_af 0.9 --min_depth 30 --pdf --csv --txt -p sample64`

### This is the result:

TBProfiler report
=================

The following report has been generated by TBProfiler.

Summary
-------
ID,sample64
Date,Thu Sep 15 14:41:22 2022
Strain,lineage2.2.1
Drug-resistance,MDR-TB
Median Depth,107

Lineage report
--------------
Lineage,Estimated Fraction,Spoligotype,Rd
lineage2,0.998,Beijing,RD105
lineage2.2,0.997,Beijing-RD207,RD105;RD207
lineage2.2.1,0.998,Beijing-RD181,RD105;RD207;RD181

Resistance report
-----------------
Drug,Genotypic Resistance,Mutations
Rifampicin,R,rpoB p.Asp435Val (1.00)
Isoniazid,R,fabG1 c.-15C>T (1.00)
Ethambutol,,
Pyrazinamide,,
Streptomycin,,
Fluoroquinolones,,
Moxifloxacin,,
Ofloxacin,,
Levofloxacin,,
Ciprofloxacin,,
Aminoglycosides,,
Amikacin,,
Capreomycin,,
Kanamycin,,
Cycloserine,,
Ethionamide,R,fabG1 c.-15C>T (1.00)
Clofazimine,,
Para-aminosalicylic_acid,,
Delamanid,,
Bedaquiline,,
Linezolid,,

Resistance variants report
-----------------
Genome Position,Locus Tag,Gene,Variant Type,Change,Estimated Fraction,Drug,Annotation
761110,Rv0667,rpoB,missense_variant,p.Asp435Val,1.000,rifampicin,
1673425,Rv1483,fabG1,upstream_gene_variant,c.-15C>T,1.000,isoniazid,ethionamide,

Other variants report
---------------------
Genome Position,Locus Tag,Gene,Variant Type,Change,Estimated Fraction,Annotation
7362,Rv0006,gyrA,missense_variant,p.Glu21Gln,1.000,
7585,Rv0006,gyrA,missense_variant,p.Ser95Thr,1.000,type=phylogenetic_mutation|lineage=lineage4
9304,Rv0006,gyrA,missense_variant,p.Gly668Asp,1.000,
491742,Rv0407,fgd1,synonymous_variant,c.960T>C,1.000,
575907,Rv0486,mshA,missense_variant,p.Ala187Val,1.000,
763031,Rv0668,rpoC,upstream_gene_variant,c.-339T>C,1.000,
764131,Rv0668,rpoC,synonymous_variant,c.762T>C,0.984,
781395,Rv0682,rpsL,upstream_gene_variant,c.-165T>C,1.000,
1471659,EBG00000313325,rrs,upstream_gene_variant,n.-187C>T,1.000,
1673346,Rv1483,fabG1,upstream_gene_variant,c.-94C>G,0.155,
1673349,Rv1483,fabG1,upstream_gene_variant,c.-91G>C,0.162,
1673357,Rv1483,fabG1,upstream_gene_variant,c.-83G>A,0.156,
1673359,Rv1483,fabG1,upstream_gene_variant,c.-81T>C,0.156,
1673361,Rv1483,fabG1,upstream_gene_variant,c.-79C>G,0.156,
1673380,Rv1483,fabG1,upstream_gene_variant,c.-60C>G,0.330,
1834177,Rv1630,rpsA,synonymous_variant,c.636A>C,1.000,
1917972,Rv1694,tlyA,synonymous_variant,c.33A>G,1.000,
2154724,Rv1908c,katG,missense_variant,p.Arg463Leu,1.000,
2155541,Rv1908c,katG,missense_variant,p.Trp191Gly,0.986,
3086788,Rv2780,ald,upstream_gene_variant,c.-32T>C,1.000,
4242643,Rv3794,embA,upstream_gene_variant,c.-590C>T,1.000,
4243460,Rv3794,embA,synonymous_variant,c.228C>T,1.000,
4246544,Rv3795,embB,missense_variant,p.Thr11Pro,0.612,
4246548,Rv3795,embB,missense_variant,p.Pro12Gln,0.786,
4246555,Rv3795,embB,synonymous_variant,c.42G>C,0.811,
4246556,Rv3795,embB,missense_variant,p.Ala15Pro,0.811,
4247015,Rv3795,embB,missense_variant,p.Ser168Ala,0.222,
4407588,Rv3919c,gid,synonymous_variant,c.615A>G,1.000,
4407927,Rv3919c,gid,missense_variant,p.Glu92Asp,1.000,

Coverage report
---------------------
Gene,Locus_Tag,Cutoff,Fraction

Missing positions report
---------------------
Gene,Locus_Tag,Position,Variants,Drugs
ethA,Rv3854c,4328117,c.-1058_968del,c.-693_867del,c.-1242_166del,c.-2501_1459del,ethionamide
ethA,Rv3854c,4328117,c.-1058_968del,c.-693_867del,c.-1242_166del,c.-2501_1459del,ethionamide

Analysis pipeline specifications
--------------------------------
Pipeline version,4.3.0
Database version,tbdb_4738132_Jody Phelan <jody.phelan@lshtm.ac.uk>_Thu Jul 21 16:19:40 2022 +0100
Analysis,Program
Mapping,trimmed-fastqs/trimmed-sample64_R1.fastq.gz
Variant calling,freebayes

Citation
--------
Coll, F. et al. Rapid determination of anti-tuberculosis drug resistance from
whole-genome sequences. Genome Medicine 7, 51. 2015

Phelan, JE. et al. Integrating informatics tools and portable sequencing 
technology for rapid detection of resistance to anti-tuberculous drugs. 
Genome Medicine 11, 41. 2019

**Comment by jodyphelan** [comment]
Hi @adimascf,

It looks like you have found a bug as the filters are not working for me either. I'll try to put a fix in tomorrow.

**Comment by adimascf** [comment]
Yea, I think so. Thank you for taking a close look at this, @jodyphelan

**Comment by adimascf** [comment]
Ah great! It works very well. Thank you @jodyphelan
