### ISSUE TITLE
specific samples consistently fail in TBprofiler version 4.3.0

### ISSUE THREAD

**Issue by jeffreybm** [jodyphelan/TBProfiler#246]
Hi @jodyphelan,

We have a couple samples that consistently fail to process when using latest TBprofiler version 4.3.0, but will process using 4.2.0.  If you would like to test a sample that fails the SRA id is SRR5153594

Looks like failing a bcftools query call on the *.delly.csq.vcf.gz files.  I ran using both pilon and freebayes as caller.  I have attached the error log for both runs.  Thanks for the help!

[SRR5153594_freebayes.log](https://github.com/jodyphelan/TBProfiler/files/9678060/SRR5153594_freebayes.log)
[SRR5153594_pilon.log](https://github.com/jodyphelan/TBProfiler/files/9678061/SRR5153594_pilon.log)

Cheers,

Brendan

**Comment by jodyphelan** [comment]
Hi @jeffreybm,

This is quite a cryptic error message that is similar to #233. It seems as though the latest version of [tbdb](https://github.com/jodyphelan/tbdb) has multiple annotations for the same variant (fabG1 c.-17G>T and inhA c.-779G>T).  This variant is present in the example sample and the pipeline quits with an error. Previously I've required only one annotation per variant but this is a bit limiting to I've put in a fix that allows for multiple annotations per variant. Will put out a new release over the weekend with this included.
