### ISSUE TITLE
tb-profiler conda/java issue

### ISSUE THREAD

**Issue by jloubser** [jodyphelan/TBProfiler#251]
Hi Jody,

This might be a very environmental-specific/conda-specific problem, so please ignore if irrelevant.
I work on a shared server that has older conda installed. Due to the slow speed I decided to get miniconda3, create and kee my own base updated and I do everything with mamba. The problem is that when I create a new environment for tb-profiler and use the environment-specific.yaml file you provided last time it installs an internal build openjdk. Tb-profiler doesn't work well with that. I get either errlog outputs or completely wrong lineage/drug-resistance outputs and the median coverage for isolates is terrible. 
Only way it worked is after I remove the "openjdk" line in the file you sent me and then create the environment. Then it uses the globally installed openjdk in the tb-profiler environment. I don't know if it's fixable? And after every update I would need to get a new tb-profiler_v4##.env.spec-file.txt from you.

**Comment by jodyphelan** [comment]
Thanks for letting me know! I'm not quite sure why that would be happening. I've created a new conda specifications file [here](https://github.com/jodyphelan/TBProfiler/blob/master/conda/linux-latest.txt), would you mind trying and letting me know if that has the same issue?

**Comment by jloubser** [comment]
Works perfectly, thank you!
