### ISSUE TITLE
tb-profiler vulnerability issues

### ISSUE THREAD

**Issue by yujun2017** [jodyphelan/TBProfiler#253]
Jody:
     We are using tb-profiler in our application long time ago. Recently when we upgrade tb-profiler to latest version, we do notice tb-profiler can't pass our security scan. The issue come from the snpeff.jar file. Our security scanner report over 60 vulnerabilities for this jar file. Before we fixed vulnerability issue, we can't use new tb-profiler version. 
     I am wondering if you have plan to get rid of this jar file or do you have any suggestion for this vulnerability issue?

Thanks!

John Yu

**Comment by jodyphelan** [comment]
Hi @dbtara , thanks for looking into it, I'm slightly confused as log4j still gets flagged in https://quay.io/repository/biocontainers/tb-profiler/manifest/sha256:39572645f2b8519b1ef5100a3ca0d7249ce1910f6d9870c27b8b092564df1e7e?tab=vulnerabilities
