### ISSUE TITLE
Don't know how to handle this mutation: ethA c.-1_1insA

### ISSUE THREAD

**Issue by huihuigogo** [jodyphelan/TBProfiler#258]
Hi @jodyphelan 

On TBprofiler version 4.3.0, when I created a custom database, the following errors occurred. It seems that the software cannot recognize similar point mutations. I want to ask what the reason is. Could you please let me know how I can fix the issue? There are also similar unrecognized mutations (ethA c.-1_1insA). 

(TBprofiler2) [huihuigogo@gsubmit0 tbdb-master]$ tb-profiler create_db --custom --include_original_mutation
Don't know how to handle this mutation: pncA c.7G>C

Thanks for the help!

**Comment by huihuigogo** [comment]
Thanks for your reply！@jodyphelan
“The mutations are parsed by tb-profiler and it looks like parser hasn't been written for mutations like ethA c.-1_1insA yet in the code. I'll put that in before the next version.” I am looking forward to the update.

I still have some questions about why TBprofiler can not handle pncA c.7G>C mutation. I think pncA c.7G>C is not a synonymous mutation, that is, the base mutation will cause changes in amino acids (p.Ala3Pro). Do you mean that p.Ala3Pro already exists in the DB, so it is not necessary to include pncA c.7G>C in the database?

**Comment by jodyphelan** [comment]
Hi @huihuigogo,

Ah right, I was assuming that people would use the protein level change if it was non-synonymous. I'll add the ability to specify mutations in the form of c.7G>C too

**Comment by huihuigogo** [comment]
@jodyphelan I see. Thanks for your answer.

**Comment by jodyphelan** [comment]
This should now be possible and will be included in the next release
