### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#26]
A new feature for consideration:

Could you add an option to have tb-profiler run in verbose mode where output would be printed to stdout or to a log file?  It would be nice if the program could at least print a message with the command line used to initiate the run including the names of the input files and a success or failure message at the end with the  elapsed time between start and finish.    

Perhaps the log file could be called    <prefix>.log  where prefix is the prefix specified on the command line.   

Other information could also be reported with timing information like when each of the components are initiated and finish:  bwa, lowfreq etc.  

 Thanks!

       Michael

**Comment by harrismia** [comment]
Hi Jody, 

       Thanks, and sorry I missed that.     --verbose 1  is pretty much what I was looking for.   Best, 

Michael

**Comment by jodyphelan** [comment]
Brilliant!
