### ISSUE TITLE
use spoligotype and snp_dist after run tb-profile

### ISSUE THREAD

**Issue by Leobpfbac** [jodyphelan/TBProfiler#262]
I ran tb-profile on my samples and everything worked fine, but now I don't know how to run --snp_dist. It asks me for arguments.
Any advice?

**Comment by jodyphelan** [comment]
The argument to `--snp_dist` is an integer which is used to store relationships between samples in the report. For example if we use `--snp_dist 20` it will find all samples that are within 20 snps from the sample that is being profiled.

**Comment by Leobpfbac** [comment]
Worked, 
Thanks Jody.

**Comment by jodyphelan** [comment]
Great!
