### ISSUE TITLE
The online analysis website of TBProfiler software crashed.

### ISSUE THREAD

**Issue by chen-1911-175** [jodyphelan/TBProfiler#267]
The online analysis website of TBProfiler software crashed. Whether it is to query the analysis results before or upload the new file analysis, it will display "Internal Server Error: The server accounted for an internal error and was unable to complete your request. Neither the server is overloaded or there is an error in the application". why does this happen?

**Comment by jodyphelan** [comment]
Hi @chen-1911-175 

Thanks for reporting that. There was an issue with the server which has now been fixed. It will try to retart all the jobs that were pending. I'll write here again when this is finished.

**Comment by chen-1911-175** [comment]
Thanks, I have finished the analysis and prediction.

**Comment by chen-1911-175** [comment]
Thanks, I have finished the analysis and prediction.

**Comment by jodyphelan** [comment]
Great!
