### ISSUE TITLE
File not found when running `tb-profiler update_tbdb --match_ref`

### ISSUE THREAD

**Issue by aofarrel** [jodyphelan/TBProfiler#278]
Version: staphb/tbprofiler:4.4.2 docker image 

I'm hoping to run tb_profiler on some bams, but ran into an error [similar to this one](https://github.com/jodyphelan/TBProfiler/issues/196#issuecomment-1039722540). My fasta file starts with `>NC_000962.3` so I figured I need to run `tb-profiler update_tbdb --match_ref`, but I can't seem to get that working. Seems like it cannot find the fasta file I'm passing into it?

```
> ls -lha
drwxr-xr-x  1 root root 4.0K Mar 28 22:03 ..
drwxr-xr-x 14 root root  448 Mar 28 02:24 .git
-rw-r--r--  1 root root   66 Mar 24 01:07 .gitattributes
-rw-r--r--  1 root root  332 Mar 28 21:56 Dockerfile
-rw-r--r--  1 root root  451 Mar 26 20:14 tb_profiler.wdl
-rw-r--r--  1 root root 4.3M Mar 28 22:04 tb_seq.fasta
-rw-r--r--  1 root root   12 Mar 28 22:11 tb_seq.fasta.amb
-rw-r--r--  1 root root   46 Mar 28 22:11 tb_seq.fasta.ann
-rw-r--r--  1 root root 4.3M Mar 28 22:11 tb_seq.fasta.bwt
-rw-r--r--  1 root root   29 Mar 28 22:11 tb_seq.fasta.fai
-rw-r--r--  1 root root 1.1M Mar 28 22:11 tb_seq.fasta.pac
-rw-r--r--  1 root root 2.2M Mar 28 22:11 tb_seq.fasta.sa
```
.git, .gitattributes, Dockerfile, and tb_profiler.wdl are my own files from my own repo.

```
> tb-profiler update_tbdb --match_ref tb_seq.fasta
Running command:
set -u pipefail; git clone https://github.com/jodyphelan/tbdb.git

Running command:
set -u pipefail; git checkout master

Running command:
set -u pipefail; git pull

Running command:
set -u pipefail; tb-profiler create_db --prefix tbdb --match_ref tb_seq.fasta --load
Traceback (most recent call last):
  File "/opt/conda/bin/tb-profiler", line 693, in <module>
    args.func(args)
  File "/opt/conda/bin/tb-profiler", line 212, in main_update_tbdb
    pp.run_cmd(f"tb-profiler create_db --prefix {args.prefix} {tmp} --load")
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 404, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; tb-profiler create_db --prefix tbdb --match_ref tb_seq.fasta --load
stderr:
Traceback (most recent call last):
  File "/opt/conda/bin/tb-profiler", line 693, in <module>
    args.func(args)
  File "/opt/conda/bin/tb-profiler", line 232, in main_create_db
    pp.create_db(args,extra_files=extra_files)
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/db.py", line 584, in create_db
    chrom_conversion = match_ref_chrom_names(args.match_ref,"genome.fasta")
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/db.py", line 549, in match_ref_chrom_names
    source_fa = fa2dict(source)
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/db.py", line 63, in fa2dict
    for l in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'tb_seq.fasta'
Cleaning up after failed run
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/bin/tb-profiler", line 33, in cleanup
    del args.conf['json_db']
AttributeError: 'Namespace' object has no attribute 'conf'

Cleaning up after failed run
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/bin/tb-profiler", line 33, in cleanup
    del args.conf['json_db']
AttributeError: 'Namespace' object has no attribute 'conf'
```

[The samtools and bwa commands mentioned here](https://github.com/jodyphelan/TBProfiler/issues/196#issuecomment-1041408789) work, so this isn't a matter of the file not being mounted into the Docker image, but `tb-profiler update_tbdb --match_ref` is still not working. Different iterations like `./tb_seq.fasta` or `$(pwd)/tb_seq.fasta` don't seem to be working. Am I missing a step? Does my fasta need to go somewhere specific?

**Comment by jodyphelan** [comment]
Hi Ash,

This is a bug in that version. It is fixed in the master branch, I just need to make a conda release. After running the command and seeing the error, it should have clones a git repo called tbdb. What you should do is to go into that directory and manually run the create_db step:

```
cd tbdb
tb-profiler create_db --prefix tbdb --match_ref tb_seq.fasta --load
```

Let me know if that works for you.

**Comment by aofarrel** [comment]
I think there might still be a mismatch somewhere. After running that, when trying to run on a bam file, this is the error I get. (If I'm not using tb_profiler, I can samtools index the bam just fine to get a bai file.)

> [94mUsing ref file: /opt/conda/share/tbprofiler//tbdb.fasta[0m
> [94mUsing gff file: /opt/conda/share/tbprofiler//tbdb.gff[0m
> [94mUsing bed file: /opt/conda/share/tbprofiler//tbdb.bed[0m
> [94mUsing version file: /opt/conda/share/tbprofiler//tbdb.version.json[0m
> [94mUsing json_db file: /opt/conda/share/tbprofiler//tbdb.dr.json[0m
> [94mUsing variables file: /opt/conda/share/tbprofiler//tbdb.variables.json[0m
> [94mUsing spoligotype_spacers file: /opt/conda/share/tbprofiler//tbdb.spoligotype_spacers.txt[0m
> [94mUsing spoligotype_annotations file: /opt/conda/share/tbprofiler//tbdb.spoligotype_list.csv[0m
> [94mUsing bedmask file: /opt/conda/share/tbprofiler//tbdb.mask.bed[0m
> [94mUsing barcode file: /opt/conda/share/tbprofiler//tbdb.barcode.bed[0m
> [94mUsing /mnt/miniwdl_task_container/work/_miniwdl_inputs/0/SAMEA10029918_to_Ref.H37Rv.bam
> 
> Please ensure that this BAM was made using the same reference as in the database.
> If you are not sure what reference was used it is best to remap the reads.[0m
> 
> Running command:
> set -u pipefail; samtools index -@ 1 /mnt/miniwdl_task_container/work/_miniwdl_inputs/0/SAMEA10029918_to_Ref.H37Rv.bam
> Traceback (most recent call last):
>   File "/opt/conda/bin/tb-profiler", line 693, in <module>
>     args.func(args)
>   File "/opt/conda/bin/tb-profiler", line 152, in main_profile
>     results.update(pp.run_profiler(args))
>   File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 37, in run_profiler
>     results = bam_profiler(
>   File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/profiler.py", line 25, in bam_profiler
>     bam_obj = bam(bam_file, prefix, platform=platform, threads=threads)
>   File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/bam.py", line 18, in __init__
>     index_bam(bam_file,threads=threads)
>   File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 421, in index_bam
>     run_cmd(cmd)
>   File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 404, in run_cmd
>     raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
> ValueError: Command Failed:
> set -u pipefail; samtools index -@ 1 /mnt/miniwdl_task_container/work/_miniwdl_inputs/0/SAMEA10029918_to_Ref.H37Rv.bam
> stderr:
> samtools index: "/mnt/miniwdl_task_container/work/_miniwdl_inputs/0/SAMEA10029918_to_Ref.H37Rv.bam" is in a format that cannot be usefully indexed
>

**Comment by jodyphelan** [comment]
Great to hear it is working now!
