### ISSUE TITLE
Intermediate files not written to the directory specified with the -d option

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#28]
Some of the intermediate files are not stored to the directory specified using the -d option.  We are running tb-profiler from a web application so we can not write files to the ./ directory.

the .depth file and the and some of intermediate files from the last command are not being written to the directory specified using the -d option.    

Below is output from a run:  

 /usr/local/share/TBProfiler/tb-profiler profile --verbose 1  -1 SRR5486866_1_subseq100K.fastq.gz -2 SRR5486866_2_subseq100k.fastq.gz -d /var/genomics/Output/Prediction/ -p b3672194-912a-4cbb-be65-561e845eb4ef
 
Running command:
/usr/local/share/TBProfiler/bin/bwa mem -R '@RG\tID:b3672194-912a-4cbb-be65-561e845eb4ef\tSM:b3672194-912a-4cbb-be65-561e845eb4ef\tPL:Illumina' -t 1 /usr/local/share/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa SRR5486866_1_subseq100K.fastq.gz SRR5486866_2_subseq100k.fastq.gz | /usr/local/share/TBProfiler/bin/samtools view -b -@ 1 - | /usr/local/share/TBProfiler/bin/samtools sort -@ 1 -o /var/genomics/Output/Prediction//bam/b3672194-912a-4cbb-be65-561e845eb4ef.bam -
 
Running command:
/usr/local/share/TBProfiler/bin/samtools depth -b /usr/local/share/TBProfiler/db/drdb.bed /var/genomics/Output/Prediction//bam/b3672194-912a-4cbb-be65-561e845eb4ef.bam > b3672194-912a-4cbb-be65-561e845eb4ef.depth
 
Running command:
set -euf pipefail; /usr/local/share/TBProfiler/bin/samtools view -bL /usr/local/share/TBProfiler/db/drdb.bed /var/genomics/Output/Prediction//bam/b3672194-912a-4cbb-be65-561e845eb4ef.bam | /usr/local/share/TBProfiler/bin/lofreq indelqual -u 30 - |/usr/local/share/TBProfiler/bin/lofreq call -f /usr/local/share/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa --call-indels --no-default-filter - | bcftools view -i 'AF>0.9' | /usr/local/share/TBProfiler/bin/bcftools norm -f /usr/local/share/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa - | /usr/local/share/TBProfiler/bin/bcftools csq -f /usr/local/share/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa -g /usr/local/share/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.gff - > /var/genomics/Output/Prediction//vcf/b3672194-912a-4cbb-be65-561e845eb4ef.dr.vcf
 
Running command:
/usr/local/share/TBProfiler/bin/samtools view -@ 1 -bL /usr/local/share/TBProfiler/db/lineages.bed /var/genomics/Output/Prediction//bam/b3672194-912a-4cbb-be65-561e845eb4ef.bam  > b3672194-912a-4cbb-be65-561e845eb4ef.temp.bam && /usr/local/share/TBProfiler/bin/htsbox pileup -f /usr/local/share/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa -Q 8 b3672194-912a-4cbb-be65-561e845eb4ef.temp.bam > b3672194-912a-4cbb-be65-561e845eb4ef.temp.pileup

**Comment by jodyphelan** [comment]
This issue should now be fixed. Please pull the latest commit and let me know if it works as expected.

Jody
