### ISSUE TITLE
Could not read Raw - error

### ISSUE THREAD

**Issue by brsaran** [jodyphelan/TBProfiler#281]
Hi i installed tb-profiler using mamba and run the following command I got the error (attached)
tb-profiler profile -1 S6657_DKDL220001375-1a_H37V5DSX3_L4_1.fq.gz -2 S6657_DKDL220001375-1a_H37V5DSX3_L4_2.fq.gz -t 10 --spoligotype

sing ref file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta
Using gff file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.gff
Using bed file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.bed
Using version file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.version.json
Using json_db file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.dr.json
Using variables file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.variables.json
Using spoligotype_spacers file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.spoligotype_spacers.txt
Using spoligotype_annotations file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.spoligotype_list.csv
Using bedmask file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.mask.bed
Using barcode file: /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.barcode.bed

Running command:
set -u pipefail; trimmomatic PE -threads 10 -phred33 S6657_DKDL220001375-1a_H37V5DSX3_L4_1.fq.gz S6657_DKDL220001375-1a_H37V5DSX3_L4_2.fq.gz -baseout ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36

Running command:
set -u pipefail; cat ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_1U ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_2U > ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_TU

Running command:
set -u pipefail; rm ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_1U ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_2U

Running command:
set -u pipefail; bwa mem -t 10 -K 10000000 -c 100 -R '@RG\tID:tbprofiler\tSM:tbprofiler\tPL:illumina' -M -T 50 /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_1P ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_2P | samtools sort -@ 10 -o ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.pair.bam -

Running command:
set -u pipefail; bwa mem -t 10 -K 10000000 -c 100 -R '@RG\tID:tbprofiler\tSM:tbprofiler\tPL:illumina' -M -T 50 /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c_TU | samtools sort -@ 10 -o ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.single.bam -

Running command:
set -u pipefail; samtools merge -@ 10 -f ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.unsort.bam ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.pair.bam ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.single.bam

Running command:
set -u pipefail; samtools sort -m 768M -n -@ 10  ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.unsort.bam | samtools fixmate -@ 10 -m - - | samtools sort -m 768M -@ 10 - | samtools markdup -@ 10 - ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.bam

Running command:
set -u pipefail; rm ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.single.bam ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.pair.bam ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.unsort.bam

Running command:
set -u pipefail; samtools index -@ 10 ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.bam
Using ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.bam

Please ensure that this BAM was made using the same reference as in the database.
If you are not sure what reference was used it is best to remap the reads.

Running command:
set -u pipefail; cat /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 10 --col-sep " " "samtools view -T /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta -h ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.bam {1} | samclip --ref /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta | samtools view -b > ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.{2}.tmp.bam && samtools index ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.{2}.tmp.bam && freebayes -f /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta -r {1} --haplotype-length -1  ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.{2}.tmp.bam | bcftools view -c 1 | bcftools norm -f /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta | bcftools filter -t {1} -e 'FMT/DP<10' -S . -Oz -o ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.{2}.vcf.gz"

Running command:
set -u pipefail; cat /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 10 --col-sep " " "bcftools index  ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.{2}.vcf.gz"

Running command:
set -u pipefail; bcftools concat -aD `cat /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | awk '{print "./a2ebcc6d-bab3-4aa9-8918-9718c726a00c."$2".vcf.gz"}'` | bcftools view -Oz -o ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.targets.vcf.gz

Running command:
set -u pipefail; rm `cat /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | awk '{print "./a2ebcc6d-bab3-4aa9-8918-9718c726a00c."$2".vcf.gz*"}'`

Running command:
set -u pipefail; rm `cat /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | awk '{print "./a2ebcc6d-bab3-4aa9-8918-9718c726a00c."$2".tmp.bam*"}'`

Running command:
set -u pipefail; bcftools index --threads 1 -ft ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.targets.vcf.gz

Running command:
set -u pipefail; bcftools query -l ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.targets.vcf.gz

Running command:
set -u pipefail; bcftools view -c 1 -a ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.targets.vcf.gz | bcftools norm -m - | bcftools view -v snps | combine_vcf_variants.py --ref /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta --gff /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.gff |  snpEff ann -dataDir /home/user/mambaforge/envs/tb-profiler/share/snpeff-5.1-2/data -noLog -noStats Mycobacterium_tuberculosis_h37rv -  | bcftools sort -Oz -o /home/user/Documents/work/saran/Kamal_TBWork/Sequencing Raw Data/TBProfiler/eff95597-c1d9-4bc0-9bf0-53268a456286.vcf.gz && bcftools index /home/user/Documents/work/saran/Kamal_TBWork/Sequencing Raw Data/TBProfiler/eff95597-c1d9-4bc0-9bf0-53268a456286.vcf.gz
Traceback (most recent call last):
  File "/home/user/mambaforge/envs/tb-profiler/bin/tb-profiler", line 693, in <module>
    args.func(args)
  File "/home/user/mambaforge/envs/tb-profiler/bin/tb-profiler", line 152, in main_profile
    results.update(pp.run_profiler(args))
  File "/home/user/mambaforge/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 37, in run_profiler
    results = bam_profiler(
  File "/home/user/mambaforge/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/profiler.py", line 34, in bam_profiler
    ann_vcf_obj = vcf_obj.run_snpeff(conf["snpEff_db"],conf["ref"],conf["gff"],rename_chroms= conf.get("chromosome_conversion",None))
  File "/home/user/mambaforge/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/vcf.py", line 92, in run_snpeff
    run_cmd("bcftools view -c 1 -a %(filename)s | bcftools norm -m - | bcftools view -v snps | combine_vcf_variants.py --ref %(ref_file)s --gff %(gff_file)s | %(rename_cmd)s snpEff ann %(snpeff_data_dir_opt)s -noLog -noStats %(db)s - %(re_rename_cmd)s | bcftools sort -Oz -o %(tmp_file1)s && bcftools index %(tmp_file1)s" % vars(self))
  File "/home/user/mambaforge/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 404, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; bcftools view -c 1 -a ./a2ebcc6d-bab3-4aa9-8918-9718c726a00c.targets.vcf.gz | bcftools norm -m - | bcftools view -v snps | combine_vcf_variants.py --ref /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.fasta --gff /home/user/mambaforge/envs/tb-profiler/share/tbprofiler//tbdb.gff |  snpEff ann -dataDir /home/user/mambaforge/envs/tb-profiler/share/snpeff-5.1-2/data -noLog -noStats Mycobacterium_tuberculosis_h37rv -  | bcftools sort -Oz -o /home/user/Documents/work/saran/Kamal_TBWork/Sequencing Raw Data/TBProfiler/eff95597-c1d9-4bc0-9bf0-53268a456286.vcf.gz && bcftools index /home/user/Documents/work/saran/Kamal_TBWork/Sequencing Raw Data/TBProfiler/eff95597-c1d9-4bc0-9bf0-53268a456286.vcf.gz
stderr:
Writing to /tmp/bcftools-sort.Vplg69
[E::hts_open_format] Failed to open file "Raw" : No such file or directory
Could not read Raw
Cleaning
Lines   total/split/realigned/skipped:	47/1/0/0

Cleaning up after failed run

################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the
contents of the error log (tbprofiler.errlog.txt)

###############################################################################
[tbprofiler.errlog.txt](https://github.com/jodyphelan/TBProfiler/files/11168938/tbprofiler.errlog.txt)

**Comment by brsaran** [comment]
Issue resolved. Actually there was space in the folder name (Sequence Raw Data), because of which the input file is not detected.

**Comment by jodyphelan** [comment]
Glat to hear you resolved the issue.
