### ISSUE TITLE
mutations on WHO list

### ISSUE THREAD

**Issue by ryobon-dev** [jodyphelan/TBProfiler#283]
I was informed that all mutations on the WHO list have been included (together with many others) in the [master branch](https://github.com/jodyphelan/tbdb/tree/master) of the tbdb repo. Additionally the [who branch](https://github.com/jodyphelan/tbdb/tree/who) contains only those in WHO list.

Does this mean both current commandline version and web version use the master branch (WHO list together with many others) as a default setting ?

Thanks,

**Comment by ryobon-dev** [comment]
Sorry, I had already got response from you on this as shown in below.

The default list contains a combination of the WHO catalogue and the original tb-profiler list. There is also another branch containing only the WHO catalogue available at https://github.com/jodyphelan/tbdb/blob/who/tbdb.csv.

**Comment by jodyphelan** [comment]
Hi @ryobon-dev ,

Sorry for the delay in getting back to you. Yes the commandline and web versions use the default (master) branch of tbdb as this has slightly better sensitivity than just the WHO mutations.

Let me know if you have any other questions.
