### ISSUE TITLE
error: argument --snp_dist: expected one argument

### ISSUE THREAD

**Issue by ryobon-dev** [jodyphelan/TBProfiler#290]
Hi, 

I tried to run --snp_dist but encountered the error in below.

Could you help me to resolve this issue ?

(tb-profiler) kansensho@MAC:/mnt/d/RIT_fastq_20221213_MTBseq$ tb-profiler version

TBProfiler version 4.4.2
(tb-profiler) kansensho@MAC:/mnt/d/RIT_fastq_20221213_MTBseq$ tb-profiler profile -1 FY27KIH243_S11_R1.fastq.gz -2 FY27KIH243_S11_R2.fastq.gz -t 16 -p FY27KIH243 --txt --spoligotype --call_whole_genome --snp_dist
usage: tb-profiler profile [-h] [--read1 READ1] [--read2 READ2] [--bam BAM] [--fasta FASTA] [--vcf VCF]
                           [--platform {illumina,nanopore,pacbio}] [--db DB] [--external_db EXTERNAL_DB]
                           [--prefix PREFIX] [--csv] [--txt] [--pdf] [--docx DOCX] [--output_template OUTPUT_TEMPLATE]
                           [--add_columns ADD_COLUMNS] [--dir DIR] [--mapper {bwa,minimap2,bowtie2,bwa-mem2}]
                           [--caller {bcftools,gatk,freebayes,pilon,lofreq}] [--calling_params CALLING_PARAMS]
                           [--kmer_counter {kmc,dsk}] [--min_depth MIN_DEPTH] [--af AF] [--reporting_af REPORTING_AF]
                           [--coverage_fraction_threshold COVERAGE_FRACTION_THRESHOLD]
                           [--missing_cov_threshold MISSING_COV_THRESHOLD] [--suspect] [--spoligotype]
                           [--call_whole_genome] [--snp_dist SNP_DIST] [--no_trim] [--no_flagstat] [--no_clip]
                           [--no_delly] [--threads THREADS] [--ram RAM] [--verbose {0,1,2}] [--temp TEMP] [--version]
tb-profiler profile: error: argument --snp_dist: expected one argument
(tb-profiler) kansensho@MAC:/mnt/d/RIT_fastq_20221213_MTBseq$

**Comment by jodyphelan** [comment]
Hi @ryobon-dev ,

The `--snp_dist` flag expects a integer argument. For example `--snp_dist 20`. This will then store all distances <= 20 between pairs of samples.

**Comment by ryobon-dev** [comment]
Thanks for your quick response.

 

I still have a problem on this. I have attached the error log.

 

Thanks,

**Comment by ryobon-dev** [comment]
Hi,

With your comment, I run the command " tb-profiler profile -1 FY27KIH243_S11_R1.fastq.gz -2 FY27KIH243_S11_R2.fastq.gz -t 16 -p FY27KIH243 --txt --snp_dist 20". 

Everything about snp_dist is fine now ! Thanks for your great support.
