### ISSUE TITLE
Can tbprofiler be analysis amplicon data

### ISSUE THREAD

**Issue by zhiliangfu** [jodyphelan/TBProfiler#296]
Hi:
   
  Tbprofiler is so helpful for me. It's a great tool！

   TBprofiler can analysis WGS data. what about amplicon data?  can i use tbprofiler to analysis my amplicon tb data?

Thank you!

**Comment by jodyphelan** [comment]
Hi @zhiliangfu 

Yes it does - you need to first create a specific database that only contains your amplicon regions. When running `create_db` you should add your primers using `--amplicon_primers primer_file` where primer_file is a three column file with the amplicon name is the first column and the the second and third columns are the forward and reverse primers.

**Comment by zhiliangfu** [comment]
@jodyphelan Thanks for your reply !
