### ISSUE TITLE
"Command failed! Please check!"

### ISSUE THREAD

**Issue by ChrisBea** [jodyphelan/TBProfiler#30]
Hello Jody, 

I hope you are well. I tried running the example data, but I seem to have gotten this error:
"Command Failed! Please Check!"

I used -v2 to get a better idea of what's going on but wasn't able to figure it out. Any help or guidance you may have to provide would be greatly appreciated. 

$ ../tb-profiler profile -1 ERR1664619_1.fastq.gz -t 4 -v2 -p ERR1664619

Here is the output from the command above (also attached as a logfile if that helps)

"
Running command:
/home/chris/software/tbprofiler/TBProfiler/bin/bwa mem -R '@RG\tID:ERR1664619\tSM:ERR1664619\tPL:Illumina' -t 4 /home/chris/software/tbprofiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa ERR1664619_1.fastq.gz | /home/chris/software/tbprofiler/TBProfiler/bin/samtools view -b -@ 4 - | /home/chris/software/tbprofiler/TBProfiler/bin/samtools sort -@ 4 -o ./bam/ERR1664619.bam -
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 136110 sequences (40000213 bp)...
[M::process] read 135732 sequences (40000283 bp)...
[M::mem_process_seqs] Processed 136110 reads in 14.564 CPU sec, 3.497 real sec
[M::process] read 135994 sequences (40000170 bp)...
[M::mem_process_seqs] Processed 135732 reads in 17.460 CPU sec, 4.318 real sec
[M::process] read 43508 sequences (12804620 bp)...
[M::mem_process_seqs] Processed 135994 reads in 16.328 CPU sec, 4.032 real sec
[M::mem_process_seqs] Processed 43508 reads in 7.004 CPU sec, 1.756 real sec
[main] Version: 0.7.15-r1142-dirty
[main] CMD: /home/chris/software/tbprofiler/TBProfiler/bin/bwa mem -R @RG\tID:ERR1664619\tSM:ERR1664619\tPL:Illumina -t 4 /home/chris/software/tbprofiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa ERR1664619_1.fastq.gz
[main] Real time: 14.351 sec; CPU: 55.884 sec
[bam_sort_core] merging from 0 files and 4 in-memory blocks...

Running command:
/home/chris/software/tbprofiler/TBProfiler/bin/samtools depth -b /home/chris/software/tbprofiler/TBProfiler/db/drdb.bed ./bam/ERR1664619.bam > ./ERR1664619.depth

Running command:
set -euf pipefail; /home/chris/software/tbprofiler/TBProfiler/bin/samtools view -bL /home/chris/software/tbprofiler/TBProfiler/db/drdb.bed ./bam/ERR1664619.bam | /home/chris/software/tbprofiler/TBProfiler/bin/lofreq indelqual -u 30 - |/home/chris/software/tbprofiler/TBProfiler/bin/lofreq call -f /home/chris/software/tbprofiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa --call-indels --no-default-filter - | bcftools view -i 'AF>0.9' | /home/chris/software/tbprofiler/TBProfiler/bin/bcftools norm -f /home/chris/software/tbprofiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa - | /home/chris/software/tbprofiler/TBProfiler/bin/bcftools csq -f /home/chris/software/tbprofiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa -g /home/chris/software/tbprofiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.gff - > ./vcf/ERR1664619.dr.vcf

Usage: bcftools view [options] <in.bcf> [reg]

Input/output options:

       -A        keep all possible alternate alleles at variant sites
       -b        output BCF instead of VCF
       -D FILE   sequence dictionary for VCF->BCF conversion [null]
       -F        PL generated by r921 or before (which generate old ordering)
       -G        suppress all individual genotype information
       -l FILE   list of sites (chr pos) or regions (BED) to output [all sites]
       -L        calculate LD for adjacent sites
       -N        skip sites where REF is not A/C/G/T
       -Q        output the QCALL likelihood format
       -s FILE   list of samples to use [all samples]
       -S        input is VCF
       -u        uncompressed BCF output (force -b)

Consensus/variant calling options:

       -c        SNP calling (force -e)
       -d FLOAT  skip loci where less than FLOAT fraction of samples covered [0]
       -e        likelihood based analyses
       -g        call genotypes at variant sites (force -c)
       -i FLOAT  indel-to-substitution ratio [0]
       -I        skip indels
       -m FLOAT  alternative model for multiallelic and rare-variant calling, include if P(chi^2)>=FLOAT
       -p FLOAT  variant if P(ref|D)<FLOAT [0.5]
       -P STR    type of prior: full, cond2, flat [full]
       -t FLOAT  scaled substitution mutation rate [0.001]
       -T STR    constrained calling; STR can be: pair, trioauto, trioxd and trioxs (see manual) [null]
       -v        output potential variant sites only (force -c)

Contrast calling and association test options:

       -1 INT    number of group-1 samples [0]
       -C FLOAT  posterior constrast for LRT<FLOAT and P(ref|D)<0.5 [1]
       -U INT    number of permutations for association testing (effective with -1) [0]
       -X FLOAT  only perform permutations for P(chi^2)<FLOAT [0.01]

Failed to open -: unknown file type
Failed to open -: unknown file type
Number of substitution tests performed: 23514
Number of indel tests performed: 29
Command Failed! Please Check!
"

Again, I would be grateful for any guidance or tips. Thank you for your time and consideration.

Best,
Chris

[tbprofiler.logfile.txt](https://github.com/jodyphelan/TBProfiler/files/2680249/tbprofiler.logfile.txt)

**Comment by jodyphelan** [comment]
Hi Chris,

The issue was related to a call to the default bcftools on the system which fails when older verions of bcftools are used. This issue should now be fixed. Please pull the latest commit and let me know if it works.

Jody

**Comment by ChrisBea** [comment]
Hey Jody,

Thanks for the quick reply. It works on the example perfectly now. Just wondering, is there a setting to use whole genome assemblies with tbprofiler, or would the database be accessible to map the lineage and resistance markers onto the genomes? Any information would be greatly appreciated. Thank you for your time.

Chris

**Comment by jodyphelan** [comment]
Hi Chris,

There is currently no setting for whole genome assemblies but the the database is available [here](https://github.com/jodyphelan/TBProfiler/blob/master/db/lineages.bed).
