### ISSUE TITLE
How can I fix about command failed?

### ISSUE THREAD

**Issue by NonthakornSkw** [jodyphelan/TBProfiler#300]
Dear Dr.Jody,

I try to run tb-profiler via command line. I have command failed at step bwa mem and update_tbdb (attached files). Could you please suggest how to fix it?

Thank you very much.
[S1004.errog.txt](https://github.com/jodyphelan/TBProfiler/files/12495000/S1004.errog.txt)
[3b628762-ca17-4e5d-8ec2-a4f78b7fa502.errlog.txt](https://github.com/jodyphelan/TBProfiler/files/12495008/3b628762-ca17-4e5d-8ec2-a4f78b7fa502.errlog.txt)

**Comment by jodyphelan** [comment]
Hi @NonthakornSkw 

It looks like the bwa mem process was killed. This is usually due to lack of ram. Can you give me the details of the system you are running? e.g OS, RAM available etc..

**Comment by NonthakornSkw** [comment]
Dear Dr.Jody @jodyphelan 

Thank you very much for your reply. I can solve this problem by increasing virtual size on virtualbox program.

**Comment by jodyphelan** [comment]
Great to hear it is resolved!
