### ISSUE TITLE
Exception: Don't know how to handle this mutation

### ISSUE THREAD

**Issue by schorlton** [jodyphelan/TBProfiler#307]
Thanks for the great tool. This looks similar to https://github.com/jodyphelan/TBProfiler/issues/258 but on official latest ([1656b7fe64c5543d55cf52b55de67b2344e9564f](https://github.com/jodyphelan/tbdb/tree/1656b7fe64c5543d55cf52b55de67b2344e9564f)) tbdb. It may just be that you haven't had a chance to update tb-profiler yet (apologies).

To recreate:
tb-profiler 5.0.0 installed in micromamba docker image
```bash
tb-profiler update_tbdb --commit 1656b7fe64c5543d55cf52b55de67b234
4e9564f
```
Error:
```bash
Exception: Don't know how to handle this                    
                    mutation: gyrA                                              
                    c.2517_*25delATCAGGCTCGCCCGACGACGATGCGG
```

**Comment by jodyphelan** [comment]
Oh sorry I jumped the gun a bit on updating this before I updated tb-profiler!
You can use this, which is the last compatible version:

```
tb-profiler update_tbdb --commit 0599ccd
```

**Comment by schorlton** [comment]
Closing as I assume this is fixed in the latest version. Thanks again!
