### ISSUE TITLE
Question: Will TBProfiler work with long reads from PacBio and Oxford Nanopore? 

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#31]
Hi Jody, 

       Just wondering how well TB Profiler will work with long reads. Is there any issue with using this type of input data?   Thanks!

**Comment by jodyphelan** [comment]
I haven't tried with PacBio reads but ONT reads are already supported by using the flag `-m minION`

**Comment by harrismia** [comment]
Thanks for the information!
