### ISSUE TITLE
Mutations database update

### ISSUE THREAD

**Issue by alantsangmb** [jodyphelan/TBProfiler#315]
WHO has issued a update of the “Catalogue of mutations in Mycobacterium tuberculosis complex and their association with drug resistance”. Will the tbdb be updated accordingly? Thank you so much.

**Comment by jodyphelan** [comment]
Ho @alantsangmb 

Yes this is currently in progress. Hope to have it released before the end of the year

**Comment by wimmulders-ITM** [comment]
Hi Jody,
I was wondering if the TBDB update, based on the new WHO DR catalogue, has already been released?
Thanks.
wim

**Comment by jodyphelan** [comment]
Hi @wimmulders-ITM ,

Have a look at this post: https://github.com/jodyphelan/TBProfiler/discussions/321

**Comment by wimmulders-ITM** [comment]
Thank you Jody. That is clear.
My Best regards,
wim

From: Jody Phelan ***@***.***>
Date: Friday, 19 January 2024 at 18:55
To: jodyphelan/TBProfiler ***@***.***>
Cc: Wim Mulders ***@***.***>, Mention ***@***.***>
Subject: Re: [jodyphelan/TBProfiler] Mutations database update (Issue #315)

Hi @wimmulders-ITM<https://github.com/wimmulders-ITM> ,

Have a look at this post: #321<https://github.com/jodyphelan/TBProfiler/discussions/321>
