### ISSUE TITLE
Galaxy Wrapper

### ISSUE THREAD

**Issue by Kurt-Hanel** [jodyphelan/TBProfiler#32]
Hi @jodyphelan, do you know if there are any plans to create a Galaxy wrapper for TBProfiler? If not, I can take it on.

**Comment by jodyphelan** [comment]
Hi Kurt,

I haven't got much experience with galaxy so if you are keen to do it that would be great!

**Comment by Kurt-Hanel** [comment]
Sounds good, I'll give it a go!

**Comment by pvanheus** [comment]
Hi @Kurt-Hanel - I started a wrapper for the `profiler` part of TB-Profiler here: https://github.com/COMBAT-TB/tb_profiler_galaxy and am also interested in the `collate` sub-command. I think I just need to add tests and finish the `<help>` tag, I'll PR to tools-iuc when I'm done (hopefully tomorrow).

**Comment by jodyphelan** [comment]
I've realised that I have to tidy the usage help a bit (there are some arguments which are no longer used and others which need a better description). I'll get this done today.

**Comment by pvanheus** [comment]
Thank you. What is the `--delly` parameter for? Reading the code it seems to actually run the `delly` tool but I'm not quite clear how this impacts the output.

**Comment by jodyphelan** [comment]
The delly command was just used during testing so that I could compare the results with and without large deletion calling. It is now enabled by default and the parameter is no longer there.

I have now updated the help in the latest commit: https://github.com/jodyphelan/TBProfiler/commit/842b6c37866b7a401d7452afa549bed3bf95a8c5 . Does this need to be put into a Release for galaxy?

**Comment by pvanheus** [comment]
Galaxy gets the software via bioconda.

So if you made changes then tag a new release, the [recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/tb-profiler) gets updated (there is something of an auto-update bot on the bioconda side but I'm not sure how well it works, recipe might need a PR from a human) which builds the new version of the dependency and then its ready for use in the Galaxy tool wrapper.

**Comment by jodyphelan** [comment]
Ok the recipe on bioconda is now updated.

**Comment by jodyphelan** [comment]
Thanks for updating it @pvanheus

**Comment by Kurt-Hanel** [comment]
Hey @pvanheus, I took a look at your wrapper and the comments you made on my [pull request](https://github.com/galaxyproject/tools-iuc/pull/2343). I'm still very new to writing galaxy wrappers and yours seems more complete than mine. I see you already have some smaller test data, which is great. 

How would you like to proceed? I had not planned on adding the collate sub-command, so if you like I could work on shrinking my test data to get my pull request accepted, then you could open a new request with your more robust version when it's ready.

**Comment by pvanheus** [comment]
Why don't you take my fastq test data, then your PR can be merged and then
I'll merge mine into tools-iuc after that? I'll add the BAM test data when
I merge my additions.

**Comment by Kurt-Hanel** [comment]
Sounds good

**Comment by jodyphelan** [comment]
I've seen its on Galaxy now. Thanks for all the help guys!
