### ISSUE TITLE
 Issue with TB-Profiler Web Version: Uploading FASTQ.GZ Files Fails

### ISSUE THREAD

**Issue by yosmu** [jodyphelan/TBProfiler#329]
Dear Jody,

I am having trouble uploading Illumina paired-end FASTQ.GZ files on the web version of TB-Profiler using Chrome as my browser. 

I would appreciate your attention and assistance.
Many thanks.

yosmu

**Comment by jodyphelan** [comment]
Hi @yosmu 

Can you give me the names of the files you are trying to upload? It might be a naming issue.

**Comment by yosmu** [comment]
Hello, Jody

Now the problem appears to have been resolved.
Thanks for the warm support.

Yosmu
