### ISSUE TITLE
Missing Fluoroquinolone profile in the itol reports

### ISSUE THREAD

**Issue by emilyncosta** [jodyphelan/TBProfiler#331]
Dear Jody,

Working in analyzing the TB-Profiler outputs within the MAGMA pipeline using distinct datasets I realized that while the DR is classified as Pre-XDR based on the output "joint.major_variants.dr.itol.txt", the individual variants from output "joint.major_variants.dr.indiv.itol.txt" does not reflect the FLQ (LEVO or MOX) resistance.

CC @abhi18av @TimHHH @vrennie 

Thanks for helping ;)

Emilyn.

**Comment by jodyphelan** [comment]
Hi @emilyncosta 

Thankd for sharing, I'll take a look at that bug!

**Comment by abhi18av** [comment]
Hi @jodyphelan , 

Glad to see the latest `v6.0.0` release https://github.com/jodyphelan/TBProfiler/releases/tag/v6.0.0  🎉 

Any chance that this bug would be addressed in patch release soon?

**Comment by jodyphelan** [comment]
Hi @abhi18av ,

If I'm understanding correctly, the previous version showed Pre-XDR from the drug resistance itol colour strip, however no fluoroquinolone resistance was being shown on the individual drugs annotation. Is that correct?

The new version should correct this, e.g. see below:

![MXWX7Tmx9V5smgXvn6qmbg](https://github.com/jodyphelan/TBProfiler/assets/8697224/f407d61b-a04f-4fe3-aef4-abae56a43634)

**Comment by abhi18av** [comment]
> however no fluoroquinolone resistance was being shown on the individual drugs annotation. Is that correct? 


Yes, that is spot on! I can confirm that this has been resolved with the latest `v6.0.0` release and you can mark this issue as closed now :) 

Thank you for the prompt fix @jodyphelan !

**Comment by jodyphelan** [comment]
Great!
