### ISSUE TITLE
 No such file or directory: '/usr/share/tbprofiler/tbdb.config.json'

### ISSUE THREAD

**Issue by SafinaAr** [jodyphelan/TBProfiler#34]
I tried to run the following command and its saying no tbdb.config.json file found 

`tb-profiler profile -1 /home/isd/Working/MTB/SUSC/ERR108427_1.fastq -2 ERR108427_2.fastq -t 6 -p ERR108427`

Can you please help me with this issue?

**Comment by jodyphelan** [comment]
Hi Safina,

Did you install through bioconda? Are you on Linux or osx?

Jody

**Comment by SafinaAr** [comment]
I installed it:

git clone git@github.com:jodyphelan/TBProfiler.git
cd TBProfiler
python setup.py install

**Comment by SafinaAr** [comment]
> Hi Safina,
> 
> Did you install through bioconda? Are you on Linux or osx?
> 
> Jody
Hi,

Thank you for the quick response:
I installed it:

```
git clone git@github.com:jodyphelan/TBProfiler.git
cd TBProfiler
python setup.py install
```

**Comment by jodyphelan** [comment]
Ok, so the manual installation will need a few more steps.
1. Create the folder at /usr/share/tbprofiler
`sudo mkdir /usr/share/tbprofiler`
2. Load the latest tbdb library
`sudo tb-profiler update_tbdb`

This should do the trick. Let me know if you if there are any issues.

**Comment by SafinaAr** [comment]
I ran the commands you mentioned but now im having some other issues:
I ran: 
```
tb-profiler profile -1 /home/isd/Working/MTB/SUSC/ERR108427_1.fastq -2 /home/isd/Working/MTB/SUSC/ERR108427_2.fastq -t 6 -p ERR108427
```
This gave the following on the console:
Running command:
set -u pipefail; trimmomatic PE -threads 6 -phred33 /home/isd/Working/MTB/SUSC/ERR108427_1.fastq /home/isd/Working/MTB/SUSC/ERR108427_2.fastq ./ERR108427_1_trim_pair.fq ./ERR108427_1_trim_unpair.fq ./ERR108427_2_trim_pair.fq ./ERR108427_2_trim_unpair.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
Command Failed!

**Comment by jodyphelan** [comment]
Have you installed the prerequisites?
You will need trimmomatic, bwa, samtoools, bcftools and parallel.

It may be easier to install using conda, which will take care of all these steps.

**Comment by SafinaAr** [comment]
I already have all of these installed in my path.

**Comment by jodyphelan** [comment]
Can you run:
```
trimmomatic PE -threads 6 -phred33 /home/isd/Working/MTB/SUSC/ERR108427_1.fastq /home/isd/Working/MTB/SUSC/ERR108427_2.fastq ./ERR108427_1_trim_pair.fq ./ERR108427_1_trim_unpair.fq ./ERR108427_2_trim_pair.fq ./ERR108427_2_trim_unpair.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
```
And share the output?

**Comment by SafinaAr** [comment]
It is saying no trimmomatic command found. However i did checked it its installed:

Reading package lists... Done
Building dependency tree
Reading state information... Done
trimmomatic is already the newest version (0.36+dfsg-3).

**Comment by SafinaAr** [comment]
This is my trimmomatic result:
Running command:
set -u pipefail; trimmomatic PE -threads 6 -phred33 /home/isd/Working/MTB/SUSC/ERR108427_1.fastq /home/isd/Working/MTB/SUSC/ERR108427_2.fastq ./ERR108427_1_trim_pair.fq ./ERR108427_1_trim_unpair.fq ./ERR108427_2_trim_pair.fq ./ERR108427_2_trim_unpair.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
root@bioinfomatics:/home/isd/software/TBProfiler# trimmomatic PE -threads 6 -phred33 /home/isd/Working/MTB/SUSC/ERR108427_1.fastq /home/isd/Working/MTB/SUSC/ERR108427_2.fastq ./ERR108427_1_trim_pair.fq ./ERR108427_1_trim_unpair.fq ./ERR108427_2_trim_pair.fq ./ERR108427_2_trim_unpair.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
TrimmomaticPE: Started with arguments: -threads 6 -phred33 /home/isd/Working/MTB/SUSC/ERR108427_1.fastq /home/isd/Working/MTB/SUSC/ERR108427_2.fastq ./ERR108427_1_trim_pair.fq ./ERR108427_1_trim_unpair.fq ./ERR108427_2_trim_pair.fq ./ERR108427_2_trim_unpair.fq LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
Input Read Pairs: 2961713 Both Surviving: 2674874 (90.32%) Forward Only Surviving: 125190 (4.23%) Reverse Only Surviving: 109059 (3.68%) Dropped: 52590 (1.78%)
TrimmomaticPE: Completed successfully

**Comment by jodyphelan** [comment]
Did you install using apt-get?
Can you let me know the output of `which trimmomatic`?

**Comment by SafinaAr** [comment]
Hey i tried to install TBProfiler with conda but it is saying that no package found:
`conda install tb-profiler`

> PackageNotFoundError: Packages missing in current channels:
> 
>   tb-profiler
> 
> Search you package using:
> binstar search -t conda tb-profiler

I ran and it gave this results:

> Using Anaconda API: https://api.anaconda.org
> Run 'anaconda show <USER/PACKAGE>' to get more details:
> Packages:
>      Name                      |  Version | Package Types   | Platforms
>      ------------------------- |   ------ | --------------- | ---------------
>      bioconda/tb-profiler      |      2.1 | conda           | noarch
>                                           : TBProfiler tools for Mtb NGS data
> Found 1 packages

**Comment by SafinaAr** [comment]
> Did you install using apt-get?
> Can you let me know the output of `which trimmomatic`?

I installed like this:

> https://vcru.wisc.edu/simonlab/bioinformatics/programs/install/trimmomatic.htm

**Comment by SafinaAr** [comment]
Okay so i solved the conda problem and installed TBProfiler with conda but now my command stuck  here:

> Running command:
> set -u pipefail; delly call -t DEL -g /root/miniconda/share/tbprofiler/tbdb.fasta ./ERR108427.bam -o ./ERR108427.targets.delly.bcf
> Command Failed! Please Check!

**Comment by SafinaAr** [comment]
Hi,
The issue is with delly. see below:

> delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory

I did install libboost-dev-all but still same error

**Comment by SafinaAr** [comment]
Can this be the version specific issue as i have libboost_iostreams.so.1.65.1 ..

Thank you for your support.

**Comment by jodyphelan** [comment]
This is strange as conda should have sorted out the shared libraries. Since you are running on Linux, for a quick fix you can download the precompiled delly like this:
```
conda remove -y delly 
wget https://github.com/dellytools/delly/releases/download/v0.8.1/delly_v0.8.1_linux_x86_64bit
chmod 755 delly_v0.8.1_linux_x86_64bit
mv delly_v0.8.1_linux_x86_64bit `echo $PATH | tr ":" "\n" | head -1`/delly
```

**Comment by SafinaAr** [comment]
I'm really surprised now no anaconda or conda is found. And i had to reinstall it and again getting that first error trimmomatic failed. however when im running trimmomatic it is running. I dont know whats wrong.
Please help me what should i do now? its really surprising that one time it is running and 1 and a half hour later not running went back to first error again. 
I installed it in root and it was running in all users now just running from root not any other user. but getting previous error of trimmomatic

Please help :(

**Comment by SafinaAr** [comment]
Should i uninstall everything and redo?

**Comment by jodyphelan** [comment]
I think removing conda and reinstalling is the best toption. This issue is a bit outside the scope of this repository, so I will close this issue and I can assist you by email on the conda installation (already emailed you).

**Comment by SafinaAr** [comment]
Hi Jody,
 Im again having the previous problem.I have tried to install it on other Linux computer and it is giving the same problem I have installed it using conda but when I’m writing tb-profiler it is saying no command found. 
Please can you check is there something wrong in the installation process or conda ? Your help would be really appreciated. This is now making me insane. I m really very sorry for disturbing you this much. I hope you will be able to help me in this regards.
