### ISSUE TITLE
Prediction issue

### ISSUE THREAD

**Issue by RehmanZaira** [jodyphelan/TBProfiler#346]
I have installed TBProfiler locally and run number of samples. All the samples turned out to be sensitive. When the same samples run on web version of TBProfiler the same samples reported to be either MDR or XDR. Which is actual results as the samples are in fact MDR and XDR proven through DST method. Why this discrepancy exist? How can I improve the results of locally installed TBProfiler?

**Comment by jodyphelan** [comment]
Hi @RehmanZaira ,

Could you let me know the command you are using?

**Comment by RehmanZaira** [comment]
> Hi @RehmanZaira ,
> 
> Could you let me know the command you are using?

I am processing the nanopore sequencing reads from a directory and here is the command:

    "$TB_PROFILER" profile -1 "$file" -p "$PREFIX"_"$sample_name"

**Comment by jodyphelan** [comment]
Try adding `--platform nanopore` and see if that fixes the issue?

**Comment by RehmanZaira** [comment]
Now it is working fine. Thank you for the help.
I have another query: Can we change the threshold of variant calling in pipeline?

**Comment by jodyphelan** [comment]
Yes you should be able to change this. Check out https://jodyphelan.github.io/tb-profiler-docs/en/algorithm/#variant-calling

**Comment by RehmanZaira** [comment]
Thank you so much for the help.
