### ISSUE TITLE
version 6.2.0 error in lineage prediction

### ISSUE THREAD

**Issue by alantsangmb** [jodyphelan/TBProfiler#355]
Hello, I am using TBProfiler version 6.2.0 to predict the lineage of Mtb using the command:

tb-profiler lineage --bam '/home/micro/MiSeq/MS240409-0415/H37/bam/H37n.bam'
or
tb-profiler lineage --bam '/home/micro/MiSeq/MS240409-0415/H37/bam/H37n.bam'  --prefix H37-snp --snps

However, I encountered the following error:

[17:05:57] ERROR                                                    tb-profiler:59
                                                                                  
                    ################################# ERROR                       
                    #######################################                       
                                                                                  
                    This run has failed. Please check all arguments               
                    and make sure all input files                                 
                    exist. If no solution is found, please open up                
                    an issue at                                                   
                    https://github.com/jodyphelan/TBProfiler/issues               
                    /new and paste or attach the                                  
                    contents of the error log                                     
                    (tbprofiler.errlog.txt)                                       
                                                                                  
                    ###############################################               
                    ################################                              
                                                        
I have attached the error log file.
[H37-snp.errlog.zip](https://github.com/jodyphelan/TBProfiler/files/15233219/H37-snp.errlog.zip)

**Comment by jodyphelan** [comment]
Hi @alantsangmb ,

Does this error happen with other samples you tested or is it an edge case that seems to fail?

**Comment by alantsangmb** [comment]
Yes, I encountered this error with other samples as well.

**Comment by thanadon1437** [comment]
Hello,

I am facing the same problem here with lineage prediction.

The error log file is attached here.
[bc87.errlog.txt](https://github.com/jodyphelan/TBProfiler/files/15256977/bc87.errlog.txt)

**Comment by jodyphelan** [comment]
I've added in a fix now and this will be included in the next release (v6.2.1)
