### ISSUE TITLE
Recommended setting for allele frequency (-af)

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#36]
I noticed that the new version of TBProfiler has the parameter -af which allows you to set an allele frequency cutoff for minor variants.  The default is 0.9 .   Older versions of TBProfiler would report variants found in a fraction of the reads by showing for example (0.25) next to the variant.  Would it be possible to add an option to report the fraction of the reads having a variant independent of the -af setting?  

For example, I may want -af set to 0.9 for the purposes of MDR/XDR drug-resistance assignment but would still like to know that the katG S315T mutation is found in 10% of the reads for the sample.

In the collate  --full or --all_variants it would be nice if there were an option to include  low level variants which may fall below the -af cutoff. 

Best wishes, 

   Michael

**Comment by jodyphelan** [comment]
Hi Michael, 

That sounds like a bug to me. I'll check it.

Jody

**Comment by harrismia** [comment]
Thanks Jody! Best,

Michael

Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by harrismia** [comment]
HI Jody,



   FYI.  The version number that we are using is:  TBProfiler version 0.3.8



    Best,



      Michael




Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by jodyphelan** [comment]
Hi Michael,

With the latest release (v2.3) you can use `--af` variants based on frequency and `--reporting_af` to filter variants used to create the resistance report. 
I have also added an extra table to thhe text report showing all variants (regardless of the `--reporting_af`). See [this gist](https://gist.github.com/jodyphelan/11cfd9b88a55c700e961fa01f7238978) look at an example output.

Let me know if this is along the lines of what you were thinking!

Jody

**Comment by harrismia** [comment]
Great!  It sounds like that is exactly what I was looking for.   I will give it a try and let you know.  Best,

Michael

Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.
