### ISSUE TITLE
Cannot profile the nanopore file

### ISSUE THREAD

**Issue by thanadon1437** [jodyphelan/TBProfiler#362]
Hi Jody,

I have 2 different nanopore .fastq.gz files (barcode57 and barcode34) and those 2 came from using `cat` command.

The barcode57 can profile properly with 
`tb-profiler profile -1 [filename].fastq.gz --platform nanopore --prefix [filename] --csv` 

<img width="1365" alt="Screenshot 2567-05-13 at 11 49 24" src="https://github.com/jodyphelan/TBProfiler/assets/169325075/1e3a069b-fe7b-487b-bdaf-df9a2e2aa841">

but barcode34 using the same command got stuck in the variant calling process at 5%.

<img width="1365" alt="Screenshot 2567-05-13 at 11 47 33" src="https://github.com/jodyphelan/TBProfiler/assets/169325075/405d38e7-a4a3-4056-9f48-09614779ee16">

I attached all the files here and also error file from barcode34 here.

[barcode34.fastq.gz](https://github.com/jodyphelan/TBProfiler/files/15289487/barcode34.fastq.gz)

[barcode57.fastq.gz](https://github.com/jodyphelan/TBProfiler/files/15289490/barcode57.fastq.gz)

[barcode34.errlog.txt](https://github.com/jodyphelan/TBProfiler/files/15289492/barcode34.errlog.txt)

Thanadon

**Comment by jodyphelan** [comment]
Hi @thanadon1437 

I think it is getting stuck due to the error rate with nanopore. Try to increase the minimum allele frequency for the variant calling to to be more appropriate for the nanopore error rate and run faster (e.g. `--af 0.4,0.7`).

**Comment by thanadon1437** [comment]
> Hi @thanadon1437
> 
> I think it is getting stuck due to the error rate with nanopore. Try to increase the minimum allele frequency for the variant calling to to be more appropriate for the nanopore error rate and run faster (e.g. `--af 0.4,0.7`).
> 
> I'll add make sure the default values are overriden with some sensible defaults in the next release

I am quite new here. 

Can you show me a command how to set `--af`?
and also how to update the version into 6.2.1 directly from github since conda package website is 6.2.0 `conda install tb-profiler`

**Comment by jodyphelan** [comment]
Sure, your command should be:

```
tb-profiler profile -1 barcode34.fastq.gz --platform nanopore --prefix barcode34 --csv --af 0.4,0.7
```

If you want to update, you can simple just run `conda install tb-profiler=6.2.1` when you are in the right environment. 
There seems to be a bit of a technical problem with bioconda at the moment so v6.2.1 is currently not available. This will hopefully be fixed soon.

**Comment by thanadon1437** [comment]
Thank you, now I can profile it and keep trying to change the `--af` parameter to get the result that I found on IGV but I still cannot get it in the TB-profiler report on the following region.

There are 2 suspected mutations that I found on IGV. Do you have any idea how to change the parameters to get those 2 variants in the TB-profiler report?

<img width="1863" alt="Screenshot 2567-05-13 at 16 51 07" src="https://github.com/jodyphelan/TBProfiler/assets/169325075/2e725080-9269-4277-8cfd-a1970d6110ff">

The sample is originally from the targeted seq using the Nanopore platform.

P.S. Since I don't want to mess this issue with my personal bioinformatic questions. Would you mind giving me the unofficial contact route like Discord or something where you can reply in your free time?
