### ISSUE TITLE
Cannot perform lineage and spoligotype in v6.2.1

### ISSUE THREAD

**Issue by thanadon1437** [jodyphelan/TBProfiler#365]
Hi Jody,

I just updated the tb-profiler to v6.2.1 and the error about lineage prediction seems resolved but there is no result about lineage in the .json file (it shows ""). The spoligotype also got the error that I attached a log file here.

![Screen Shot 2567-05-24 at 10 17 43 AM](https://github.com/jodyphelan/TBProfiler/assets/169325075/d4fe4e8b-cad4-4dda-8822-33d2b4de49a7)

[bc34spo.errlog.txt](https://github.com/jodyphelan/TBProfiler/files/15427035/bc34spo.errlog.txt)

also the .bam file if you want to test it yourself.
[barcode34-2.zip](https://github.com/jodyphelan/TBProfiler/files/15427057/barcode34-2.zip)

**Comment by jodyphelan** [comment]
Hi @thanadon1437 

I believe this is targeted NGS data right? In this case the lineage prediction won't work as it uses SNPs that are not covered by the amplicons. The Spoligotype bug is fixed in the latest version and should be available in v6.2.2 when it comes out.

**Comment by thanadon1437** [comment]
> Hi @thanadon1437
> 
> I believe this is targeted NGS data right? In this case the lineage prediction won't work as it uses SNPs that are not covered by the amplicons. The Spoligotype bug is fixed in the latest version and should be available in v6.2.2 when it comes out.

Thank you @jodyphelan 

Yes, it is targeted NGS data. Will it be improved in the next version? because I used the built-in software from ONT they can report the lineage like this while TB-profiler cannot report the lineage of the same sample.

<img width="689" alt="Screenshot 2567-05-24 at 19 22 23" src="https://github.com/jodyphelan/TBProfiler/assets/169325075/bc261933-d520-49e3-b9ce-489be01a70bd">

TB-profiler result

<img width="511" alt="Screenshot 2567-05-24 at 19 26 42" src="https://github.com/jodyphelan/TBProfiler/assets/169325075/85e16502-db7c-4713-93d7-1e53db97d02a">

**Comment by thanadon1437** [comment]
> Hi @thanadon1437
> 
> I believe this is targeted NGS data right? In this case the lineage prediction won't work as it uses SNPs that are not covered by the amplicons. The Spoligotype bug is fixed in the latest version and should be available in v6.2.2 when it comes out.

Hi @jodyphelan,

is that bug fixed in 6.3.0? so you can close this issue.

Thank you

**Comment by jodyphelan** [comment]
Hi @thanadon1437 , it should be, I'll close this for now but let me know if there are any issues
