### ISSUE TITLE
iTOL files not created

### ISSUE THREAD

**Issue by moks-micro** [jodyphelan/TBProfiler#366]
Hi Jody, 

I've been running tbprofiler v6.2.1, and it doesn't seem to be creating any of the iTOL files when I run the collate command:

tb-profiler collate -p test_name

Am I missing something in the command ?

Thanks
Simone

**Comment by jodyphelan** [comment]
Hey Simone!

You can add in `--itol` to the command. I thought i was the only one who used it so I took it out of the default settings, but maybe I'll but it back in the next version!

**Comment by moks-micro** [comment]
Thanks Jody!! We really like to use the itol files here :)
The only problem when I use --itol is that it seems to have a problem if La1-3 lineages are present and wont create the itol files. It only works when I only have lineages 1-5. Does this ever happen to you ?

(tbprofiler_6.2.1) simone@BioinformaticsWorkstation:~/Documents/tbprofiler6.2.1_validation/TBprofiler_6.2.1$ tb-profiler collate -p tbprofiler6.2.1_validation --itol
[09:00:59] INFO     Using ref file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.fasta                                         db.py:587
           INFO     Using gff file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.gff                                           db.py:587
           INFO     Using bed file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.bed                                           db.py:587
           INFO     Using json_db file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.dr.json                                   db.py:587
           INFO     Using variables file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.variables.json                          db.py:587
           INFO     Using spoligotype_spacers file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.spoligotype_spacers.txt       db.py:587
           INFO     Using spoligotype_annotations file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.spoligotype_list.csv      db.py:587
           INFO     Using bedmask file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.mask.bed                                  db.py:587
           INFO     Using barcode file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.barcode.bed                               db.py:587
           INFO     Using rules file: /home/simone/miniconda3/envs/tbprofiler_6.2.1/share/tbprofiler//tbdb.rules.txt                                   db.py:587
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [00:00<00:00, 448.86it/s]
Traceback (most recent call last):
  File "/home/simone/miniconda3/envs/tbprofiler_6.2.1/bin/tb-profiler", line 587, in <module>
    args.func(args)
  File "/home/simone/miniconda3/envs/tbprofiler_6.2.1/bin/tb-profiler", line 273, in main_collate
    tbp.collate_results(args)
  File "/home/simone/miniconda3/envs/tbprofiler_6.2.1/lib/python3.10/site-packages/tbprofiler/collate.py", line 149, in collate_results
    generate_itol_config(rows,drugs,args.prefix)
  File "/home/simone/miniconda3/envs/tbprofiler_6.2.1/lib/python3.10/site-packages/tbprofiler/collate.py", line 178, in generate_itol_config
    writer.write(lineage_outfile)
  File "/home/simone/miniconda3/envs/tbprofiler_6.2.1/lib/python3.10/site-packages/itol_config/interfaces/colour_strip.py", line 33, in write
    O.write("%s\t%s\n" % (index,self.colour_lookup[value]))
KeyError: 'La1'
Cleaning up after failed run
           ERROR                                                                                                                                  tb-profiler:59
                                                                                                                                                                
                    ################################# ERROR #######################################                                                             
                                                                                                                                                                
                    This run has failed. Please check all arguments and make sure all input files                                                               
                    exist. If no solution is found, please open up an issue at                                                                                  
                    https://github.com/jodyphelan/TBProfiler/issues/new and paste or attach the                                                                 
                    contents of the error log (tbprofiler6.2.1_validation.errlog.txt)

**Comment by jodyphelan** [comment]
Oh this looks like a bug. I'll run some tests.

**Comment by abhi18av** [comment]
Hi @jodyphelan ,

Ran across the same behavior, though for a specific sample - we'd like to reenable `iTol` for v2 of MAGMA and the error highlights `Mcanetti` for some reason. https://github.com/TORCH-Consortium/MAGMA/pull/197 

``` 
  Traceback (most recent call last):
    File "/usr/local/bin/tb-profiler", line 583, in <module>
      args.func(args)
    File "/usr/local/bin/tb-profiler", line 269, in main_collate
      tbp.collate_results(args)
    File "/usr/local/lib/python3.10/site-packages/tbprofiler/collate.py", line 149, in collate_results
      generate_itol_config(rows,drugs,args.prefix)
    File "/usr/local/lib/python3.10/site-packages/tbprofiler/collate.py", line 178, in generate_itol_config
      writer.write(lineage_outfile)
    File "/usr/local/lib/python3.10/site-packages/itol_config/interfaces/colour_strip.py", line 33, in write
      O.write("%s\t%s\n" % (index,self.colour_lookup[value]))
  KeyError: 'M.canetti'
  Cleaning up after failed run
             ERROR                                                  tb-profiler:59

                      ################################# ERROR
                      #######################################

                      This run has failed. Please check all
                      arguments and make sure all input files
                      exist. If no solution is found, please open
                      up an issue at
                      https://github.com/jodyphelan/TBProfiler/issu
                      es/new and paste or attach the
                      contents of the error log
                      (joint.major_variants.errlog.txt)

                      #############################################
                      ##################################



```

CC @vrennie @mdediegofuertes

**Comment by abhi18av** [comment]
Hi @jodyphelan , just checking in regarding the release with the https://github.com/jodyphelan/TBProfiler/commit/4c50d84efd00d0b0a0dc3b385c81f487efb336fe ? 

We'd really appreciate if this could be released as a patch please :)

**Comment by jodyphelan** [comment]
All features for the next version are now complete so I've started the release process now

**Comment by abhi18av** [comment]
Great news - thanks Jody for keeping us posted! Looking forward to the release and then we'll update the containers and env on our side as well.

**Comment by vrennie** [comment]
As always @jodyphelan thanks for the effort! Much appreciated

**Comment by abhi18av** [comment]
Hi @jodyphelan ,

Confirming from our side that the latest `6.3.0` is producing the relevant `iTol` annotations. Thank you so much for taking this forward!

https://github.com/jodyphelan/TBProfiler/releases/tag/v6.3.0 

CC @vrennie @mdediegofuertes

**Comment by jodyphelan** [comment]
Amazing! I'll close this then
