### ISSUE TITLE
Problem using NC_000962.3 as seqname

### ISSUE THREAD

**Issue by flashton2003** [jodyphelan/TBProfiler#37]
I'm trying to determine the lineage of some samples which have been aligned against  NC_000962.3 reference genome.

I cloned tbdb repository, ran `python parse_db.py --seqname NC_000962.3`, then ran `tb-profiler load_library tbdb` but then when I ran 

`tb-profiler lineage -a /home/ubuntu/external_tb/oucru_robot/12778-ERR2653170/phenix_bbduk/12778-ERR2653170.bam`

the only output was an empty json file i.e. '{}'

The load_library seems to have worked, or at least the below command returns the expected.

```
$ grep '>' /home/ubuntu/miniconda/share/tbprofiler/tbdb.fasta
>NC_000962.3
```

Any thoughts? Sorry, I'm not that familiar with tb-profiler so might have missed something obvious.

**Comment by jodyphelan** [comment]
I think it might be reading the old fasta.fai index file. Try running:
```
samtools faidx /home/ubuntu/miniconda/share/tbprofiler/tbdb.fasta
```
And see if that helps.

**Comment by jodyphelan** [comment]
I have now added automatic reindexing on when using `tb-profiler load_library` and added the --seqname option to `tb-profiler update_tbdb` (df5e26e ). 

The following should now work for you:
```
tb-profiler update_tbdb --seqname NC_000962.3
```
Let me know if there are still issues.

**Comment by flashton2003** [comment]
yep, re-indexing the reference worked. thanks!
