### ISSUE TITLE
QC metrics

### ISSUE THREAD

**Issue by thanadon1437** [jodyphelan/TBProfiler#377]
Hi @jodyphelan,

I profiled my tNGS data obtained from nanopore sequencing using TB-profiler and it presented two variants in the _rpoB_ gene: L430P (761,095) and D435A (761,110) both variants associated with resistance. One variant was reported in the “resistance variants report,” while the other was listed in the “QC failed variants report.”

Additionally, there are a few samples where resistance-associated variants were found, which are concordant with the pDST, but these variants were also reported in the QC failed section.

Could you please explain the criteria or QC metrics that TB-profiler uses to determine which variants pass or fail quality control?

Thank you!

**Comment by jodyphelan** [comment]
Hi @thanadon1437 
Have a look here for info on the variant filtering: https://jodyphelan.github.io/tb-profiler-docs/en/algorithm/#variant-filtering
Additionally see here for more info: https://github.com/jodyphelan/TBProfiler/issues/239#issuecomment-2054068666

**Comment by thanadon1437** [comment]
> Hi @thanadon1437 Have a look here for info on the variant filtering: https://jodyphelan.github.io/tb-profiler-docs/en/algorithm/#variant-filtering Additionally see here for more info: [#239 (comment)](https://github.com/jodyphelan/TBProfiler/issues/239#issuecomment-2054068666)

What could be the reason of soft-fail in my case since I am using single-end data, having over 95% estimated fraction, and those variants are also located very close to each other?

**Comment by thanadon1437** [comment]
I just ran `samtools depth -r Chromosome:760000-761300 input.bam > depth_rpob.txt`

the one that was soft fail shown
`Chromosome	761095	99`

and another that reported 
`Chromosome	761110	101`

I attached the output of samtools depth here
[depth_rpob.txt](https://github.com/user-attachments/files/16027427/depth_rpob.txt)

**Comment by jodyphelan** [comment]
Could you post the json result file?

**Comment by thanadon1437** [comment]
> Could you post the json result file?

Sure, I am willing to know more about the explanation.
here the .json file
[barcode01.results.json](https://github.com/user-attachments/files/16027683/barcode01.results.json)

and this also the sample that 2 _rpoB_ variants and 1 _inhA_ (both are WHO G1) reported in QC failed
[barcode05.results.json](https://github.com/user-attachments/files/16027703/barcode05.results.json)

Thank you
