### ISSUE TITLE
Why are genes not associated with drug resistance included in tbdb.bed?

### ISSUE THREAD

**Issue by mariaelf97** [jodyphelan/TBProfiler#378]
Dear author,

Good day to you! Thank you for the great tool.
I was reviewing the 2023 WHO drug resistance catalogue and it looks like some of the genes that are not associated with drug resistance is included in your tbdb.bed file. For instance, no danA mutation is reported as "associated with R" in the catalogue but you included it in your db. Could you explain the reasoning behind it?

Thank you.

**Comment by jodyphelan** [comment]
Hi @mariaelf97 

There were a number of genes that were used by the WHO in their analysis. These were classified as tier 1 and tier 2 genes based on the available evidence. Genes such as dnaA have been implicated in drug resistance, however no individual variant passed the statistical cutoffs set by the WHO. I have included all genes in the database as it would be useful to call varaints for all candidate resistance genes for surveillance purposes. Have a look at the table below for all genes, or have a look at table 21 in https://www.who.int/publications/i/item/9789240082410.

<img width="815" alt="image" src="https://github.com/jodyphelan/TBProfiler/assets/8697224/435e6934-dfbb-4138-8ec7-673319af049a">

**Comment by jodyphelan** [comment]
Going to close this now but feel free to reopen if you have any more questions
