### ISSUE TITLE
different results between instances of tb-profiler

### ISSUE THREAD

**Issue by flashton2003** [jodyphelan/TBProfiler#38]
I'm having a problem with two installations of tb-profiler on different servers giving different results.

Both installations are linux, v2.2.0 from conda (one is miniconda, one is anaconda, but I don't think that should make a difference?). For both of them I've downloaded the latest database from tbdb git repo, parsed the db with the NC_000962.3 seq name, loaded the library and re-indexed the fasta file in the conda share dir.

I'm running `tb-profiler lineage -a <bamfile>`.

The bam file is [here](https://www.dropbox.com/s/552jkb4noamt98d/9825-SRR5067384.bam?dl=0) (275 Mb, dropbox link).

One server/installation gives this result

[{"spoligotype": "LAM;T;S;X;H", "rd": "None", "lin": "lineage4", "frac": 1, "family": "Euro-American"}]

and the other server gives this result

[{"lin": "lineage4", "family": "Euro-American", "spoligotype": "LAM;T;S;X;H", "rd": "None", "frac": 1.0}, {"lin": "lineage4.4", "family": "Euro-American", "spoligotype": "S;T", "rd": "None", "frac": 0.9948453608247423}, {"lin": "lineage4.4.2", "family": "Euro-American", "spoligotype": "T1;T2", "rd": "None", "frac": 0.9985196150999259}]

Any thoughts?

**Comment by jodyphelan** [comment]
Hmm that is quite strange. Can send the output of `conda env export` for the different servers?

**Comment by flashton2003** [comment]
This is the server which isn't working

```
$ conda env export -n default
name: default
channels:
  - bioconda
  - defaults
  - conda-forge
prefix: /home/ubuntu/anaconda2/envs/default
```
and the server which is working as expected.

```
$ conda env export -n default
name: default
channels:
  - https://conda.anaconda.org/qiime2/label/r2017.6
  - https://conda.anaconda.org/qiime2
  - https://conda.anaconda.org/biocore
  - https://conda.anaconda.org/bioconda
  - bioconda
  - r
  - defaults
  - conda-forge
prefix: /home/ubuntu/miniconda/envs/default
```

**Comment by jodyphelan** [comment]
Can you try create an environment just for tbprofiler on the server which isnt working just to check if it has anything to do with versions of python or bcftools:
`conda create -n test tb-profiler=2.3`

**Comment by flashton2003** [comment]
That works, thanks Jesse!
