### ISSUE TITLE
TypeError: profiler() got an unexpected keyword argument 'af'

### ISSUE THREAD

**Issue by Philipkkw** [jodyphelan/TBProfiler#39]
Hi Jody,

I've followed the tbprofiler installition guide (conda) and tried running the whole pipeline on my fastq files (on CentOS 6.5 and  Univa cluster system), but I kept getting this error:

[kwpkwan@n068 scripts]$  tb-profiler profile -1 /mnt/projects/xx/x_R1_001.fastq.gz -2 /mnt/projects/xx/x_R2_001.fastq.gz
Traceback (most recent call last):
  File "/mnt/projects/xx/miniconda2/bin/tb-profiler", line 333, in <module>
    args.func(args)
  File "/mnt/projects/xx/miniconda2/bin/tb-profiler", line 82, in main_profile
results=pp.profiler(conf_file=conf_file,prefix=args.dir+"/"+args.prefix,r1=args.read1,r2=args.read2,bam_file=args.bam,call_method=args.call_method,min_depth=args.min_depth,threads=args.threads,platform=args.platform,mapper=args.mapper,run_delly=True,af=args.af)
TypeError: profiler() got an unexpected keyword argument 'af'

Is it something to do with the conda that I installed?

**Comment by jodyphelan** [comment]
Looks like an old version of pathogen-profiler (one of the prerequisites) is installing. 
Try running `conda install pathogen-profiler=1.3`. This should sort it out.
Let me know how it goes,
Jody

**Comment by Philipkkw** [comment]
Thanks Jody! the program can start now

**Comment by steffan711** [comment]
Hello Jody,

I tried the same as mentioned above and got the very same error. I then updated pathogen-profiler to the newest (1.7.3) version and got the following error:

(base) user@taraptap:~$ tb-profiler profile -1 '/home/user/Documents/december/2/2R1.fastq.gz'  -2 '/home/user/Documents/december/2/2R2.fastq.gz'  -p '/home/user/Documents/december/2' 
Traceback (most recent call last):
  File "/home/user/bin/miniconda3/bin/tb-profiler", line 333, in <module>
    args.func(args)
  File "/home/user/bin/miniconda3/bin/tb-profiler", line 82, in main_profile
    results = pp.profiler(conf_file=conf_file,prefix=args.dir+"/"+args.prefix,r1=args.read1,r2=args.read2,bam_file=args.bam,call_method=args.call_method,min_depth=args.min_depth,threads=args.threads,platform=args.platform,mapper=args.mapper,run_delly=True,af=args.af)
TypeError: profiler() got an unexpected keyword argument 'conf_file'

Could you provide an advice how to deal with this problem?

**Comment by jodyphelan** [comment]
Hi @steffan711,

Does it work if you try to create a new environment with `conda create -n tb-profiler tb-profiler=2.8.13`?

Jody

**Comment by tomlas32** [comment]
does the pathogen-profiler get installed as a part of the tbprofiler package? I recently installed this  using conda and i am getting the same errors as the original post. I tried installing the pathogen-profiler 1.3 but after hours nothing really happened.  It's odd as a few days ago everything was working fine when I ran the test code from the README. 
Now even those don't work.
also, Does this work only on Mac and Linux?
thanks
Tom

**Comment by jodyphelan** [comment]
Hi @tomlas32 

Yes pathogen-profiler should gt installed as part of the tb-profiler package if you are installing it through conda. Which version did you install? Does it work if you try install the latest version in its own env?

```
conda create -n tb-profiler tb-profiler=4.3.0
```

> also, Does this work only on Mac and Linux?
It is also available to run on windows, but this has to be done through docker or a WSL installation.
