### ISSUE TITLE
-b option   .  TB reference genome version needs to be explicitly specified

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#4]
Hi,   Thanks very much for adding the ability to start from a .bam file!  

I assume that if I don't use the same reference version of the TB genome that you are assuming that all of the annotation will be off.      You probably should warn users about this or have some way of checking the reference version used for the mapping to make sure that it is compatible with the reference version.

**Comment by jodyphelan** [comment]
Hi Harrismia,

Yes that is correct. It should be mapped to the ensembl version of the h37rv genome. 
```
ftp://ftp.ensemblgenomes.org/pub/release-32/bacteria//fasta/bacteria_0_collection/mycobacterium_tuberculosis_h37rv/dna/Mycobacterium_tuberculosis_h37rv.ASM19595v2.dna.toplevel.fa.gz
```
I will add a note about this.

Let me know if you would like any other features!

Jody
