### ISSUE TITLE
Stuck at splitchr.py + bcftools

### ISSUE THREAD

**Issue by Philipkkw** [jodyphelan/TBProfiler#40]
Hi Jody,

The program got stuck at the splitchr.py + bcftools step (bam and bai files were successfully created):

------------------
Running command:
set -u pipefail; samtools index -@ 4 ./tbprofiler_pasco36.bam

Variant calling optimised for Illumina

Running command:
set -u pipefail; splitchr.py /mnt/projects/kwpkwan/TB/test/softwares/miniconda2/share/tbprofiler/tbdb.fasta 50000 --bed /mnt/projects/kwpkwan/TB/test/softwares/miniconda2/share/tbprofiler/tbdb.bed --reformat | parallel --col-sep '\t' -j 32 "bcftools mpileup -f /mnt/projects/kwpkwan/TB/test/softwares/miniconda2/share/tbprofiler/tbdb.fasta ./tbprofiler_sample36.bam -ABq0 -Q0 -a DP,AD -r {1} | bcftools call -mg 10 | bcftools norm -f /mnt/projects/kwpkwan/TB/test/softwares/miniconda2/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -Ou -S . | bcftools view -Ob -o ./tbprofiler_sample36.targets_{2}.bcf "
Command Failed! Please Check!
----------------------

Here is my bcftools --version
>bcftools 1.9
>Using htslib 1.9

,and this is my output for splitchr.py
>splitchr.py /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/share/tbprofiler/tbdb.fasta 50000 --bed /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/share/tbprofiler/tbdb.bed --reformat
Chromosome:4998-7267    Chromosome_4998_7267
Chromosome:7268-9818    Chromosome_7268_9818
Chromosome:759310-763325        Chromosome_759310_763325
Chromosome:763326-767320        Chromosome_763326_767320
Chromosome:778906-779487        Chromosome_778906_779487
Chromosome:781312-781933        Chromosome_781312_781933
Chromosome:800793-801461        Chromosome_800793_801461
Chromosome:1416181-1417657      Chromosome_1416181_1417657
Chromosome:1471743-1473382      Chromosome_1471743_1473382
Chromosome:1473383-1476795      Chromosome_1473383_1476795
Chromosome:1673300-1674183      Chromosome_1673300_1674183
Chromosome:1674184-1675011      Chromosome_1674184_1675011
Chromosome:1833380-1834987      Chromosome_1833380_1834987
Chromosome:1917933-1918745      Chromosome_1917933_1918745
Chromosome:2153889-2156148      Chromosome_2153889_2156148
Chromosome:2288682-2289281      Chromosome_2288682_2289281
Chromosome:2518115-2519365      Chromosome_2518115_2519365
Chromosome:2714124-2715471      Chromosome_2714124_2715471
Chromosome:2726088-2726780      Chromosome_2726088_2726780
Chromosome:2746139-2747594      Chromosome_2746139_2747594
Chromosome:2986841-2987615      Chromosome_2986841_2987615
Chromosome:3067193-3068188      Chromosome_3067193_3068188
Chromosome:3073680-3074471      Chromosome_3073680_3074471
Chromosome:3086755-3087935      Chromosome_3086755_3087935
Chromosome:3640142-3641538      Chromosome_3640142_3641538
Chromosome:3840198-3841713      Chromosome_3840198_3841713
Chromosome:4043862-4044280      Chromosome_4043862_4044280
Chromosome:4239864-4243147      Chromosome_4239864_4243147
Chromosome:4243148-4246513      Chromosome_4243148_4246513
Chromosome:4246514-4249810      Chromosome_4246514_4249810
Chromosome:4326004-4327548      Chromosome_4326004_4327548
Chromosome:4327549-4328199      Chromosome_4327549_4328199
Chromosome:4407528-4408333      Chromosome_4407528_4408333

---------------
bcftools --version
>bcftools 1.9
>Using htslib 1.9
---------------

I also tried running the entire command script above on my interactive node but I got this error
>perl: symbol lookup error: /mnt/software/lib/perl5/5.10.1/auto/Cwd/Cwd.so: undefined symbol: Perl_Istack_sp_ptr
>close failed in file object destructor:
>sys.excepthook is missing
>lost sys.stderr

Not sure what's wrong. I tried to reinstall conda perl but it still didn't work. Maybe it's something to do with perl -- when I ran "which perl" I got "/mnt/projects/kwpkwan/TB/test/softwares/miniconda2/bin/perl" (not "/mnt/software/" which is my cluster default softwares) 

Really appreciate your help here. Any tips to troubleshoot this? 

Thank you.
Philip

**Comment by jodyphelan** [comment]
Can you check parallel is working? Try running this:
```
splitchr.py /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/share/tbprofiler/tbdb.fasta 50000 --bed /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/share/tbprofiler/tbdb.bed --reformat | parallel --col-sep "\t" -j32 "echo {1}"
```

**Comment by Philipkkw** [comment]
The parallel is not working and it's the cause for that perl error:

--------------
(base) [kwpkwan@n006 scripts]$ python /mnt/projects/kwpkwan/TB/x/softwares/miniconda2/bin/splitchr.py /mnt/projects/kwpkwan/TB/x/softwares/miniconda2/share/tbprofiler/tbdb.fasta 50000 --bed /mnt/projects/kwpkwan/TB/x/softwares/miniconda2/share/tbprofiler/tbdb.bed --reformat | parallel --col-sep "\t" -j32 "echo {1}"
perl: symbol lookup error: /mnt/software/lib/perl5/5.10.1/auto/Cwd/Cwd.so: undefined symbol: Perl_Istack_sp_ptr
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
----------------

I guess this might be the cause? Is there a way around this?

**Comment by jodyphelan** [comment]
Have you tried reinstalling parallel?
```conda install parallel=20160622=1```

**Comment by Philipkkw** [comment]
I've reinstalled parallel but now bcftools has this same error that I faced earlier with samtools:

bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Earlier for samtools, I manually downgraded the openssl (conda install openssl=1.0 based on this trend: https://github.com/bioconda/bioconda-recipes/issues/12100) that help the program run until bwa mapping but it might have affected parallel in the process. By updating parallel, this error is back. I tried repeating the openssl downgrading step to make bcftools work but I got the "Perl_Istack_sp_ptr" error again.

Is there a better way to make parallel and bcftools work at the same time? Perhaps the downgrading step was a mistake, and maybe there's a better way to reinstall bcftools/samtools with the specific openssl?

Thank you.
Philip

**Comment by jodyphelan** [comment]
Strange, I assumed conda would handle all the versioning correctly. Can you try create a new envorinment? 
```
conda create -n test tb-profiler=2.3
```

**Comment by Philipkkw** [comment]
There's a new error when trying to test for parallel (I've tried reinstalling parallel again but the problem is still there:

conda activate test
splitchr.py /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/share/tbprofiler/tbdb.fasta 50000 --bed /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/share/tbprofiler/tbdb.bed --reformat | parallel --col-sep "\t" -j32 "echo {1}"
perl: symbol lookup error: /mnt/software/lib/perl5/5.10.1/auto/Cwd/Cwd.so: undefined symbol: Perl_Istack_sp_ptr
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe


Also, when I did the "conda create", there was this note at the end. I'm wondering if it will be an issue later:
Preparing transaction: done
Verifying transaction: -
CondaMultiError: SafetyError: The package for tb-profiler located at /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/pkgs/tb-profiler-2.3-py_0
appears to be corrupted. The path 'share/tbprofiler/tbdb.fasta'
has an incorrect size.
  reported size: 4485135 bytes
  actual size: 4411545 bytes

SafetyError: The package for tb-profiler located at /mnt/projects/kwpkwan/TB/capture_probe/softwares/miniconda2/pkgs/tb-profiler-2.3-py_0
appears to be corrupted. The path 'share/tbprofiler/tbdb.gff'
has an incorrect size.
  reported size: 2346900 bytes
  actual size: 2346899 bytes

                                                                                                                                                                     done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

**Comment by Philipkkw** [comment]
I tried a separate system (Centos7) and it works!! I continued with the bam files using the "profile -a" command 

For this new system, I also did the "conda create -n test tb-profiler=2.3" but it didn't give me the SafetyError above.

**Comment by jodyphelan** [comment]
That is very strange. I am not too familiar with conda but I think it is not handling the dependencies properly.

The Safety error is concerning. On the server where it does not work it may be worthwhile to try a seperate installation of conda to see if that works.

**Comment by Philipkkw** [comment]
I'll try reinstalling miniconda and let you know

**Comment by Philipkkw** [comment]
Still didn't work after reinstalling...
But, it worked after I manually set the $PERL5LIB in my ~/.bashrc:

..........
unset PERL5LIB
export PERL5LIB=$PERL5LIB:/mnt/projects/kwpkwan/TB/X/softwares/miniconda2/envs/test/bin/perl
.........

Previously when I did "echo $PERL5LIB" , it returns the perl from my cluster's default path ( although "which perl" command did show the correct conda path)-- so, looks like the reason for this due to my cluster's set-up rather than the operating system.


Thank you Jody!

**Comment by jodyphelan** [comment]
I see... It might be worthwhile getting one of the system admins to take a look at the envoronment setup. It definitely seems like parallel is at fault but I'm not sure why exactly. I was under the impression conda would handle all the dependancies.

**Comment by pvanheus** [comment]
@jodyphelan 'm a bit confused here - the `splitchr.py` and other things are not part of `tbprofiler` as far as I can tell. The conda recipe certainly doesn't deal with parallel etc. Is this a wrapper that is being described?

**Comment by jodyphelan** [comment]
@pvanheus That is correct, `tbprofiler` requires `pathogen-profiler` (found [here](https://bioconda.github.io/recipes/pathogen-profiler/README.html)) which in turn requires all the command line tools like parallel bwa samtools etc..

**Comment by pvanheus** [comment]
Ok noted. In that case it definitely should pull in all those dependencies. Odd.
