### ISSUE TITLE
json.dump permission error

### ISSUE THREAD

**Issue by ponomarevsy** [jodyphelan/TBProfiler#41]
Running Anaconda install of TBProfiler versions 2.1, 2.3 produces this error:

$ module load tbprofiler/2.1

$ tb-profiler profile -1 /pathtofile/SRR3743202_1.fastq.gz -2 /pathtofile/SRR3743202_2.fastq.gz -t 4 -p SRR3743202 -d /pathtooutput/TB_all_profiler/
Traceback (most recent call last):
  File "/pathtoAnaconda2/5.3.0/envs/tb-profiler2.1_env/bin/tb-profiler", line 266, in <module>
    args.func(args)
  File "/pathtoAnaconda2/5.3.0/envs/tb-profiler2.1_env/bin/tb-profiler", line 55, in main_profile
    json.dump(new_conf,open(sys.base_prefix+"/share/tbprofiler/tbdb.config.json","w"))
PermissionError: [Errno 13] Permission denied: '/pathtoAnaconda2/5.3.0/envs/tb-profiler2.1_env/share/tbprofiler/tbdb.config.json'

Why is this happening? Please let me know.

**Comment by ponomarevsy** [comment]
PS: There is no such file as 'tbdb.config.json',

$ ls -l /pathtoAnaconda2/5.3.0/envs/tb-profiler2.1_env/share/tbprofiler/tbdb.config.json
ls: cannot access /pathtoAnaconda2/5.3.0/envs/tb-profiler2.1_env/share/tbprofiler/tbdb.config.json: No such file or directory

**Comment by ponomarevsy** [comment]
The above was solved by running the following command:

» **tb-profiler update_tbdb**
 
Running command:
set -u pipefail; git pull
 
Running command:
set -u pipefail; python parse_db.py --seqname Chromosome
 
Running command:
set -u pipefail; tb-profiler load_library tbdb

However, we are hitting a new error now:

Running command:
set -u pipefail; bwa index /pathtoAnaconda2/5.3.0/envs/tb-profiler2.1_env/share/tbprofiler/tbdb.fasta
**Command Failed! Please Check!**

**Comment by jodyphelan** [comment]
Can you run ```bwa index /pathtoAnaconda2/5.3.0/envs/tb-profiler2.1_env/share/tbprofiler/tbdb.fasta``` and send the output?

**Comment by jodyphelan** [comment]
These issues seem related... it looks like you dont have permission to create files in the anaconda folder. The first time you run, it will create the BWA index which will create some files in `pathtoAnaconda2/5.3.0/envs/tb-profiler2.3_env/share/tbprofiler/. Maybe you can try running it as sudo?

**Comment by ponomarevsy** [comment]
Hmm... I had to change permissions on a bunch of files:

$ ls -l /pathtoAnaconda2/5.3.0/envs/tb-profiler2.3_env/share/tbprofiler/
total 36736
-rw-rw-r-- 2 appbuild appbuild 1583007 Jun 10 15:51 tbdb.ann.txt
-rw-rw-r-- 2 appbuild appbuild   29253 Jun 10 15:51 tbdb.barcode.bed
-rw-rw-r-- 2 appbuild appbuild    1890 Jun 10 15:51 tbdb.bed
-rw-rw-r-- 1 appbuild appbuild     638 Jun 10 15:51 tbdb.config.json
-rw-rw-r-- 2 appbuild appbuild   64078 Jun 10 15:51 tbdb.dr.json
-rw-rw-rw- 2 appbuild appbuild 4411545 Jun 10 15:51 tbdb.fasta <-
-rw-rw-rw- 1 appbuild appbuild      12 Jun 11 15:58 tbdb.fasta.amb <-
-rw-rw-rw- 1 appbuild appbuild      45 Jun 11 15:58 tbdb.fasta.ann <-
-rw-rw-rw- 1 appbuild appbuild 4411632 Jun 11 15:58 tbdb.fasta.bwt <-
-rw-rw-r-- 1 appbuild appbuild      38 Jun 10 15:51 tbdb.fasta.fai
-rw-rw-rw- 1 appbuild appbuild 1102885 Jun 11 15:58 tbdb.fasta.pac <-
-rw-rw-rw- 1 appbuild appbuild 2205816 Jun 11 15:58 tbdb.fasta.sa <-
-rw-rw-r-- 2 appbuild appbuild 2346899 Jun 10 15:51 tbdb.gff
-rw-rw-r-- 2 appbuild appbuild 2601153 May  6 05:24 tbprofiler.test.fq.gz

Should all files in the above directory have write permissions for all users (a+w) or is there a different solution? Please let me know.

**Comment by jodyphelan** [comment]
The `/pathtoAnaconda2/5.3.0/envs/tb-profiler2.3_env/share/tbprofiler/` directory should have write permissions to the user. This is where all the library files are created/copied to. Alternatively you can install a local version of ana/miniconda and this should solve these issues.

**Comment by ponomarevsy** [comment]
Understood. Thanks for your help, @jodyphelan! It seems to work now...

**Comment by jodyphelan** [comment]
No probs!
