### ISSUE TITLE
error during run of pipeline

### ISSUE THREAD

**Issue by princenanaowusu** [jodyphelan/TBProfiler#42]
I need help with solving this error: Below is the error message

Running command:
set -u pipefail; samtools view -bL /home/prince/anaconda3/share/tbprofiler/tbdb.bed ./G32753.bam | samtools depth -aa --reference /home/prince/anaconda3/share/tbprofiler/tbdb.fasta -
Traceback (most recent call last):
  File "/home/prince/anaconda3/bin/tb-profiler", line 335, in <module>
    args.func(args)
  File "/home/prince/anaconda3/bin/tb-profiler", line 89, in main_profile
    results["db_version"] = json.load(open(conf["version"]))
KeyError: 'version'

**Comment by jodyphelan** [comment]
Can you run `tb-profiler update_tbdb` and check if that fixes the issue?

**Comment by princenanaowusu** [comment]
Perfect!
That solved the issue
Thanks

**Comment by jodyphelan** [comment]
No probs!
