### ISSUE TITLE
estimated fraction  = 0 ?

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#45]
Hi Jody, 

       I am running version 4.0 and am getting estimated fraction = 0 for some variants.  I am wondering what this means.   For example for SRR6356938.   I get the report below:

Maybe these are being reported as integers instead of decimals? 

      Thanks for your continued development of this fantastic tool!  Best, 

 Michael 

------------------------------------------------------------------------------

Resistance variants report
-----------------
Genome Position	Locus Tag	Gene	Change	Estimated Fraction	Drug
1918631	Rv1694	tlyA	c.693 694insG	0	capreomycin
2155168	Rv1908c	katG	p.Ser315Thr	0	isoniazid
1673425	Rv1483	fabG1	c.-15C>T	0	isoniazid,ethionamide
761109	Rv0667	rpoB	p.Asp435Phe	0	rifampicin
2715342	Rv2416c	eis	c.-10G>A	0	kanamycin

**Comment by harrismia** [comment]
It looks like this is a problem in the .variants.txt file after doing a collate.  When I look at the values they all appear to be zero.

**Comment by jodyphelan** [comment]
Hi Michael,

Which version of python are you running? This might be an issue with python2.

Jody

**Comment by harrismia** [comment]
Hi Jody, 

    We are running python version 2.7 .     What version should we be using?   Thanks,

Michael

**Comment by jodyphelan** [comment]
I have tested with python2.7 and it reproduces the bug. It is due to the way python 2 and 3 differ in the way they use the `/` operator for division. A quick fix would be to use python3. Meanwhile I will work towards adding backwards compatibility

**Comment by harrismia** [comment]
Hi Jody,

Thanks for looking into this issue!  I will ask that the tool be reinstalled in the python 3 environment.

   Best,

Michael

Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by jodyphelan** [comment]
No Problem!
