### ISSUE TITLE
estimated fraction = 0 in  variants.txt file 

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#46]
Hi Jody, 

     After installing python 3.7.3 .  tb-profiler profile  seems to work fine producing estimated fractions etc.  

     When I run tb-profiler collate    the variants.txt file seems to have all zeros.   I went back to the  tbprofiler 2.3 version and this also seems to have the all zeros problem.  

    For example using the SRR ids : 

SRR6357000
SRR6807694
SRR6807754
  
    All of these have the katG Ser315Thr mutation which is correctly reported in the results.txt files but after running  tb-profiler collate .      the  variants.txt file has all zeros .  

   Best, 

        Michael

**Comment by jodyphelan** [comment]
Hi Michael,

Will take a look at this.

Jody

**Comment by harrismia** [comment]
Thanks!

Michael A. Harris
Senior Informatics Scientist
Bioinformatics and Computational Biosciences Branch (BCBB)
OCICB/OSMO/OD/NIAID/NIH

5601 Fishers Lane, Room 4A33A
Rockville, MD 20852
Office 301-761-6764
Web: BCBB Home Page<http://www.niaid.nih.gov/about/organization/odoffices/omo/ocicb/Pages/bcbb.aspx>
Twitter: @NIAIDBioIT<https://twitter.com/NIAIDBioIT>

Disclaimer: The information in this e-mail and any of its attachments is confidential and may contain sensitive information. It should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices. National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender's own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by jodyphelan** [comment]
Hi Michael,

This should now be fixed.

Jody

**Comment by harrismia** [comment]
Hi Jody, 

     Thanks a lot! I will check it out and let you know if i find any issues.   Best, 

Michael
