### ISSUE TITLE
TB Profiler hangs on some sequences

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#5]
I tried running TB Profiler on the sequence in the short read archive:  SRR1159154   

[https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1159154](url)

It seems to hang after printing the line:   Checking lineage

Here are the details:    I executed the command:

**[TBprofiler_debug]$ tb-profiler full -1 ../../SRR1159154_1.fastq.gz -2 ../../SRR1159154_2.fastq.gz -t 4 -d ./ -p SRR1159154_debug --verbose**

which produces output: 

Checking input files
Performing mapping
/sysapps/cluster/software/TBProfiler/0.2/bin/snap-aligner paired /sysapps/cluster/software/TBProfiler/0.2/ref -compressedFastq ../../SRR1159154_1.fastq.gz ../../SRR1159154_2.fastq.gz -t 4 -o -bam - | /sysapps/cluster/software/TBProfiler/0.2/bin/samtools sort -o SRR1159154_debug.bam -@ 4 - && /sysapps/cluster/software/TBProfiler/0.2/bin/samtools index SRR1159154_debug.bam
Calling Variants
/sysapps/cluster/software/TBProfiler/0.2/bin/samtools view -bL /sysapps/cluster/software/TBProfiler/0.2/db/drdb.bed SRR1159154_debug.bam | /sysapps/cluster/software/TBProfiler/0.2/bin/lofreq indelqual -u 30 - | /sysapps/cluster/software/TBProfiler/0.2/bin/lofreq call -f /sysapps/cluster/software/TBProfiler/0.2/ref/MTB-h37rv_asm19595v2-eg18.fa --call-indels - | /sysapps/cluster/software/TBProfiler/0.2/bin/bcftools norm -f /sysapps/cluster/software/TBProfiler/0.2/ref/MTB-h37rv_asm19595v2-eg18.fa - > SRR1159154_debug.dr.vcf
Loading annotation
Checking lineage_

**Comment by jodyphelan** [comment]
Hi,

I have run that sample through with no errors. Are you on the latest version of the TBProfiler?

Jody

**Comment by harrismia** [comment]
Is there an easy way to tell what version of tb-profiler I have?  It would be useful to add a -version option to print the software version number.   

When I ran on my Mac I go the error below.   The previous error (hanging on checking lineage) happened when I ran on a linux environment.   There may be something particular about the input file as I am able to run other samples without a problem.  I will  try upgrading tb-profiler to see if that helps. 

**tb-profiler full -1 ./SRR1159154_1.fastq.gz -2 ./SRR1159154_2.fastq.gz -t 4 -d ./ -p SRR1159154_debug --verbose**
Checking input files
Performing mapping
/Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/bwa mem -t 4 /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa ./SRR1159154_1.fastq.gz ./SRR1159154_2.fastq.gz | /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/samtools view -@ 4 -b - | /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/samtools sort -@ 4 -o SRR1159154_debug.bam - && /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/samtools index SRR1159154_debug.bam
Calling Variants
/Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/samtools view -bL /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/db/drdb.bed SRR1159154_debug.bam | /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/lofreq indelqual -u 30 - | /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/lofreq call -f /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa --call-indels - | /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/bin/bcftools norm -f /Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/ref/MTB-h37rv_asm19595v2-eg18.fa - > SRR1159154_debug.dr.vcf
Loading annotation
Traceback (most recent call last):
  File "/Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/tb-profiler", line 581, in <module>
    args.func(args)
  File "/Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/tb-profiler", line 540, in main_run_pipeline
    small_dr_variants,small_other_variants = small_dr_var(args.prefix)
  File "/Users/harrismia/Tools/ResistancePrediction/TBProfiler/TBProfiler/tb-profiler", line 354, in small_dr_var
    change_str = "%s%s%s" % (codons[ref_codon],ann[chrom][pos]["codon_num"],codons[alt_var])
KeyError: 'ANG'

**Comment by harrismia** [comment]
After upgrading this completes with no problems on my Mac.  I will try upgrading our linux environment and try running again.  Thanks, 

 Michael

**Comment by jodyphelan** [comment]
Hi Michael,

Great to hear it works now. I have added a version function to the tool (now at v0.1), thanks for the suggestion.

Jody

**Comment by harrismia** [comment]
Hi Jody, 

      Thanks for adding the version function! 

         Michael
