### ISSUE TITLE
Feature request: allow DB to be specified outside of TB profiler install dir

### ISSUE THREAD

**Issue by pvanheus** [jodyphelan/TBProfiler#50]
I have encountered quite a few requests to use a database of variants besides the default one.

Currently the `--db` parameter for the `profile` subcommand, the `update_tbdb` and `load_library` commands all assume that the user has write access to the installation path of the TBProfiler tool. This is not the case in a shared (e.g. cluster) installation or where the software is provided via a Singularity (or Docker) container.

Can an option be provided to use a database outside the installation path? Thanks

**Comment by jodyphelan** [comment]
That sounds like a great idea. I'll let you know when it is implemented!

**Comment by jodyphelan** [comment]
@pvanheus  Would the user have write access to where the external DB is stored?

**Comment by jodyphelan** [comment]
This option is now available using `--external_db /path/to/external/db/prefix`. It needs the path to the db files (.fa .gff .bed ...etc). It should be available with the latest commit and also on conda. Let me know how it goes!

Jody

**Comment by pvanheus** [comment]
Thanks @jodyphelan ! I'll test it when I've got the latest version of the Galaxy wrapper working! BTW do you have tools for maintaining the DB or do you do it by hand? If you are lacking tools perhaps open some feature requests. :)

**Comment by jodyphelan** [comment]
At the moment I am doing it by hand, would be great if there were any tools to help. Do you have any in mind?
