### ISSUE TITLE
Using full path for --dir when using tb-profiler collate not working 

### ISSUE THREAD

**Issue by jeffreybm** [jodyphelan/TBProfiler#51]
When using tb-profiler collate as part of a pipeline, I cannot use a full path to the working directory.  I get error: FileNotFoundError: [Errno 2] No such file or directory : results/SAMPLEA.results.json

I can collate if I go to the tb_profiler directory where results direcotry is and run from there

**Comment by jodyphelan** [comment]
Hi Jeffrey,

This looks like a bug in the code. I'll look into it and let you know what I find.

Jody

**Comment by jodyphelan** [comment]
Hi Jeffrey,

The code has been updated in the latest commit. I will also update this in the next conda release.

Jody
