### ISSUE TITLE
tbdb.conf.json not found for `vcf_profile`

### ISSUE THREAD

**Issue by pvanheus** [jodyphelan/TBProfiler#52]
Hi @jodyphelan in `setup.py` (https://github.com/jodyphelan/TBProfiler/blob/master/setup.py#L26) lists the data files for the default database. In the main code (e.g. https://github.com/jodyphelan/TBProfiler/blob/master/tb-profiler#L209) you check for the existence of this file. The result is that with the current default conda install the `vcf_profile` command does not work.

The `tbdb.config.json` stores paths to the relevant files in the DB, but, as far as I can tell, these paths are absolute paths. There is thus no way to distribute a pre-computed version of this file. I'm trying to think of a workaround for this problem, but thought I'd just let you know of its existence for now.

**Comment by jodyphelan** [comment]
Ah thanks for letting me know, I'll try come up with a solution for this.

**Comment by jodyphelan** [comment]
Hi Peter,

In the latest commit I've removed the necessity of having a `.conf.json` file and instead just  create the object in runtime when the program loads. I think this will solve the issue of having absolute paths as you only have to specify where the files are.

Let me know what you think...

Jody

**Comment by pvanheus** [comment]
That looks like an elegant solution @jodyphelan.I look forward to resting the resulting release and hopefully incorporating this into the Galaxy wrapper.

**Comment by jodyphelan** [comment]
This issue is now fixed in the latest conda build (v2.6.1)
