### ISSUE TITLE
Haarlem sublineage

### ISSUE THREAD

**Issue by arturotorreso** [jodyphelan/TBProfiler#53]
Hi, 

I saw that the database used by TBProfiler identifies the Haarlem sublineage as lineage4.1.1.3, instead of with lineage4.1.2.1 as in the Coll et all publication. Is there any reason for this change? 

Thank you, 
Arturo

**Comment by jodyphelan** [comment]
Thanks for bringing this up. I'll take a look at this and let you know ASAP.

Jody

**Comment by jodyphelan** [comment]
This should be fixed with the new database. Please run `tb-profiler update_tbdb` to get the latest version.
