### ISSUE TITLE
pncA mutation

### ISSUE THREAD

**Issue by adippenaar** [jodyphelan/TBProfiler#54]
Hi Jody, 

I saw the following: 

All mutations reported as refAA/position/mutAA, came across pncA Y>103*
Should this not be Tyr103* or Tyr103Stop ? Or is this depicted in this way on purpose because it is not a standard amino acid change? 

Best,
Anzaan

**Comment by jodyphelan** [comment]
Hi Anzaan,

Can you let me know the version of tb-profiler you are using? This issue should be fixed in the latest release.

```
tb-profiler version
```

Jody

**Comment by adippenaar** [comment]
Hi Jody,

Thank you for your fast response. I was using version 2.4.0.

After updating today with: (Is this the correct way to update to the latest version?)
conda install -c bioconda tb-profiler samtools=1.9=h7c4ea83_11 ncurses=6.1=h0a44026_1002
I got the same result.



pncA containing line below:
Pyrazinamide R pncA 103Y>103* (1.00)


Best,
Anzaan



Anzaan Dippenaar  |  PhD (SU)
Post-Doctoral Research Fellow: Department of Biomedical Sciences
Division of Molecular Biology and Human Genetics | Faculty of Medicine and Health Sciences
DST-NRF Centre of Excellence for Biomedical Tuberculosis Research | SAMRC Centre for Tuberculosis Research
e: adippenaar@sun.ac.za  |  t: +27 21 938 9957  |  a: Room 315, FISAN Building, Francie van Zijl Drive

[1512997505056_uni.jpg]
________________________________

**Comment by jodyphelan** [comment]
Thanks for the info. The ocnversion of the mutations is done by a library called pathogen-profile it could be that it needs to be updated too. Can you run  `conda env export | grep profiler` and let me know the results? Thanks!

**Comment by adippenaar** [comment]
Hi Jody,

The result is:

- pathogen-profiler=1.3=py_0
- tb-profiler=2.4=py_0


Best,
Anzaan

Anzaan Dippenaar  |  PhD (SU)
Post-Doctoral Research Fellow: Department of Biomedical Sciences
Division of Molecular Biology and Human Genetics | Faculty of Medicine and Health Sciences
DST-NRF Centre of Excellence for Biomedical Tuberculosis Research | SAMRC Centre for Tuberculosis Research
e: adippenaar@sun.ac.za  |  t: +27 21 938 9957  |  a: Room 315, FISAN Building, Francie van Zijl Drive

[1512997505056_uni.jpg]
________________________________

**Comment by jodyphelan** [comment]
It looks like the tools haven't been updated. If you run the following you should get the latest versions:
```
conda install tb-profiler=2.6 pathogen-profiler=1.6
tb-profiler update_tbdb
```
This should fix the issue, but let me know if you are still having problems.

Jody

**Comment by adippenaar** [comment]
Thank you, Jody. That seems to have done the trick.

Kind Regards,
Anzaan

Anzaan Dippenaar  |  PhD (SU)
Post-Doctoral Research Fellow: Department of Biomedical Sciences
Division of Molecular Biology and Human Genetics | Faculty of Medicine and Health Sciences
DST-NRF Centre of Excellence for Biomedical Tuberculosis Research | SAMRC Centre for Tuberculosis Research
e: adippenaar@sun.ac.za  |  t: +27 21 938 9957  |  a: Room 315, FISAN Building, Francie van Zijl Drive

[1512997505056_uni.jpg]
________________________________
