### ISSUE TITLE
Feature request:   put version of tbdb file in the results.txt file and suggestion. 

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#56]
Hi Jody, 

Here are a few suggestions to make a great tool even better: 

It might be a good idea to put the version number of the tbdb file in the in results.txt file so that a user can know which version of the tbdb.csv and barcode.bed files were used to  generate the results.   The Analysis pipeline specifications section might be a good place to put these file version numbers.   

Also, it might be worth considering adopting a release strategy like the one used for Plink. See https://www.cog-genomics.org/plink/1.9/  . They have a stable build and a development build.  This way users can decide if they want to use the newest features in a release candidate build or if they prefer to use a widely tested but older version of the software.  You would have the opportunity to fix issues with the a release candidate build before promoting it to a stable build. 

Thanks again for all of your hard work and for providing this fantastic tool to the community!

Michael

**Comment by jodyphelan** [comment]
Hi Michael,

I have included a database version line in the text and csv outputs now. It simply concatenates the version name, commit string, author and date separated by an underscore (e.g `tbdb_f8bc66ce9368b640201d58d3ea674eae9b550e8d_Jody Phelan <jody.phelan@lshmt.ac.uk>_Wed Aug 7 12:55:33 2019 +0100`. Would this be suitable? 
By default these values are taken from the git config when the db is being built, but can all be overridden with custom strings.

I like the idea of having a stable and development build. I'll take a look at the plink strategy, thanks for the suggestion!

No problem, thanks for testing it out and giving all the useful feedback.
Jody

**Comment by harrismia** [comment]
Hi Jody, 

Thanks! The text string in the .txt and .cvs outputs is helpful.   For future consideration, I had a more human readable version number in mind.   Something like:    tbdb_v1.9 ,   barcode.bed_v3.2 .     Just a thought.. 

   Best,

      Michael

**Comment by jodyphelan** [comment]
Sounds loke a good idea, I'll give it some more thought and try implement something soon.

**Comment by harrismia** [comment]
Great!
