### ISSUE TITLE
tb-profiler update_tbdb comman failed

### ISSUE THREAD

**Issue by lexleong** [jodyphelan/TBProfiler#57]
Hi Jody,
I have installed tb-profiler using conda. It is in its own env. But everytime I run tb-profiler, it has the error during the update_tbdb.

`Running command:
set -u pipefail; tb-profiler update_tbdb
Command Failed! Please Check!
`
I tried running the tb-profiler update_tbdb it gave me similar error.

`(tbprofiler)$ tb-profiler update_tbdb
Running command:
set -u pipefail; git pull
Running command:
set -u pipefail; python parse_db.py --seqname Chromosome
Command Failed! Please Check!`

I wonder if you could help me out? 

Cheers,
Lex

**Comment by lexleong** [comment]
Hi Jody,
I have reinstall the conda commit and I think the bug has is gone now. Thanks! L

**Comment by jodyphelan** [comment]
No probs!
