### ISSUE TITLE
main_lineage column empty, sub_lineage column "root" for all samples 

### ISSUE THREAD

**Issue by fgmp** [jodyphelan/TBProfiler#58]
Hello Jody, 
I ran the profile command on a set of paired-end reads:
tb-profiler profile --threads 8 --mapper bwa --caller BCFtools --verbose 2 --read1 $f1 --read2 $f2 -p $BASE

However when I run collate on the results folder, the main_lineage column is empty and the sub_lineage column is assigned to "root" for all of my samples, although all other columns are as expected. I find the same result for the test run samples ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR166/009/ERR1664619/ERR1664619_{1,2}.fastq.gz

**Comment by jodyphelan** [comment]
Hi,

I've tried to replicate it for ERR1664619, however I've get the following after using `tb-profiler collate`:

| sample  | main_lineage|    sub_lineage |
| - | - | - |
| ERR1664619 |      lineage4 |        lineage4.3.4.2 |

However I have replicated this issue in other samples. I checked a few and noticed that all samples had low coverage or were contaminated with other sequence data. Can you check that you have good coverage?

Jody

**Comment by fgmp** [comment]
Dear Jody, 
I have reinstalled tb-profiler using conda since the recent bug fix (issue #57) and tb-profiler is running as expected now along with the lineages reported. My previous installation was done manually in a new conda environment, so the issue might have had to do with my installation. 
Thank you!

**Comment by jodyphelan** [comment]
Great thanks for letting me know!
