### ISSUE TITLE
Double pipe error

### ISSUE THREAD

**Issue by mriglobal** [jodyphelan/TBProfiler#60]
I'm not sure if this is an issue using the --platform minION or if it's a consequence of something else, but when running tb-profiler on my data, I encountered an error after bcftools view was run in a pipeline that contained a double pipe (looked like | | with no command inside).

I'm unsure if a command didn't print to the pipeline or if there's a typo because I couldn't immediately find this line in the code. I have attached the output of tbprofiler as well as the offending command run from the command line, outside of tb-profiler.

I have removed one of the two pipes from the command and it ran successfully, but I haven't been able to integrate that into tb-profiler.

[tbprofiler.log.txt](https://github.com/jodyphelan/TBProfiler/files/3783962/tbprofiler.log.txt)

**Comment by jodyphelan** [comment]
Thanks for reporting the issue. I'll look into this and get back to you asap.

Jody

**Comment by mriglobal** [comment]
It's looking to me like it's going to be in bam.py
`self.mix_cmd = "| bcftools +setGT -- -t q -i 'GT=\"het\" & AD[:1]/(AD[:0]+AD[:1])<0.7' -n . |" if mixed_as_missing else ""

self.af_filter_cmd = "| bcftools view -i 'AF>%s'" % af
 35         run_cmd("bcftools view %(gbcf_file)s %(mix_cmd)s %(af_filter_cmd)s | bcftools view -T ^%(del_bed)s -g miss -O b -o %(missing_bcf_file)s" % vars(self))
 36         run_cmd("bcftools view %(gbcf_file)s %(mix_cmd)s %(af_filter_cmd)s | bcftools view -g ^miss -c 1 -O b -o %(variant_bcf_file)s" % vars(self))`

Because mix_cmd is called with minION data and ends with a pipe that gets immediately met with another pipe as af_filter_cmd is the next command called.

**Comment by jodyphelan** [comment]
This issue (along with a few others) should be fixed with the latest commit. Please update both pathogen-profiler and tb-profiler libraries. I will release a new version on conda soon.

Jody

**Comment by nilay-p** [comment]
Hi Jody,
I am a beginner in bioinformatics data analysis and having the same issue as mriglobal had in my analysis. As a newbie , it is difficult for me to fix the problem. I hope new version to be released soon.

**Comment by jodyphelan** [comment]
Hi @nilay-p,

The latest version on conda (v2.7.1) should have these issues fixed!

Jody
