### ISSUE TITLE
Is this python 2 or python 3 ?

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#61]
I am not a python expert, but I see `#! /usr/bin/env python` and that is ambiguous these days, but normally means python 2 .  But I see `print()` which is python 3?

**Comment by jodyphelan** [comment]
Ah yeah, to be honest I'm always a bit confused with what I should put there but the code should all be backwards compatible. I'll run some tests though to double check!

**Comment by tseemann** [comment]
My rule is to _never_ refer to bare `python` as it could be either. 
Explicitly use:
```
#!/usr/bin/env python3
```
or
```
#!/usr/bin/env python2
```

**Comment by jodyphelan** [comment]
Tested on python2 and 3 and all code in the main library is compatible. Changed the header to `#! /usr/bin/env python3`

**Comment by tseemann** [comment]
Can you add this fact to README.md , that it works on both?
