### ISSUE TITLE
bwa index - no permissions

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#64]
We install software as a separate user.
I ran `update_tbdb` when installing it.

When i ran the example test line as a different regular user I get this error:

```
Running command:
set -u pipefail; bwa index /opt/python/share/tbprofiler/tbdb.fasta
Command Failed! Please Check!
```
It's trying to index the reference.
Does it do this every time you run?
Can it be done at install stage just once, and then checked to see if it already exists?
ie. could `update_tbdb` do it?

PS. This also stops it working in Docker and Singularity containers.

**Comment by pvanheus** [comment]
I thought that was fixed in the latest `conda` package. How did you install it @tseemann ? (I encountered a problem running it on usegalaxy.eu because they use Singularity containers for all their tools)

**Comment by tseemann** [comment]
```
pip3 install git+https://github.com/jodyphelan/pathogen-profiler.git
pip3 install git+https://github.com/jodyphelan/TBprofiler.git
```

**Comment by tseemann** [comment]
One way to resolve this is to use `os.tempdir` and put the bwa index in there:
```
bwa index
 -p STR    prefix of the index [same as fasta name]
```

**Comment by jodyphelan** [comment]
This should only be if a user updates the database. We fixed the issue to create the samtools and gatk reference index but not the bwa one. Should now be fixed

**Comment by tseemann** [comment]
@jodyphelan usually when you fix a bug reported in an issue, you put the string "`Issue #64`" in the commit message and it will link it to this issue so we can see that change was actually made. Makes it easier for you too to see what was done, as sometimes things get forgotten/lost.

**Comment by jodyphelan** [comment]
Ah sorry by bad! I'll try to keep the commits more organised in the future!!

**Comment by tseemann** [comment]
You have issues, man.  :-P
