### ISSUE TITLE
Option to disable trimmomatic step?

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#65]
Would it be possible to skip the `trimmomatic` step with a new `--no-trim` option?

```
set -u pipefail; trimmomatic PE -threads 1 -phred33 R1.fq.gz R2.fq.gz tbp2/tbprofiler_1_trim_pair.fq
 tbp2/tbprofiler_1_trim_unpair.fq tbp2/tbprofiler_2_trim_pair.fq tbp2/tbprofiler_2_trim_unpair.fq 
LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
```
It see it only does quality/length trimming anyway (not adapters) but MINBQ=3 and MINLEN=50 is already done by the Illumina software anyway so we don't really need that step.

You could skip it and set the 'orphan` files to `/dev/null` in your pipeline perhaps.

(I know this is also  `pathogen-profiler` related)

**Comment by jodyphelan** [comment]
Ah I thought MINLEN was the minimum length to keep after trimming?
In any case there is now a `--no_trim` option.
