### ISSUE TITLE
LoFreq in flow diagram but not in tool?

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#66]
![image](https://user-images.githubusercontent.com/453972/68814991-404c6700-06ce-11ea-8d18-ae39e0120aae.png)
```
  --caller {BCFtools,GATK}
                        Variant calling tool to use. (default: GATK)
```

**Comment by jodyphelan** [comment]
Good spot! Taken out SAMtools nad LoFreq for variant calling and added in GATK
