### ISSUE TITLE
GATK missing from prereqs

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#68]
> The following pre-requisites will be needed at runtime: trimmomatic, bwa, minimap2, bowtie2, samtools, bcftools, tqdm and parallel.

Given the default caller is now GATK, it should be listed?
If the tools have minimum versions can you please list them?
Is it gatk 3 or 4 ?

**Comment by jodyphelan** [comment]
Added in GATK and versions for all other programs.
