### ISSUE TITLE
delly call issue??

### ISSUE THREAD

**Issue by foamy1881** [jodyphelan/TBProfiler#69]
I install tb-profiler from conda and it work until this part? it said command failed please check base? 

set -u pipefail; delly call -t DEL -g /home/yfong/miniconda3/share/tbprofiler/tbdb.fasta ./M004.bam -o ./M004.targets.delly.bcf
Command Failed! Please Check!(base) 

Can anyone please help me? also is there an option to run multiple files together under the sequencesfiles folder that contains many read 1 and read 2?

**Comment by jodyphelan** [comment]
Can you run the command that failed (below) and post the output?
```
delly call -t DEL -g /home/yfong/miniconda3/share/tbprofiler/tbdb.fasta ./M004.bam -o ./M004.targets.delly.bcf
```

**Comment by foamy1881** [comment]
I manage to solve it by deleting and reinstall with fresh conda environment. Is all good now. case close.
