### ISSUE TITLE
edit the lineages.bed file

### ISSUE THREAD

**Issue by samlipworth** [jodyphelan/TBProfiler#7]
Hi I want to edit the lineages.bed file to add new sub-lineages - this is straightforward but then when I call tb profiler it does not recognise the new sub lineage - is there anything else I have to change?

**Comment by jodyphelan** [comment]
Hi,

I haven't actually tested to call new lineages. I will check this and release a fix asap.

Jody

**Comment by samlipworth** [comment]
Thanks very much Jody!

**Comment by jodyphelan** [comment]
Hi Sam,

I have added the capability to add custom lineages now. Just make sure to test it out first and let me know if it works.

Jody

**Comment by samlipworth** [comment]
Hi Jody,

Thanks very much for doing this however I cant get it to work.  I copied your formatting in the bed file - could you perhaps supply an example you used to test this so I can see what I am doing wrong?

Sam

**Comment by samlipworth** [comment]
Magic it is working now, very many thanks indeed.

**Comment by jodyphelan** [comment]
No Probs! Let me know if you would like any other features added.

Jody
