### ISSUE TITLE
More information how to generate tree of ITOL?

### ISSUE THREAD

**Issue by foamy1881** [jodyphelan/TBProfiler#70]
I tried the 'tb-profiler collate' it generated random files for ITOL config. Is there anymore tutorial on this matter? I also tried import my own tree (nexus format) and it does work too. Sorry my knowledge is limited and would like to generate the figure shown in tb-profiler.

**Comment by foamy1881** [comment]
Somehow the tb-profiler collate work but it seem doesnt work as it didnt combine the JSON file? also config files from ITOL doesnt work and miss .tree figure too. Please help.

**Comment by jodyphelan** [comment]
Did you get any error message when you ran it?

With the producing the figure... if you have loaded the tree in Itol you should be able to drag and drop the .itol.txt files into the browser and it should display the results. However if the .json file is empty then the itol config files will also be empty so we'll need to get that to work first!

**Comment by foamy1881** [comment]
Hi there is no error message..  I ran the tb-profiler collate and it return with the following, 

(tbprofiler) yfong@yfong-VirtualBox:~/Documents/software/tbprofiler$ tb-profiler collate
Using gff file: /home/yfong/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.gff
Using ref file: /home/yfong/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.fasta
Using ann file: /home/yfong/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.ann.txt
Using barcode file: /home/yfong/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.barcode.bed
Using bed file: /home/yfong/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.bed
Using json_db file: /home/yfong/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.dr.json
Using version file: /home/yfong/miniconda3/envs/tbprofiler/share/tbprofiler/tbdb.version.json
0it [00:00, ?it/s]
(tbprofiler) yfong@yfong-VirtualBox:~/Documents/software/tbprofiler$ 
It also generate the following files: 
tbprofiler/tbprofiler.dr.indiv.itol.txt  454 bytes
tbprofiler/tbprofiler.dr.itol.txt 272 bytes
tbprofiler/tbprofiler.json 2 bytes
tbprofiler/tbprofiler.lineage.itol.txt 394 bytes
tbprofiler/tbprofiler.txt 313 bytes
tbprofiler/tbprofiler.variants.txt 21.8 kB

from the result section for each jason files I have full information with kilobytes files..  You said to drag and drop .itol txt files and there are three of them being generated (does it mean i drop all of them to ITOL? also there is no .tree file from it and how I generate it via tbprofiler? I have my own tree previously generated from MEGA but when i load it from nexus format and drag the itol files it return with the following: 

Unknown variable 'FIELD_LABELS rifampicin'
Unknown variable 'FIELD_COLORS black'
Unknown variable 'FIELD_SHAPES 2'
Unknown variable 'SHOW_LABELS 1'
Unknown variable 'COLOR #ff0000'
Unknown variable 'DATASET_LABEL Drugs'
Failed to extract required data (DATASET_LABEL is missing). Please use the templates provided on the help pages.

Any information and help will be very useful. Please help.

**Comment by jodyphelan** [comment]
For the itol issue: I think this is an issue that was introduced with the latest version in conda. I will update the version on conda asap and let you know when you can upgrade. 

For the issue with the empty json file: You should run it and set the `--dir` flag to point to the results directory.

**Comment by foamy1881** [comment]
Will tbprofiler generate a .tree file for me or I need to generate it myself using other tool?

**Comment by jodyphelan** [comment]
You need to generate it with another tool. It just generates the itol config files

**Comment by foamy1881** [comment]
Ok understand with the tree loading now.... I just try the --dir and is working now...  looking forward for the update so I continue with the analysis. appreciate your help so much..

**Comment by foamy1881** [comment]
I just found another bug. One of the ITOL files generated for colour coding field seem to only return with only BLACK for all drug resistance genes. 


DATASET_BINARY |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SEPARATOR TAB |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
DATASET_LABEL    Drugs |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
COLOR      #ff0000 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
SHOW_LABELS    1 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
FIELD_SHAPES    2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 |  
FIELD_COLORS    black | black | black | black | black | black | black | black | black | black | black | black | black | black | black |  
FIELD_LABELS    rifampicin | isoniazid | ethambutol | pyrazinamide | streptomycin | fluoroquinolones | aminoglycosides | kanamycin | amikacin | capreomycin | ethionamide | para-aminosalicylic_acid | clofazimine | linezolid | bedaquiline

M032 | 1 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0
M147 | 1 | 1 | 1 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0
M067 | 1 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
M281 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0

**Comment by foamy1881** [comment]
Hi.. I explore the data generated via TB-Profiler. In the VCF folder they have many files type. Which of these I can use to view the SNP via vcf output? I need to generate a tree via VCF but only have gvcf output. Can anyone explain?

**Comment by jodyphelan** [comment]
Hi @foamy1881 

The the best file to use to view the SNPs are the ones ending in **targets.csq.vcf.gz**. These will contain all SNPs found in drug resistance genes with annotation. For phylogenies I would not recommend using these VCF files as they only contain the drug resistance regions, and so will not contain much variation contributing to the phylogenetic signal. I would recommend using gatk to generate whole genome VCFs by following their [best practices guidelines](https://software.broadinstitute.org/gatk/best-practices/workflow?id=11145).

**Comment by foamy1881** [comment]
Ok good to know. Have you fix the ITOL issue yet?

**Comment by jodyphelan** [comment]
Almost there... will you let know when its ready.

**Comment by foamy1881** [comment]
Thanks Thanks

**Comment by jodyphelan** [comment]
Should be fixed now!

**Comment by foamy1881** [comment]
How do I update it?

**Comment by jodyphelan** [comment]
You should be able to update using `conda install tb-profiler`

**Comment by foamy1881** [comment]
ok will try it and let you know. Thanks so much

**Comment by jodyphelan** [comment]
No probs, let me know how it goes!

**Comment by foamy1881** [comment]
All good... it work.. now just need a tree.. as when I import the itol config it said is missing sample with this id and so on.. I guess the tree sample name must be the same as tb-profiler output?

**Comment by jodyphelan** [comment]
Yes, the names must be exactly the same.

**Comment by malare** [comment]
Hi 
I was wondering if you have a recommendation which files (which format) to use for building a tree and which software to use. 
Thanks a lot

**Comment by jodyphelan** [comment]
Hi @malare 

Phylogenetic tree building is a bit outside the scope of TB-Profiler as it only analyses the drug-resistance genes. You could use the BAM files that the pipeline outputs and perform variant calling using software such as gatk or bcftools. The vcf files can then be merged and converged into fasta format to be input into a tree builder such as iqtree or raxml. There are several packages that can help with creating an alignment such as [snippy](https://github.com/tseemann/snippy) for example.

Jody
