### ISSUE TITLE
Is it possible for batch processing TBProfiler?

### ISSUE THREAD

**Issue by foamy1881** [jodyphelan/TBProfiler#71]
I have hundreds of isolates that I need to process. Is there a looping or batch processing option? can someone help?

**Comment by jodyphelan** [comment]
At the moment there is no in build functionality for this, however I will try create a function for it soon.

**Comment by ayooluwaB** [comment]
Visiting this issue as it applies to me. Have you been able to create a function for this? Thanks.

**Comment by jodyphelan** [comment]
Yes in the latest versions you can use `tb-profiler batch`. See https://jodyphelan.github.io/TBProfiler/en/batch-run/
