### ISSUE TITLE
Low estimated fraction being used in Drug resistance type and included in collated results

### ISSUE THREAD

**Issue by jeffreybm** [jodyphelan/TBProfiler#72]
In below profiler results file the gyrA p.Asp94Gly	SNP had an est. fraction of 0.093. Appears that this SNP fraction resulted in correctly calling NOT flouroquinalone resistance, however the Drug resistance status was called as XDR which should require flouroquinalone resistance.  Also this SNP was included in the collated merge.txt file for the oflaxacin - flouroquinalone fields.  Should this have been included in the collated for this sample? 

Strain: lineage4.1.2.1;lineage4.1.1.1
Drug-resistance: XDR

Lineage report
--------------
Lineage	Estimated Fraction	Family	Spoligotype	Rd
lineage4	1.000	Euro-American	LAM;T;S;X;H	None
lineage4.1	1.000	Euro-American	T;X;H	None
lineage4.1.2	1.000	Euro-American	T;H	None
lineage4.1.2.1	1.000	Euro-American (Haarlem)	T1;H1	RD182
lineage4.1.1.1	0.096	Euro-American (X-type)	X2	RD183

Resistance report
-----------------
Drug	Genotypic Resistance	Mutations
Rifampicin	R	rpoB p.Ser450Leu (1.00)
Isoniazid	R	katG p.Ser315Thr (1.00)
Ethambutol	R	embA c.-12C>T (1.00), embB p.Asp354Ala (1.00)
Pyrazinamide	R	pncA p.Tyr34* (1.00)
Streptomycin
Fluoroquinolones
Amikacin	R	rrs r.1401a>g (1.00)
Capreomycin	R	rrs r.1401a>g (1.00)
Kanamycin	R	rrs r.1401a>g (1.00)
Cycloserine
Ethionamide	R	ethA c.1242 1242del (0.96)
Clofazimine
Para-aminosalicylic acid
Delamanid
Bedaquiline
Linezolid

Resistance variants report
-----------------
Genome Position	Locus Tag	Gene	Change	Estimated Fraction	Drug
7582	Rv0006	gyrA	p.Asp94Gly	0.093	ciprofloxacin,fluoroquinolones,levofloxacin,moxifloxacin,ofloxacin
761155	Rv0667	rpoB	p.Ser450Leu	1.000	rifampicin
1473246	rrs	rrs	r.1401a>g	1.000	amikacin,aminoglycosides,capreomycin,kanamycin
2155168	Rv1908c	katG	p.Ser315Thr	1.000	isoniazid
2289140	Rv2043c	pncA	p.Tyr34*	1.000	pyrazinamide
4243221	Rv3794	embA	c.-12C>T	1.000	ethambutol
4247574	Rv3795	embB	p.Asp354Ala	1.000	ethambutol
4326231	Rv3854c	ethA	c.1242 1242del	0.957	ethionamide

**Comment by jodyphelan** [comment]
This looks to me like a bug in the way it is calling XDR (without using SNP fraction). I will take a look at this and get back to you.

**Comment by jodyphelan** [comment]
Hi @jeffreybm,

I have written some code which will filter variants based on the frequency specified using `--reporting_af`. So in this example the sample will be called **MDR** and the _gyrA p.Asp94Gly_ will **not** appear in the collated results. Is this the desired behavior?

Jody

**Comment by jeffreybm** [comment]
Hi @jodyphelan,

Yeah I think that behaviour would be good, at least for my groups purposes, where we would be collating several thousand samples placing all SNPs for each drug resistance into database.  Currently, using this collated merge.txt file, we would check if there is a SNP present for drug of interest we would 'assume' this sample is resistant to said drug. 

Would the --reporting_af default be set to 0.1 similar to the individual profile call?

Cheers,

Brendan

**Comment by jodyphelan** [comment]
Ah great! Yes it would be set to 0.1 by default and the user could change this.
I will update the git repo now and will update the the conda recipe asap.

Jody

**Comment by jodyphelan** [comment]
This is now available on bioconda (v2.8.0)
