### ISSUE TITLE
Release 2.7.2 still says --version is 2.7.1

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#73]
Forgot to bump `_VERSION` ? 
 https://github.com/jodyphelan/TBProfiler/blob/9b75dc957c3f8b52b377cd4fdf44878e9a6be8ed/tbprofiler/__init__.py

If you bump, please make it 2.7.3

**Comment by jodyphelan** [comment]
Oh yes I forgot! I'll be releasing a conda update soon. Will bump to 2.7.3.

**Comment by tseemann** [comment]
@jodyphelan no worries - i've done this myself too many times to remember!
