### ISSUE TITLE
rpoB_p.Ser450Leu not appearing in the output of collate

### ISSUE THREAD

**Issue by kristyhoran** [jodyphelan/TBProfiler#74]
Hi @jodyphelan I ran `tbprofiler collate` across a collection of `tbprofiler profile` outputs and the resulting `.variant.txt` file did not have the rpoB_p.Ser450Leu present, despite this being present in the `.json` file. Can you help me figure out why this might be? Thanks in advance!
Cheers
Kristy

**Comment by jodyphelan** [comment]
Hi @kristyhoran ,

Thanks for highlighting that bug. Should be fixed now!
I'll release a conda update asap.

Jody

**Comment by kristyhoran** [comment]
@jodyphelan Thank you!

**Comment by jodyphelan** [comment]
Ok, the conda recipe is now updated too.
