### ISSUE TITLE
tb-profiler vcf_profile issue in version 2.7.4: reporting_af

### ISSUE THREAD

**Issue by arturotorreso** [jodyphelan/TBProfiler#76]
Hi, 

I got the new version of TB profiler (2.7.4) and suddenly tb-profiler vcf_profile stopped working for VCF files for which previous versions worked. I'm using the Linux version. This is the error message: 

Running command:
set -u pipefail; rm 990496.tmp.vcf.gz
Traceback (most recent call last):
  File "/home/miniconda3/bin/tb-profiler", line 448, in <module>
    args.func(args)
  File "/home/miniconda3/bin/tb-profiler", line 286, in main_vcf_profile
    results = tbp.reformat(results,conf)
TypeError: reformat() missing 1 required positional argument: 'reporting_af'

I am now using previous versions where 'reporting_af' option wasn't included and it works fine, but it might be worth checking it out!

**Comment by jodyphelan** [comment]
Thanks for reporting this, I'll look into this!

**Comment by jodyphelan** [comment]
This should be fixed now with the latest release (v2.8.0)
