### ISSUE TITLE
Can't update tbdb

### ISSUE THREAD

**Issue by yujun2017** [jodyphelan/TBProfiler#79]
If we updated tbdb, the tbprofile will be failed in text output format.
we do find the json data will miss "DATE" field in db_version part. the new field will be "Merge". when we try to output text format, it will be failed.

**Comment by jodyphelan** [comment]
Hi @yujun2017. Thanks for reporting the issue. I'll look into this asap!

**Comment by jodyphelan** [comment]
This should now be fixed
