### ISSUE TITLE
What do the numbers after the variant call mean?

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#8]
Hi, 
        Can you  please let  me know what the numbers after the variant call mean?   For example:

         katG (Ser315Thr, 0.12)
                or 
         katG (Ser315Thr, 1.0)

          What does the 0.12  and 1.0 mean?   If I missed this in the documentation can you point me to the description?

 Thanks a lot!     Michael

**Comment by jodyphelan** [comment]
Hi Machael,

These numbers indicate the proportion of reads supporting that variant. For example if you had 100 reads at a position and 12 of them had a SNP which caused the Ser315Thr mutation then the it would display as `katG (Ser315Thr, 0.12)`. It can be thought of as a very basic insight into heteroresistance.

Jody

**Comment by harrismia** [comment]
Thanks for the information Jody!    This is very helpful.   Best, 

 Michael
