### ISSUE TITLE
Reference genome used to create BAM files do not match with the reference in the database

### ISSUE THREAD

**Issue by nilay-p** [jodyphelan/TBProfiler#81]
Hi Jody,
After updating TBProfiler from version 2.8.0 to 2.8.2 through conda, I have had the following issue;
`.....
Running command:
set -u pipefail; samtools index -@ 4 ./674-04_illumina.bam

Using ./674-04_illumina.bam

Please ensure that this BAM was made using the same reference as in the database.
If you are not sure what reference was used it is best to remap the reads.

Running command:
set -u pipefail; cat /Users/nilay/miniconda3/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 3 --col-sep " " "bcftools mpileup -f /Users/nilay/miniconda3/share/tbprofiler/tbdb.fasta -ABq0 -Q0 -a DP,AD -r {1} ./674-04_illumina.bam | bcftools call -mv | bcftools norm -f /Users/nilay/miniconda3/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -s 0 -Oz -o ./674-04_illumina.{2}.vcf.gz"`

Could you please help me to fix it?
Regards,
Nilay

**Comment by jodyphelan** [comment]
Hi Nilay,

Can you run the following command and check for any error:

```
cat /Users/nilay/miniconda3/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1""$2""$3}' | parallel -j 3 --col-sep " " "bcftools mpileup -f /Users/nilay/miniconda3/share/tbprofiler/tbdb.fasta -ABq0 -Q0 -a DP,AD -r {1} ./674-04_illumina.bam | bcftools call -mv | bcftools norm -f /Users/nilay/miniconda3/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -s 0 -Oz -o ./674-04_illumina.{2}.vcf.gz"
```

**Comment by nilay-p** [comment]
Hi Jody,

I have the following error

dyld: Library not loaded: @rpath/libquadmath.0.dylib
  Referenced from: /Users/nilay/miniconda3/lib/libcblas.3.dylib
  Reason: image not found

**Comment by jodyphelan** [comment]
This looks like an error with conda not installing the dependancies. If you just try `bcftools` do you get an error?

**Comment by nilay-p** [comment]
Yes, I get the error
dyld: Library not loaded: @rpath/libquadmath.0.dylib
  Referenced from: /Users/nilay/miniconda3/lib/libcblas.3.dylib
  Reason: image not found
Abort trap: 6

**Comment by jodyphelan** [comment]
Ok.. it looks like this is an issue with conda. You can try to set up an environment for tb-profiler using `conda create -n tbprofiler tb-profiler`.  You can then activate the env using `conda activate tbprofiler`. If this doesn't work you can try reinstall conda

**Comment by nilay-p** [comment]
Thanks Jody. It worked well now!
Best,
Nilay

**Comment by jodyphelan** [comment]
Perfect!
