### ISSUE TITLE
vcf_profile with haploid called vcf files

### ISSUE THREAD

**Issue by LennertVerboven** [jodyphelan/TBProfiler#82]
Hi,

When using TBProfiler on VCF files created using our own pipeline which outputs a single GT see below, the program crashes as it expects a GT call of the following  format X/X or X|X

`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  EC010A-268\nChromosome      237     .       G       A       28355.31        PASS    omited_for_clarity     GT:AD:DP:GQ:PL  1:51,0:51:99:0,1304`

I was wondering whether it is possible to modify the TBProfiler to also work with vcf files in the format presented above.

Kind regards
Lennert

**Comment by jodyphelan** [comment]
Hi Lennert,

Sure, I'll take a look.

Jody

**Comment by LennertVerboven** [comment]
To add to this comment, the error happens in TBProfiler/pathogenprofiler/vcf.py line 86 where it tries to split the two calls.

**Comment by jodyphelan** [comment]
Thanks @LennertVerboven. I've included a fix for this in the latest commits. I'll to update the conda recipe too.

Jody
