### ISSUE TITLE
Conda issue with bcftools

### ISSUE THREAD

**Issue by dankein** [jodyphelan/TBProfiler#84]
Hi,
FYI - I just installed v2.8.3 and I received the error below. 

Installing the bcftools conda package: bcftools=v1.10.2 resolved the error. 

`Please ensure that this BAM was made using the same reference as in the database.
If you are not sure what reference was used it is best to remap the reads.

Running command:
set -u pipefail; cat 
.conda/envs/tbprofiler_2.8.3b/share/tbprofiler/tbdb.bed | awk '{print $1":"$2"-"$3" "$1"_"$2"_"$3}' | parallel -j 64 --col-sep " " "bcftools mpileup -f .conda/envs/tbprofiler_2.8.3b/share/tbprofiler/tbdb.fasta -ABq0 -Q0 -a DP,AD -r {1} ./sample.bam | bcftools call -mv | bcftools norm -f 
.conda/envs/tbprofiler_2.8.3b/share/tbprofiler/tbdb.fasta | bcftools filter -e 'FMT/DP<10' -S . -Oz -o ./sample.{2}.vcf.gz"
Command Failed! Please Check!`

**Comment by jodyphelan** [comment]
Thanks! I'll update the conda recipe to `bcftools>=v1.10.2`. Do you know what the specific error that bcftools emitted?

**Comment by dankein** [comment]
I think bcftools wasn't present at all, but conda thought it was there.

**Comment by jodyphelan** [comment]
Ah ok that is strange....not sure how conda messed that up! Thanks for letting me know though
