### ISSUE TITLE
Lineage in tb-profiler using vcf_profile

### ISSUE THREAD

**Issue by LennertVerboven** [jodyphelan/TBProfiler#87]
HI

When using the collate function of the tb-profiler to aggregate all the results in single json file and to create the itol files I noticed that the lineage being called is a little off. I have attached (part of) the [collated file](https://github.com/jodyphelan/TBProfiler/files/4203185/sample.resistance.txt), the [itol lineage file](https://github.com/jodyphelan/TBProfiler/files/4203180/resistance.lineage.itol.txt) and some sample result json files as an example.

[S18BD01935.results.json](https://github.com/jodyphelan/TBProfiler/files/4203182/S18BD01935.results.txt)
[S19BD02502.results.json](https://github.com/jodyphelan/TBProfiler/files/4203183/S19BD02502.results.txt)

When looking at sample 'S19BD02502', we can see that lineage 4.4, 4.4.1, and 4.4.1.1 are called, the main lineage then becomes 'lineage4.4;lineage4.4.1;lineage4.4.1.1', same as the sublin. When this data get processed for the collated file the main and sub lineage both remain 'lineage4.4;lineage4.4.1;lineage4.4.1.1' and in the itol file, this lineage does not get recognized as lineage 4 so it get categorized as other.

When looking at sample 'S19BD02502', we see that lineage 2, 2.2, and 2.2.1 are called, making the main lineage 'lineage2' and the sublineage 'lineage2.2.1'. This get correctly translated to lineage2 in the itol file.

For some reason the behavior seems different in these two cases.

Additional note, I am once again profiling from an existing vcf file using vcf_profile followed by collate.

Kind regards
Lennert

**Comment by jodyphelan** [comment]
Hi Lennert,

I think this is because it looks for the main lineage (i.e. one without a decimal point) and if it can't find one it just concatenates all of them together. In the first case, it looks like "lineage 4" isn't called, perhaps due to a lack of coverage or a mutation in it's defining position in the genome. I'll try come up with a fix for this.

Jody

**Comment by jodyphelan** [comment]
This issue is now fixed. I will release on conda soon.
