### ISSUE TITLE
Interpretation of resistance mutations

### ISSUE THREAD

**Issue by flashton2003** [jodyphelan/TBProfiler#89]
Hi Jody,

I just want to check that I'm interpreting tb-profiler correctly.

If a sample has a variant in a drug column in the output of `tb-profiler collate`, then the inferred phenotype for that sample is that it is resistant to that antibiotic?

Thanks,

Phil

**Comment by jodyphelan** [comment]
Hi Phil,

Yes that is correct, if you see a mutation in a drug column then it is inferred to be resistant that drug.

Jody

**Comment by flashton2003** [comment]
Thanks!
