### ISSUE TITLE
total snps for each isolate?

### ISSUE THREAD

**Issue by foamy1881** [jodyphelan/TBProfiler#90]
Hi Jody, 

Where can i find the total SNP being called for each isolate? in the tb-profiler collate the final output txt summary files along with gene resistance information does not have the number of snps being called. need it for publications purposes.

**Comment by jodyphelan** [comment]
Hi @foamy1881 

Would you like this to be output in the collated file?

Jody

**Comment by foamy1881** [comment]
Hi Jody,

Yes please can it be done? Then I will have the total snps being called and useful for my circos plot. many thanks!

Sent from my iPhone

On 12/03/2020, at 3:44 AM, Jody Phelan <notifications@github.com> wrote:

﻿

Hi @foamy1881<https://github.com/foamy1881>

Would you like this to be output in the collated file?

Jody

**Comment by jodyphelan** [comment]
Ok has been added now and will be included in the next release.
