### ISSUE TITLE
samtools index hard-coded to use 4 threads

### ISSUE THREAD

**Issue by tseemann** [jodyphelan/TBProfiler#92]
1. when i use --threads=1 samtools index still uses 4 ; i think the args.threads is not being propogated to it, and it is using your default threads=4 (or 3)

2. can you make all default threads=1  and rely on args.threads otherwise?
https://github.com/jodyphelan/TBProfiler/search?q=threads&unscoped_q=threads

CC: @kristyhoran

**Comment by jodyphelan** [comment]
Ah good spot! I'll put the default as 1

**Comment by jodyphelan** [comment]
Should be fixed now
